SELECT DISTINCT
?is_linear ?is_not_linear
?is_dynamic ?is_static
?is_deterministic ?is_stochastic
?is_dimensionless ?is_dimensional
?is_time_continuous ?is_time_discrete
?is_space_continuous ?is_space_discrete
?reference
(GROUP_CONCAT(DISTINCT CONCAT(?sbf, " | ", ?sbfl, " | ", ?sbfd, " | ", ?sbfq); SEPARATOR=" <|> ") AS ?specialized_by)
(GROUP_CONCAT(DISTINCT CONCAT(?sf, " | ", ?sfl, " | ", ?sfd, " | ", ?sfq); SEPARATOR=" <|> ") AS ?specializes)
(GROUP_CONCAT(DISTINCT CONCAT(?abf, " | ", ?abfl, " | ", ?abfd); SEPARATOR=" <|> ") AS ?approximated_by)
(GROUP_CONCAT(DISTINCT CONCAT(?af, " | ", ?afl, " | ", ?afd); SEPARATOR=" <|> ") AS ?approximates)
(GROUP_CONCAT(DISTINCT CONCAT(?nbf, " | ", ?nbfl, " | ", ?nbfd); SEPARATOR=" <|> ") AS ?nondimensionalized_by)
(GROUP_CONCAT(DISTINCT CONCAT(?nf, " | ", ?nfl, " | ", ?nfd); SEPARATOR=" <|> ") AS ?nondimensionalizes)
(GROUP_CONCAT(DISTINCT CONCAT(?dbf, " | ", ?dbfl, " | ", ?dbfd); SEPARATOR=" <|> ") AS ?discretized_by)
(GROUP_CONCAT(DISTINCT CONCAT(?df, " | ", ?dfl, " | ", ?dfd); SEPARATOR=" <|> ") AS ?discretizes)
(GROUP_CONCAT(DISTINCT CONCAT(?lbf, " | ", ?lbfl, " | ", ?lbfd); SEPARATOR=" <|> ") AS ?linearized_by)
(GROUP_CONCAT(DISTINCT CONCAT(?lf, " | ", ?lfl, " | ", ?lfd); SEPARATOR=" <|> ") AS ?linearizes)
(GROUP_CONCAT(DISTINCT CONCAT(?stf, " | ", ?stfl, " | ", ?stfd); SEPARATOR=" <|> ") AS ?similar_to)
(GROUP_CONCAT(DISTINCT CONCAT(?pub, " | ", ?publ, " | ", ?pubd); SEPARATOR=" <|> ") AS ?publication)
                                                                               
WHERE {{ 

    VALUES ?id {{wd:{0}}}

    OPTIONAL {{
        ?id wdt:{comment} ?reference
    }}

    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{linear equation} }}, "True", "False" ) AS ?is_linear)
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{nonlinear equation} }}, "True", "False" ) AS ?is_not_linear)

    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{dynamic equation} }}, "True", "False" ) AS ?is_dynamic)
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{static equation} }}, "True", "False" ) AS ?is_static)

    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{deterministic equation} }}, "True", "False" ) AS ?is_deterministic)
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{probabilistic equation} }}, "True", "False" ) AS ?is_stochastic)

    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{dimensionless equation} }}, "True", "False" ) AS ?is_dimensionless)
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{dimensional equation} }}, "True", "False" ) AS ?is_dimensional)

    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{continuous-space equation} }}, "True", "False" ) AS ?is_space_continuous)
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{discrete-space equation} }}, "True", "False" ) AS ?is_space_discrete)

    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{continuous-time equation} }}, "True", "False" ) AS ?is_time_continuous)
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{discrete-time equation} }}, "True", "False" ) AS ?is_time_discrete)

    OPTIONAL {{   

        OPTIONAL {{
                                                          
            {{
                SELECT ?statement3 (GROUP_CONCAT(DISTINCT ?sbfq_entry; separator=" <<||>> ") AS ?sbfq)
                WHERE {{
                    ?id p:{specialized by} ?statement3.

                    OPTIONAL {{
                        ?statement3 pq:{assumes} ?qua3raw.
                        BIND(CONCAT("mardi:", STRAFTER(STR(?qua3raw), STR(wd:))) AS ?qua3)
                                                             
                        OPTIONAL {{
                            ?qua3raw rdfs:label ?sbfqlraw.
                            FILTER (lang(?sbfqlraw) = "en")
                        }}
                        BIND(COALESCE(?sbfqlraw, "No Label Provided!") AS ?sbfql)

                        OPTIONAL {{
                            ?qua3raw schema:description ?sbfqdraw.
                            FILTER (lang(?sbfqdraw) = "en")
                        }}
                        BIND(COALESCE(?sbfqdraw, "No Description Provided!") AS ?sbfqd)
                    }}

                    BIND(COALESCE(?qua3, "") AS ?qua3_final)
                    BIND(COALESCE(?sbfql, "") AS ?sbfql_final)
                    BIND(COALESCE(?sbfqd, "") AS ?sbfqd_final)
                    
                    BIND(IF((?qua3_final = "" && ?sbfql_final = "" && ?sbfqd_final = ""),"",CONCAT(?qua3_final, " | ", ?sbfql_final, " | ", ?sbfqd_final)) AS ?sbfq_entry)
                                                             
                }}
                GROUP BY ?statement3
            }}
        }}
                                                        
        ?id p:{specialized by} ?statement3.
        ?statement3 ps:{specialized by} ?sbfraw.                                    
        BIND(CONCAT("mardi:", STRAFTER(STR(?sbfraw), STR(wd:))) AS ?sbf)
                                                          
        ?sbfraw wdt:{instance of} wd:{mathematical expression}.

        OPTIONAL {{
            ?sbfraw rdfs:label ?sbflraw
            FILTER (lang(?sbflraw) = 'en')
        }}
        BIND(COALESCE(?sbflraw, "No Label Provided!") AS ?sbfl)

        OPTIONAL {{
            ?sbfraw schema:description ?sbfdraw
            FILTER (lang(?sbfdraw) = 'en')
        }}
        BIND(COALESCE(?sbfdraw, "No Description Provided!") AS ?sbfd)
                                                  
    }}

    OPTIONAL {{   
                                                    
        OPTIONAL {{
                                                          
            {{
                SELECT ?statement4 (GROUP_CONCAT(DISTINCT ?sfq_entry; separator=" <<||>> ") AS ?sfq)
                WHERE {{
                    ?sfraw wdt:{specialized by} ?id.
                    ?sfraw p:{specialized by} ?statement4.
                                                          
                    OPTIONAL {{
                        ?statement4 pq:{assumes} ?qua4raw.
                        BIND(CONCAT("mardi:", STRAFTER(STR(?qua4raw), STR(wd:))) AS ?qua4)
                                                             
                        OPTIONAL {{
                            ?qua4raw rdfs:label ?sfqlraw.
                            FILTER (lang(?sfqlraw) = "en")
                        }}
                        BIND(COALESCE(?sfqlraw, "No Label Provided!") AS ?sfql)

                        OPTIONAL {{
                            ?qua4raw schema:description ?sfqdraw.
                            FILTER (lang(?sfqdraw) = "en")
                        }}
                        BIND(COALESCE(?sfqdraw, "No Description Provided!") AS ?sfqd)                                   
                    }}

                    BIND(COALESCE(?qua4, "") AS ?qua4_final)
                    BIND(COALESCE(?sfql, "") AS ?sfql_final)
                    BIND(COALESCE(?sfqd, "") AS ?sfqd_final)
                    
                    BIND(IF((?qua4_final = "" && ?sfql_final = "" && ?sfqd_final = ""),"",CONCAT(?qua4_final, " | ", ?sfql_final, " | ", ?sfqd_final)) AS ?sfq_entry)
                                                             
                }}
                GROUP BY ?statement4
            }}
        }}
                                                        
        ?sfraw p:{specialized by} ?statement4.
        ?statement4 ps:{specialized by} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?sfraw), STR(wd:))) AS ?sf)
                                                          
        ?sfraw wdt:{instance of} wd:{mathematical expression}.

        OPTIONAL {{
            ?sfraw rdfs:label ?sflraw
            FILTER (lang(?sflraw) = 'en')
        }}
        BIND(COALESCE(?sflraw, "No Label Provided!") AS ?sfl)

        OPTIONAL {{
            ?sfraw schema:description ?sfdraw
            FILTER (lang(?sfdraw) = 'en')
        }}
        BIND(COALESCE(?sfdraw, "No Description Provided!") AS ?sfd)

    }}
                                                    
    OPTIONAL {{
        ?id wdt:{approximated by} ?abfraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?abfraw), STR(wd:))) AS ?abf)

        ?abfraw wdt:{instance of} wd:{mathematical expression}.

        OPTIONAL {{
            ?abfraw rdfs:label ?abflraw.
            FILTER (lang(?abflraw) = 'en')
        }}
        BIND(COALESCE(?abflraw, "No Label Provided!") AS ?abfl)

        OPTIONAL {{
            ?abfraw schema:description ?abfdraw
            FILTER (lang(?abfdraw) = 'en')
        }}
        BIND(COALESCE(?abfdraw, "No Description Provided!") AS ?abfd)
    }}

    OPTIONAL {{
        ?afraw wdt:{approximated by} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?afraw), STR(wd:))) AS ?af)
         
        ?afraw wdt:{instance of} wd:{mathematical expression}.
        OPTIONAL {{
            ?afraw rdfs:label ?aflraw.
            FILTER (lang(?aflraw) = 'en')
        }}
        BIND(COALESCE(?aflraw, "No Label Provided!") AS ?afl)
        
        OPTIONAL {{
            ?afraw schema:description ?afdraw
            FILTER (lang(?afdraw) = 'en')
        }}
        BIND(COALESCE(?afdraw, "No Description Provided!") AS ?afd)
    }}

    OPTIONAL {{
        ?id wdt:{nondimensionalized by} ?nbfraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?nbfraw), STR(wd:))) AS ?nbf)
        
        ?nbfraw wdt:{instance of} wd:{mathematical expression}.
        
        OPTIONAL {{
            ?nbfraw rdfs:label ?nbflraw.
            FILTER (lang(?nbflraw) = 'en')
        }}
        BIND(COALESCE(?nbflraw, "No Label Provided!") AS ?nbfl)

        OPTIONAL {{
            ?nbfraw schema:description ?nbfdraw
            FILTER (lang(?nbfdraw) = 'en')
        }}
        BIND(COALESCE(?nbfdraw, "No Description Provided!") AS ?nbfd)
    }}

    OPTIONAL {{
        ?nfraw wdt:{nondimensionalized by} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?nfraw), STR(wd:))) AS ?nf)
        
        ?nfraw wdt:{instance of} wd:{mathematical expression}.

        OPTIONAL {{
            ?nfraw rdfs:label ?nflraw.
            FILTER (lang(?nflraw) = 'en')
        }}
        BIND(COALESCE(?nflraw, "No Label Provided!") AS ?nfl)

        OPTIONAL {{
            ?nfraw schema:description ?nfdraw
            FILTER (lang(?nfdraw) = 'en')
        }}
        BIND(COALESCE(?nfdraw, "No Description Provided!") AS ?nfd)
    }}

    OPTIONAL {{
        ?id wdt:{discretized by} ?dbfraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?dbfraw), STR(wd:))) AS ?dbf)
                  
        ?dbfraw wdt:{instance of} wd:{mathematical expression}.
        
        OPTIONAL {{
            ?dbfraw rdfs:label ?dbflraw.
            FILTER (lang(?dbflraw) = 'en')
        }}
        BIND(COALESCE(?dbflraw, "No Label Provided!") AS ?dbfl)
        
        OPTIONAL {{
            ?dbfraw schema:description ?dbfdraw
            FILTER (lang(?dbfdraw) = 'en')
        }}
        BIND(COALESCE(?dbfdraw, "No Description Provided!") AS ?dbfd)
    }}

    OPTIONAL {{
        ?dfraw wdt:{discretized by} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?dfraw), STR(wd:))) AS ?df)
                   
        ?dfraw wdt:{instance of} wd:{mathematical expression}.
        
        OPTIONAL {{
            ?dfraw rdfs:label ?dflraw.
            FILTER (lang(?dflraw) = 'en')
        }}
        BIND(COALESCE(?dflraw, "No Label Provided!") AS ?dfl)

        OPTIONAL {{
            ?dfraw schema:description ?dfdraw
            FILTER (lang(?dfdraw) = 'en')
        }}
        BIND(COALESCE(?dfdraw, "No Description Provided!") AS ?dfd)
    }}


    OPTIONAL {{
        ?id wdt:{linearized by} ?lbfraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?lbfraw), STR(wd:))) AS ?lbf)
        
        ?lbfraw wdt:{instance of} wd:{mathematical expression}.
        
        OPTIONAL {{
            ?lbfraw rdfs:label ?lbflraw.
            FILTER (lang(?lbflraw) = 'en')
        }}
        BIND(COALESCE(?lbflraw, "No Label Provided!") AS ?lbfl)

        OPTIONAL {{
            ?lbfraw schema:description ?lbfdraw
            FILTER (lang(?lbfdraw) = 'en')
        }}
        BIND(COALESCE(?lbfdraw, "No Description Provided!") AS ?lbfd)
    }}

    OPTIONAL {{
        ?lfraw wdt:{linearized by} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?lfraw), STR(wd:))) AS ?lf)
        
        ?lfraw wdt:{instance of} wd:{mathematical expression}.
        
        OPTIONAL {{
            ?lfraw rdfs:label ?lflraw.
            FILTER (lang(?lflraw) = 'en')
        }}
        BIND(COALESCE(?lflraw, "No Label Provided!") AS ?lfl)
        
        OPTIONAL {{
            ?lfraw schema:description ?lfdraw
            FILTER (lang(?lfdraw) = 'en')
        }}
        BIND(COALESCE(?lfdraw, "No Description Provided!") AS ?lfd)
    }}

    OPTIONAL {{
        ?id wdt:{similar to} ?stfraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?stfraw), STR(wd:))) AS ?stf)
        
        ?stfraw wdt:{instance of} wd:{mathematical expression}.
        
        OPTIONAL {{
            ?stfraw rdfs:label ?stflraw.
            FILTER (lang(?stflraw) = 'en')
        }}
        BIND(COALESCE(?stflraw, "No Label Provided!") AS ?stfl)
        
        OPTIONAL {{
            ?stfraw schema:description ?stfdraw
            FILTER (lang(?stfdraw) = 'en')
        }}
        BIND(COALESCE(?stfdraw, "No Description Provided!") AS ?stfd)
    }}

    OPTIONAL {{
        ?id p:{described by source} ?statement_p .
        ?statement_p ps:{described by source} ?pubraw .
        ?statement_p pq:{object has role} ?role .
        VALUES ?role {{ wd:{documentation} wd:{invention} wd:{review} wd:{study} wd:{use} }}
        BIND(CONCAT("mardi:", STRAFTER(STR(?pubraw), STR(wd:))) AS ?pub)
        
        OPTIONAL {{
            ?pubraw rdfs:label ?publraw.
            FILTER (lang(?publraw) = 'en')
        }}
        BIND(COALESCE(?publraw, "No Label Provided!") AS ?publ)

        OPTIONAL {{
            ?pubraw schema:description ?pubdraw
            FILTER (lang(?pubdraw) = 'en')
        }}
        BIND(COALESCE(?pubdraw, "No Description Provided!") AS ?pubd)
    }}
}}

GROUP BY ?descriptionLong ?is_linear ?is_not_linear ?is_dynamic ?is_static ?is_deterministic ?is_stochastic ?is_dimensionless 
         ?is_dimensional ?is_space_continuous ?is_space_discrete ?is_time_continuous ?is_time_discrete ?reference