SELECT DISTINCT
?is_linear ?is_not_linear
?is_dynamic ?is_static
?is_deterministic ?is_stochastic
?is_dimensionless ?is_dimensional
?is_space_continuous ?is_space_discrete
?is_time_continuous ?is_time_discrete
(GROUP_CONCAT(DISTINCT CONCAT(?rp, " | ", ?rpl, " | ", ?rpd); SEPARATOR=" <|> ") AS ?models)
(GROUP_CONCAT(DISTINCT CONCAT(?ta, " | ", ?tal, " | ", ?tad); SEPARATOR=" <|> ") AS ?used_by)
(GROUP_CONCAT(DISTINCT CONCAT(?conf, " | ", ?confl, " | ", ?confd, " | ", ?confq); SEPARATOR=" <|> ") AS ?contains_formulation)
(GROUP_CONCAT(DISTINCT CONCAT(?sbm, " | ", ?sbml, " | ", ?sbmd, " | ", ?sbmq); SEPARATOR=" <|> ") AS ?specialized_by)
(GROUP_CONCAT(DISTINCT CONCAT(?sm, " | ", ?sml, " | ", ?smd, " | ", ?smq); SEPARATOR=" <|> ") AS ?specializes)
(GROUP_CONCAT(DISTINCT CONCAT(?abm, " | ", ?abml, " | ", ?abmd); SEPARATOR=" <|> ") AS ?approximated_by)
(GROUP_CONCAT(DISTINCT CONCAT(?am, " | ", ?aml, " | ", ?amd); SEPARATOR=" <|> ") AS ?approximates)
(GROUP_CONCAT(DISTINCT CONCAT(?conm, " | ", ?conml, " | ", ?conmd); SEPARATOR=" <|> ") AS ?contains_model)
(GROUP_CONCAT(DISTINCT CONCAT(?conim, " | ", ?coniml, " | ", ?conimd); SEPARATOR=" <|> ") AS ?contained_in_model)
(GROUP_CONCAT(DISTINCT CONCAT(?dbm, " | ", ?dbml, " | ", ?dbmd); SEPARATOR=" <|> ") AS ?discretized_by)
(GROUP_CONCAT(DISTINCT CONCAT(?dm, " | ", ?dml, " | ", ?dmd); SEPARATOR=" <|> ") AS ?discretizes)
(GROUP_CONCAT(DISTINCT CONCAT(?lbm, " | ", ?lbml, " | ", ?lbmd); SEPARATOR=" <|> ") AS ?linearized_by)
(GROUP_CONCAT(DISTINCT CONCAT(?lm, " | ", ?lml, " | ", ?lmd); SEPARATOR=" <|> ") AS ?linearizes)
(GROUP_CONCAT(DISTINCT CONCAT(?stm, " | ", ?stml, " | ", ?stmd); SEPARATOR=" <|> ") AS ?similar_to)
(GROUP_CONCAT(DISTINCT CONCAT(?pub, " | ", ?publ, " | ", ?pubd); SEPARATOR=" <|> ") AS ?publication)
                                                                 
WHERE {{
                                                   
    VALUES ?id {{wd:{0}}}
                                                   
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{linear model} }}, "True", "False" ) AS ?is_linear)
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{nonlinear model} }}, "True", "False" ) AS ?is_not_linear)
    
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{dynamic model} }}, "True", "False" ) AS ?is_dynamic)
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{static model} }}, "True", "False" ) AS ?is_static)
    
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{deterministic model} }}, "True", "False" ) AS ?is_deterministic)
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{probabilistic model} }}, "True", "False" ) AS ?is_stochastic)
    
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{dimensionless model} }}, "True", "False" ) AS ?is_dimensionless)
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{dimensional model} }}, "True", "False" ) AS ?is_dimensional)
    
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{continuous-space model} }}, "True", "False" ) AS ?is_space_continuous)
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{discrete-space model} }}, "True", "False" ) AS ?is_space_discrete)
    
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{continuous-time model} }}, "True", "False" ) AS ?is_time_continuous)
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{discrete-time model} }}, "True", "False" ) AS ?is_time_discrete)

    OPTIONAL {{
        ?rpraw wdt:{modelled by} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?rpraw), STR(wd:))) AS ?rp)
         
        ?rpraw wdt:{instance of} wd:{research problem}.
        
        OPTIONAL {{
            ?rpraw rdfs:label ?rplraw.
            FILTER (lang(?rplraw) = 'en')
        }}
        BIND(COALESCE(?rplraw, "No Label Provided!") AS ?rpl)
        
        OPTIONAL {{
            ?rpraw schema:description ?rpdraw
            FILTER (lang(?rpdraw) = 'en')
        }}
        BIND(COALESCE(?rpdraw, "No Description Provided!") AS ?rpd)
    }}

    OPTIONAL {{
        ?id wdt:{used by} ?taraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?taraw), STR(wd:))) AS ?ta)
         
        ?taraw wdt:{instance of} wd:{computational task}.
        
        OPTIONAL {{
            ?taraw rdfs:label ?talraw.
            FILTER (lang(?talraw) = 'en')
        }}
        BIND(COALESCE(?talraw, "No Label Provided!") AS ?tal)
        
        OPTIONAL {{
            ?taraw schema:description ?tadraw
            FILTER (lang(?tadraw) = 'en')
        }}
        BIND(COALESCE(?tadraw, "No Description Provided!") AS ?tad)
    }}

    OPTIONAL {{
        ?id p:{contains} ?statement_y.
        ?statement_y ps:{contains} ?confraw.
        ?confraw wdt:{instance of} wd:{mathematical expression}.
        BIND(CONCAT("mardi:", STRAFTER(STR(?confraw), STR(wd:))) AS ?conf)
         
        OPTIONAL {{
            ?confraw rdfs:label ?conflraw.
            FILTER (lang(?conflraw) = 'en')
        }}
        BIND(COALESCE(?conflraw, "No Label Provided!") AS ?confl)
        
        OPTIONAL {{
            ?confraw schema:description ?confdraw
            FILTER (lang(?confdraw) = 'en')
        }}
        BIND(COALESCE(?confdraw, "No Description Provided!") AS ?confd)
        
        OPTIONAL {{
            ?statement_y pq:{object has role} ?quaraw.
            BIND(CONCAT("mardi:", STRAFTER(STR(?quaraw), STR(wd:))) AS ?qua)
        }}
        BIND(COALESCE(?qua, "") AS ?confq)
    }}

    OPTIONAL {{   
                                                    
        OPTIONAL {{
                                                          
            {{
                SELECT ?statement2 (GROUP_CONCAT(DISTINCT ?sbmq_entry; separator=" <<||>> ") AS ?sbmq)
                WHERE {{
                    ?id p:{specialized by} ?statement2.

                    OPTIONAL {{
                        ?statement2 pq:{assumes} ?qua2raw.
                        BIND(CONCAT("mardi:", STRAFTER(STR(?qua2raw), STR(wd:))) AS ?qua2)

                        OPTIONAL {{
                            ?qua2raw rdfs:label ?sbmqlraw.
                            FILTER (lang(?sbmqlraw) = "en")
                        }}
                        BIND(COALESCE(?sbmqlraw, "No Label Provided!") AS ?sbmql)

                        OPTIONAL {{
                            ?qua2raw schema:description ?sbmqdraw.
                            FILTER (lang(?sbmqdraw) = "en")
                        }}
                        BIND(COALESCE(?sbmqdraw, "No Description Provided!") AS ?sbmqd)
                    }}

                    BIND(COALESCE(?qua2, "") AS ?qua2_final)
                    BIND(COALESCE(?sbmql, "") AS ?sbmql_final)
                    BIND(COALESCE(?sbmqd, "") AS ?sbmqd_final)

                    BIND(IF((?qua2_final = "" && ?sbmql_final = "" && ?sbmqd_final = ""),"",CONCAT(?qua2_final, " | ", ?sbmql_final, " | ", ?sbmqd_final)) AS ?sbmq_entry)
                   
                }}
                GROUP BY ?statement2
            }}
        }}
                                                        
        ?id p:{specialized by} ?statement2.
        ?statement2 ps:{specialized by} ?sbmraw.
        
        BIND(CONCAT("mardi:", STRAFTER(STR(?sbmraw), STR(wd:))) AS ?sbm)
        
        ?sbmraw wdt:{instance of} wd:{mathematical model}.
    
        OPTIONAL {{
            ?sbmraw rdfs:label ?sbmlraw
            FILTER (lang(?sbmlraw) = 'en')
        }}
        BIND(COALESCE(?sbmlraw, "No Label Provided!") AS ?sbml)
    
        OPTIONAL {{
            ?sbmraw schema:description ?sbmdraw
            FILTER (lang(?sbmdraw) = 'en')
        }}
        BIND(COALESCE(?sbmdraw, "No Description Provided!") AS ?sbmd)

    }}

    OPTIONAL {{   
                                                    
        OPTIONAL {{
                                                          
            {{
                SELECT ?statement3 (GROUP_CONCAT(DISTINCT ?smq_entry; separator=" <<||>> ") AS ?smq)
                WHERE {{
                    ?smraw wdt:{specialized by} ?id.
                    ?smraw p:{specialized by} ?statement3.
                
                    OPTIONAL {{
                        ?statement3 pq:{assumes} ?qua3raw.
                        BIND(CONCAT("mardi:", STRAFTER(STR(?qua3raw), STR(wd:))) AS ?qua3)
                   
                        OPTIONAL {{
                            ?qua3raw rdfs:label ?smqlraw.
                            FILTER (lang(?smqlraw) = "en")
                        }}
                        BIND(COALESCE(?smqlraw, "No Label Provided!") AS ?smql)
                   
                        OPTIONAL {{
                            ?qua3raw schema:description ?smqdraw.
                            FILTER (lang(?smqdraw) = "en")
                        }}
                        BIND(COALESCE(?smqdraw, "No Description Provided!") AS ?smqd)
                    }}
                
                    BIND(COALESCE(?qua3, "") AS ?qua3_final)
                    BIND(COALESCE(?smql, "") AS ?smql_final)
                    BIND(COALESCE(?smqd, "") AS ?smqd_final)
                
                    BIND(IF((?qua3_final = "" && ?smql_final = "" && ?smqd_final = ""),"",CONCAT(?qua3_final, " | ", ?smql_final, " | ", ?smqd_final)) AS ?smq_entry)
                   
                }}
                GROUP BY ?statement3
            }}
        }}
                                                        
        ?smraw p:{specialized by} ?statement3.
        ?statement3 ps:{specialized by} ?id.
        
        BIND(CONCAT("mardi:", STRAFTER(STR(?smraw), STR(wd:))) AS ?sm)
        
        ?smraw wdt:{instance of} wd:{mathematical model}.
    
        OPTIONAL {{
            ?smraw rdfs:label ?smlraw
            FILTER (lang(?smlraw) = 'en')
        }}
        BIND(COALESCE(?smlraw, "No Label Provided!") AS ?sml)
    
        OPTIONAL {{
            ?smraw schema:description ?smdraw
            FILTER (lang(?smdraw) = 'en')
        }}
        BIND(COALESCE(?smdraw, "No Description Provided!") AS ?smd)

    }}
                                                    
    OPTIONAL {{
        ?id wdt:{approximated by} ?abmraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?abmraw), STR(wd:))) AS ?abm)
         
        ?abmraw wdt:{instance of} wd:{mathematical model}.

        OPTIONAL {{
            ?abmraw rdfs:label ?abmlraw.
            FILTER (lang(?abmlraw) = 'en')
        }}
        BIND(COALESCE(?abmlraw, "No Label Provided!") AS ?abml)
        
        OPTIONAL {{
            ?abmraw schema:description ?abmdraw
            FILTER (lang(?abmdraw) = 'en')
        }}
        BIND(COALESCE(?abmdraw, "No Description Provided!") AS ?abmd)
    }}

    OPTIONAL {{
        ?amraw wdt:{approximated by} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?amraw), STR(wd:))) AS ?am)
         
        ?amraw wdt:{instance of} wd:{mathematical model}.
        
        OPTIONAL {{
            ?amraw rdfs:label ?amlraw.
            FILTER (lang(?amlraw) = 'en')
        }}
        BIND(COALESCE(?amlraw, "No Label Provided!") AS ?aml)
        
        OPTIONAL {{
            ?amraw schema:description ?amdraw
            FILTER (lang(?amdraw) = 'en')
        }}
        BIND(COALESCE(?amdraw, "No Description Provided!") AS ?amd)
    }}

    OPTIONAL {{
        ?id wdt:{contains} ?conmraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?conmraw), STR(wd:))) AS ?conm)
         
        ?conmraw wdt:{instance of} wd:{mathematical model}.
        
        OPTIONAL {{
            ?conmraw rdfs:label ?conmlraw.
            FILTER (lang(?conmlraw) = 'en')
        }}
        BIND(COALESCE(?conmlraw, "No Label Provided!") AS ?conml)
        
        OPTIONAL {{
            ?conmraw schema:description ?conmdraw
            FILTER (lang(?conmdraw) = 'en')
        }}
        BIND(COALESCE(?conmdraw, "No Description Provided!") AS ?conmd)
    }}

    OPTIONAL {{
        ?conimraw wdt:{contains} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?conimraw), STR(wd:))) AS ?conim)
         
        ?conimraw wdt:{instance of} wd:{mathematical model}.

        OPTIONAL {{
            ?conimraw rdfs:label ?conimlraw.
            FILTER (lang(?conimlraw) = 'en')
        }}
        BIND(COALESCE(?conimlraw, "No Label Provided!") AS ?coniml)
        
        OPTIONAL {{
            ?conimraw schema:description ?conimdraw
            FILTER (lang(?conimdraw) = 'en')
        }}
        BIND(COALESCE(?conimdraw, "No Description Provided!") AS ?conimd)
    }}

    OPTIONAL {{
        ?id wdt:{discretized by} ?dbmraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?dbmraw), STR(wd:))) AS ?dbm)
                   
        ?dbmraw wdt:{instance of} wd:{mathematical model}.

        OPTIONAL {{
            ?dbmraw rdfs:label ?dbmlraw.
            FILTER (lang(?dbmlraw) = 'en')
        }}
        BIND(COALESCE(?dbmlraw, "No Label Provided!") AS ?dbml)
        
        OPTIONAL {{
            ?dbmraw schema:description ?dbmdraw
            FILTER (lang(?dbmdraw) = 'en')
        }}
        BIND(COALESCE(?dbmdraw, "No Description Provided!") AS ?dbmd)
    }}

    OPTIONAL {{
        ?dmraw wdt:{discretized by} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?dmraw), STR(wd:))) AS ?dm)
         
        ?dmraw wdt:{instance of} wd:{mathematical model}.

        OPTIONAL {{
            ?dmraw rdfs:label ?dmlraw.
            FILTER (lang(?dmlraw) = 'en')
        }}
        BIND(COALESCE(?dmlraw, "No Label Provided!") AS ?dml)
        
        OPTIONAL {{
            ?dmraw schema:description ?dmdraw
            FILTER (lang(?dmdraw) = 'en')
        }}
        BIND(COALESCE(?dmdraw, "No Description Provided!") AS ?dmd)
    }}

    OPTIONAL {{
        ?id wdt:{linearized by} ?lbmraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?lbmraw), STR(wd:))) AS ?lbm)
         
        ?lbmraw wdt:{instance of} wd:{mathematical model}.
        
        OPTIONAL {{
            ?lbmraw rdfs:label ?lbmlraw.
            FILTER (lang(?lbmlraw) = 'en')
        }}
        BIND(COALESCE(?lbmlraw, "No Label Provided!") AS ?lbml)
        
        OPTIONAL {{
            ?lbmraw schema:description ?lbmdraw
            FILTER (lang(?lbmdraw) = 'en')
        }}
        BIND(COALESCE(?lbmdraw, "No Description Provided!") AS ?lbmd)
    }}

    OPTIONAL {{
        ?lmraw wdt:{linearized by} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?lmraw), STR(wd:))) AS ?lm)
         
        ?lmraw wdt:{instance of} wd:{mathematical model}.

        OPTIONAL {{
            ?lmraw rdfs:label ?lmlraw.
            FILTER (lang(?lmlraw) = 'en')
        }}
        BIND(COALESCE(?lmlraw, "No Label Provided!") AS ?lml)
        
        OPTIONAL {{
            ?lmraw schema:description ?lmdraw
            FILTER (lang(?lmdraw) = 'en')
        }}
        BIND(COALESCE(?lmdraw, "No Description Provided!") AS ?lmd)
    }}

    OPTIONAL {{
         ?id wdt:{similar to} ?stmraw.
         BIND(CONCAT("mardi:", STRAFTER(STR(?stmraw), STR(wd:))) AS ?stm)
         
         ?stmraw wdt:{instance of} wd:{mathematical model}.

         OPTIONAL {{
            ?stmraw rdfs:label ?stmlraw.
            FILTER (lang(?stmlraw) = 'en')
        }}
        BIND(COALESCE(?stmlraw, "No Label Provided!") AS ?stml)
        
        OPTIONAL {{
            ?stmraw schema:description ?stmdraw
            FILTER (lang(?stmdraw) = 'en')
        }}
        BIND(COALESCE(?stmdraw, "No Description Provided!") AS ?stmd)
    }}

    OPTIONAL {{
        ?id p:{described by source} ?statement_p .
        ?statement_p ps:{described by source} ?pubraw .
        ?statement_p pq:{object has role} ?role .
        VALUES ?role {{ wd:{documentation} wd:{invention} wd:{review} wd:{study} wd:{use} }}
        BIND(CONCAT("mardi:", STRAFTER(STR(?pubraw), STR(wd:))) AS ?pub)
         
        OPTIONAL {{
            ?pubraw rdfs:label ?publraw.
            FILTER (lang(?publraw) = 'en')
        }}
        BIND(COALESCE(?publraw, "No Label Provided!") AS ?publ)
        
        OPTIONAL {{
            ?pubraw schema:description ?pubdraw
            FILTER (lang(?pubdraw) = 'en')
        }}
        BIND(COALESCE(?pubdraw, "No Description Provided!") AS ?pubd)
    }}
          
}}
GROUP BY ?is_linear ?is_not_linear ?is_dynamic ?is_static ?is_deterministic ?is_stochastic ?is_dimensionless 
         ?is_dimensional ?is_space_continuous ?is_space_discrete ?is_time_continuous ?is_time_discrete