SELECT DISTINCT
?is_dynamic ?is_static
?is_deterministic ?is_stochastic
?is_dimensionless ?is_dimensional
?is_space_continuous ?is_space_discrete
?is_time_continuous ?is_time_discrete
?is_chemical_constant ?is_mathematical_constant ?is_physical_constant
?class ?qudt_quantitykind_id ?qudt_constant_id
(GROUP_CONCAT(DISTINCT ?alias; SEPARATOR=" <|> ") AS ?aliases)
(GROUP_CONCAT(DISTINCT ?descriptionLong; SEPARATOR=" <|> ") AS ?description_long)
(GROUP_CONCAT(DISTINCT(?formula); SEPARATOR=" <|> ") AS ?formulas)
(GROUP_CONCAT(DISTINCT CONCAT(?symbol, " | ", ?cq, " | ", ?cql, " | ", ?cqd); SEPARATOR=" <|> ") AS ?contains_quantity)
(GROUP_CONCAT(DISTINCT CONCAT(?sbq, " | ", ?sbql, " | ", ?sbqd, " | ", ?sbqc); SEPARATOR=" <|> ") AS ?specialized_by)
(GROUP_CONCAT(DISTINCT CONCAT(?sq, " | ", ?sql, " | ", ?sqd, " | ", ?sqc); SEPARATOR=" <|> ") AS ?specializes)
(GROUP_CONCAT(DISTINCT CONCAT(?abq, " | ", ?abql, " | ", ?abqd, " | ", ?abqc); SEPARATOR=" <|> ") AS ?approximated_by)
(GROUP_CONCAT(DISTINCT CONCAT(?aq, " | ", ?aql, " | ", ?aqd, " | ", ?aqc); SEPARATOR=" <|> ") AS ?approximates)
(GROUP_CONCAT(DISTINCT CONCAT(?dbq, " | ", ?dbql, " | ", ?dbqd, " | ", ?dbqc); SEPARATOR=" <|> ") AS ?discretized_by)
(GROUP_CONCAT(DISTINCT CONCAT(?dq, " | ", ?dql, " | ", ?dqd, " | ", ?dqc); SEPARATOR=" <|> ") AS ?discretizes)
(GROUP_CONCAT(DISTINCT CONCAT(?lbq, " | ", ?lbql, " | ", ?lbqd, " | ", ?lbqc); SEPARATOR=" <|> ") AS ?linearized_by)
(GROUP_CONCAT(DISTINCT CONCAT(?lq, " | ", ?lql, " | ", ?lqd, " | ", ?lqc); SEPARATOR=" <|> ") AS ?linearizes)
(GROUP_CONCAT(DISTINCT CONCAT(?nbq, " | ", ?nbql, " | ", ?nbqd, " | ", ?nbqc); SEPARATOR=" <|> ") AS ?nondimensionalized_by)
(GROUP_CONCAT(DISTINCT CONCAT(?nq, " | ", ?nql, " | ", ?nqd, " | ", ?nqc); SEPARATOR=" <|> ") AS ?nondimensionalizes)
(GROUP_CONCAT(DISTINCT CONCAT(?stq, " | ", ?stql, " | ", ?stqd, " | ", ?stqc); SEPARATOR=" <|> ") AS ?similar_to)
(GROUP_CONCAT(DISTINCT CONCAT(?pub, " | ", ?publ, " | ", ?pubd); SEPARATOR=" <|> ") AS ?publication)
                                                                      
WHERE {{
                                                
    VALUES ?id {{wd:{0}}}

    OPTIONAL {{
        ?id skos:altLabel ?alias .
        FILTER (LANG(?alias) = "en")
    }}

    OPTIONAL {{
        ?id wdt:{description} ?descriptionLong
    }}

    BIND(EXISTS {{ ?id wdt:{instance of} wd:{dynamic quantity} }} AS ?dynamicQuantity)
    BIND(EXISTS {{ ?id wdt:{instance of} wd:{dynamic quantity kind} }} AS ?dynamicQuantityKind)
    BIND(IF(?dynamicQuantity || ?dynamicQuantityKind, "True", "False") AS ?dynamic)
    BIND(COALESCE(?dynamic, "False") AS ?is_dynamic)

    BIND(EXISTS {{ ?id wdt:{instance of} wd:{static quantity} }} AS ?staticQuantity)
    BIND(EXISTS {{ ?id wdt:{instance of} wd:{static quantity kind} }} AS ?staticQuantityKind)
    BIND(IF(?staticQuantity || ?staticQuantityKind, "True", "False") AS ?static)
    BIND(COALESCE(?static, "False") AS ?is_static)

    BIND(EXISTS {{ ?id wdt:{instance of} wd:{deterministic quantity} }} AS ?deterministicQuantity)
    BIND(EXISTS {{ ?id wdt:{instance of} wd:{deterministic quantity kind} }} AS ?deterministicQuantityKind)
    BIND(IF(?deterministicQuantity || ?deterministicQuantityKind, "True", "False") AS ?deterministic)
    BIND(COALESCE(?deterministic, "False") AS ?is_deterministic)

    BIND(EXISTS {{ ?id wdt:{instance of} wd:{probabilistic quantity} }} AS ?stochasticQuantity)
    BIND(EXISTS {{ ?id wdt:{instance of} wd:{probabilistic quantity kind} }} AS ?stochasticQuantityKind)
    BIND(IF(?stochasticQuantity || ?stochasticQuantityKind, "True", "False") AS ?stochastic)
    BIND(COALESCE(?stochastic, "False") AS ?is_stochastic)

    BIND(EXISTS {{ ?id wdt:{instance of} wd:{dimensionless quantity} }} AS ?dimensionlessQuantity)
    BIND(EXISTS {{ ?id wdt:{instance of} wd:{dimensionless quantity kind} }} AS ?dimensionlessQuantityKind)
    BIND(IF(?dimensionlessQuantity || ?dimensionlessQuantityKind, "True", "False") AS ?dimensionless)
    BIND(COALESCE(?dimensionless, "False") AS ?is_dimensionless)

    BIND(EXISTS {{ ?id wdt:{instance of} wd:{dimensional quantity} }} AS ?dimensionalQuantity)
    BIND(EXISTS {{ ?id wdt:{instance of} wd:{dimensional quantity kind} }} AS ?dimensionalQuantityKind)
    BIND(IF(?dimensionalQuantity || ?dimensionalQuantityKind, "True", "False") AS ?dimensional)
    BIND(COALESCE(?dimensional, "False") AS ?is_dimensional)

    BIND(EXISTS {{ ?id wdt:{instance of} wd:{continuous-space quantity} }} AS ?spaceContinuousQuantity)
    BIND(EXISTS {{ ?id wdt:{instance of} wd:{continuous-space quantity kind} }} AS ?spaceContinuousQuantityKind)
    BIND(IF(?spaceContinuousQuantity || ?spaceContinuousQuantityKind, "True", "False") AS ?spaceContinuous)
    BIND(COALESCE(?spaceContinuous, "False") AS ?is_space_continuous)

    BIND(EXISTS {{ ?id wdt:{instance of} wd:{discrete-space quantity} }} AS ?spaceDiscreteQuantity)
    BIND(EXISTS {{ ?id wdt:{instance of} wd:{discrete-space quantity kind} }} AS ?spaceDiscreteQuantityKind)
    BIND(IF(?spaceDiscreteQuantity || ?spaceDiscreteQuantityKind, "True", "False") AS ?spaceDiscrete)
    BIND(COALESCE(?spaceDiscrete, "False") AS ?is_space_discrete)

    BIND(EXISTS {{ ?id wdt:{instance of} wd:{continuous-time quantity} }} AS ?timeContinuousQuantity)
    BIND(EXISTS {{ ?id wdt:{instance of} wd:{continuous-time quantity kind} }} AS ?timeContinuousQuantityKind)
    BIND(IF(?timeContinuousQuantity || ?timeContinuousQuantityKind, "True", "False") AS ?timeContinuous)
    BIND(COALESCE(?timeContinuous, "False") AS ?is_time_continuous)

    BIND(EXISTS {{ ?id wdt:{instance of} wd:{discrete-time quantity} }} AS ?timeDiscreteQuantity)
    BIND(EXISTS {{ ?id wdt:{instance of} wd:{discrete-time quantity kind} }} AS ?timeDiscreteQuantityKind)
    BIND(IF(?timeDiscreteQuantity || ?timeDiscreteQuantityKind, "True", "False") AS ?timeDiscrete)
    BIND(COALESCE(?timeDiscrete, "False") AS ?is_time_discrete)
                                                    
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{chemical constant} }}, "True", "False" ) AS ?is_chemical_constant)
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{mathematical constant} }}, "True", "False" ) AS ?is_mathematical_constant)
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{physical constant} }}, "True", "False" ) AS ?is_physical_constant)

    {{
        ?id wdt:{instance of} wd:{quantity}.
        BIND("Quantity" AS ?class)
    }}
    UNION
    {{
        ?id wdt:{instance of} wd:{kind of quantity}.
        BIND("QuantityKind" AS ?class)
    }}
    
    OPTIONAL {{
        ?id wdt:{QUDT quantity kind ID} ?qudt_quantitykind_id
    }}

    OPTIONAL {{
        ?id wdt:{QUDT constant ID} ?qudt_constant_id
    }}

    OPTIONAL {{
        ?id wdt:{defining formula} ?formula.
    }}

    OPTIONAL {{
        ?id p:{in defining formula} ?statement.
        ?statement ps:{in defining formula} ?symbol.

        OPTIONAL {{
            ?statement pq:{symbol represents} ?cqraw.
                                                                           
            BIND(CONCAT("mardi:", STRAFTER(STR(?cqraw), STR(wd:))) AS ?cq)
                                                                           
            OPTIONAL {{
                ?cqraw rdfs:label ?cqlraw.
                FILTER (lang(?cqlraw) = 'en')
            }}
            BIND(COALESCE(?cqlraw, "No Label Provided!") AS ?cql)

            OPTIONAL {{
               ?cqraw schema:description ?cqdraw
               FILTER (lang(?cqdraw) = 'en')
            }}
            BIND(COALESCE(?cqdraw, "No Description Provided!") AS ?cqd)
        }}
    }}

    OPTIONAL {{
        ?id wdt:{specialized by} ?sbqraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?sbqraw), STR(wd:))) AS ?sbq)
                                                               
        {{
            ?sbqraw wdt:{instance of} wd:{quantity}.
            BIND("Quantity" AS ?sbqc)
        }}
        UNION
        {{
            ?sbqraw wdt:{instance of} wd:{kind of quantity}.
            BIND("QuantityKind" AS ?sbqc)
        }}

        OPTIONAL {{
            ?sbqraw rdfs:label ?sbqlraw.
            FILTER (lang(?sbqlraw) = 'en')
        }}
        BIND(COALESCE(?sbqlraw, "No Label Provided!") AS ?sbql)

        OPTIONAL {{
            ?sbqraw schema:description ?sbqdraw
            FILTER (lang(?sbqdraw) = 'en')
        }}
        BIND(COALESCE(?sbqdraw, "No Description Provided!") AS ?sbqd)
    }}

    OPTIONAL {{
        ?sqraw wdt:{specialized by} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?sqraw), STR(wd:))) AS ?sq)
                                                               
        {{
            ?sqraw wdt:{instance of} wd:{quantity}.
            BIND("Quantity" AS ?sqc)
        }}
        UNION
        {{
            ?sqraw wdt:{instance of} wd:{kind of quantity}.
            BIND("QuantityKind" AS ?sqc)
        }}

        OPTIONAL {{
            ?sqraw rdfs:label ?sqlraw.
            FILTER (lang(?sqlraw) = 'en')
        }}
        BIND(COALESCE(?sqlraw, "No Label Provided!") AS ?sql)

        OPTIONAL {{
            ?sqraw schema:description ?sqdraw
            FILTER (lang(?sqdraw) = 'en')
        }}
        BIND(COALESCE(?sqdraw, "No Description Provided!") AS ?sqd)
    }}

    OPTIONAL {{
        ?id wdt:{approximated by} ?abqraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?abqraw), STR(wd:))) AS ?abq)

        {{
            ?abqraw wdt:{instance of} wd:{quantity}.
            BIND("Quantity" AS ?abqc)
        }}
        UNION
        {{
            ?abqraw wdt:{instance of} wd:{kind of quantity}.
            BIND("QuantityKind" AS ?abqc)
        }}

        OPTIONAL {{
            ?abqraw rdfs:label ?abqlraw.
            FILTER (lang(?abqlraw) = 'en')
        }}
        BIND(COALESCE(?abqlraw, "No Label Provided!") AS ?abql)

        OPTIONAL {{
            ?abqraw schema:description ?abqdraw
            FILTER (lang(?abqdraw) = 'en')
        }}
        BIND(COALESCE(?abqdraw, "No Description Provided!") AS ?abqd)
    }}

    OPTIONAL {{
        ?dqraw wdt:{discretized by} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?dqraw), STR(wd:))) AS ?dq)
                                                               
        {{
            ?dqraw wdt:{instance of} wd:{quantity}.
            BIND("Quantity" AS ?dqc)
        }}
        UNION
        {{
            ?dqraw wdt:{instance of} wd:{kind of quantity}.
            BIND("QuantityKind" AS ?dqc)
        }}

        OPTIONAL {{
            ?dqraw rdfs:label ?dqlraw.
            FILTER (lang(?dqlraw) = 'en')
        }}
        BIND(COALESCE(?dqlraw, "No Label Provided!") AS ?dql)

        OPTIONAL {{
            ?dqraw schema:description ?dqdraw
            FILTER (lang(?dqdraw) = 'en')
        }}
        BIND(COALESCE(?dqdraw, "No Description Provided!") AS ?dqd)
    }}

    OPTIONAL {{
        ?id wdt:{discretized by} ?dbqraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?dbqraw), STR(wd:))) AS ?dbq)
                                                               
        {{
            ?dbqraw wdt:{instance of} wd:{quantity}.
            BIND("Quantity" AS ?dbqc)
        }}
        UNION
        {{
            ?dbqraw wdt:{instance of} wd:{kind of quantity}.
            BIND("QuantityKind" AS ?dbqc)
        }}

        OPTIONAL {{
            ?dbqraw rdfs:label ?dbqlraw.
            FILTER (lang(?dbqlraw) = 'en')
        }}
        BIND(COALESCE(?dbqlraw, "No Label Provided!") AS ?dbql)

        OPTIONAL {{
            ?dbqraw schema:description ?dbqdraw
            FILTER (lang(?dbqdraw) = 'en')
        }}
        BIND(COALESCE(?dbqdraw, "No Description Provided!") AS ?dbqd)
    }}

    OPTIONAL {{
        ?aqraw wdt:{approximated by} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?aqraw), STR(wd:))) AS ?aq)
                                                               
        {{
            ?aqraw wdt:{instance of} wd:{quantity}.
            BIND("Quantity" AS ?aqc)
        }}
        UNION
        {{
            ?aqraw wdt:{instance of} wd:{kind of quantity}.
            BIND("QuantityKind" AS ?aqc)
        }}

        OPTIONAL {{
            ?aqraw rdfs:label ?aqlraw.
            FILTER (lang(?aqlraw) = 'en')
        }}
        BIND(COALESCE(?aqlraw, "No Label Provided!") AS ?aql)

        OPTIONAL {{
            ?aqraw schema:description ?aqdraw
            FILTER (lang(?aqdraw) = 'en')
        }}
        BIND(COALESCE(?aqdraw, "No Description Provided!") AS ?aqd)
    }}

    OPTIONAL {{
        ?id wdt:{linearized by} ?lbqraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?lbqraw), STR(wd:))) AS ?lbq)
                                                               
        {{
            ?lbqraw wdt:{instance of} wd:{quantity}.
            BIND("Quantity" AS ?lbqc)
        }}
        UNION
        {{
            ?lbqraw wdt:{instance of} wd:{kind of quantity}.
            BIND("QuantityKind" AS ?lbqc)
        }}

        OPTIONAL {{
            ?lbqraw rdfs:label ?lbqlraw.
            FILTER (lang(?lbqlraw) = 'en')
        }}
        BIND(COALESCE(?lbqlraw, "No Label Provided!") AS ?lbql)

        OPTIONAL {{
            ?lbqraw schema:description ?lbqdraw
            FILTER (lang(?lbqdraw) = 'en')
        }}
        BIND(COALESCE(?lbqdraw, "No Description Provided!") AS ?lbqd)
    }}

    OPTIONAL {{
        ?lqraw wdt:{linearized by} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?lqraw), STR(wd:))) AS ?lq)
                                                               
        {{
            ?lqraw wdt:{instance of} wd:{quantity}.
            BIND("Quantity" AS ?lqc)
        }}
        UNION
        {{
            ?lqraw wdt:{instance of} wd:{kind of quantity}.
            BIND("QuantityKind" AS ?lqc)
        }}

        OPTIONAL {{
            ?lqraw rdfs:label ?lqlraw.
            FILTER (lang(?lqlraw) = 'en')
        }}
        BIND(COALESCE(?lqlraw, "No Label Provided!") AS ?lql)

        OPTIONAL {{
            ?lqraw schema:description ?lqdraw
            FILTER (lang(?lqdraw) = 'en')
        }}
        BIND(COALESCE(?lqdraw, "No Description Provided!") AS ?lqd)
    }}

    OPTIONAL {{
        ?id wdt:{nondimensionalized by} ?nbqraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?nbqraw), STR(wd:))) AS ?nbq)
                                                               
        {{
            ?nbqraw wdt:{instance of} wd:{quantity}.
            BIND("Quantity" AS ?nbqc)
        }}
        UNION
        {{
            ?nbqraw wdt:{instance of} wd:{kind of quantity}.
            BIND("QuantityKind" AS ?nbqc)
        }}

        OPTIONAL {{
            ?nbqraw rdfs:label ?nbqlraw.
            FILTER (lang(?nbqlraw) = 'en')
        }}
        BIND(COALESCE(?nbqlraw, "No Label Provided!") AS ?nbql)

        OPTIONAL {{
            ?nbqraw schema:description ?nbqdraw
            FILTER (lang(?nbqdraw) = 'en')
        }}
        BIND(COALESCE(?nbqdraw, "No Description Provided!") AS ?nbqd)
    }}

    OPTIONAL {{
        ?nqraw wdt:{nondimensionalized by} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?nqraw), STR(wd:))) AS ?nq)
                                                               
        {{
            ?nqraw wdt:{instance of} wd:{quantity}.
            BIND("Quantity" AS ?nqc)
        }}
        UNION
        {{
            ?nqraw wdt:{instance of} wd:{kind of quantity}.
            BIND("QuantityKind" AS ?nqc)
        }}

        OPTIONAL {{
            ?nqraw rdfs:label ?nqlraw.
            FILTER (lang(?nqlraw) = 'en')
        }}
        BIND(COALESCE(?nqlraw, "No Label Provided!") AS ?nql)

        OPTIONAL {{
            ?nqraw schema:description ?nqdraw
            FILTER (lang(?nqdraw) = 'en')
        }}
        BIND(COALESCE(?nqdraw, "No Description Provided!") AS ?nqd)
    }}

    OPTIONAL {{
        ?id wdt:{similar to} ?stqraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?stqraw), STR(wd:))) AS ?stq)
                                                               
        {{
            ?stqraw wdt:{instance of} wd:{quantity}.
            BIND("Quantity" AS ?stqc)
        }}
        UNION
        {{
            ?stqraw wdt:{instance of} wd:{kind of quantity}.
            BIND("QuantityKind" AS ?stqc)
        }}

        OPTIONAL {{
            ?stqraw rdfs:label ?stqlraw.
            FILTER (lang(?stqlraw) = 'en')
        }}
        BIND(COALESCE(?stqlraw, "No Label Provided!") AS ?stql)

        OPTIONAL {{
            ?stqraw schema:description ?stqdraw
            FILTER (lang(?stqdraw) = 'en')
        }}
        BIND(COALESCE(?stqdraw, "No Description Provided!") AS ?stqd)
    }}

    OPTIONAL {{
        ?id p:{described by source} ?statement_p .
        ?statement_p ps:{described by source} ?pubraw .
        ?statement_p pq:{object has role} ?role .
        VALUES ?role {{ wd:{documentation} wd:{invention} wd:{review} wd:{study} wd:{use} }}
        BIND(CONCAT("mardi:", STRAFTER(STR(?pubraw), STR(wd:))) AS ?pub)
                                                               
        OPTIONAL {{
            ?pubraw rdfs:label ?publraw.
            FILTER (lang(?publraw) = 'en')
        }}
        BIND(COALESCE(?publraw, "No Label Provided!") AS ?publ)

        OPTIONAL {{
            ?pubraw schema:description ?pubdraw
            FILTER (lang(?pubdraw) = 'en')
        }}
        BIND(COALESCE(?pubdraw, "No Description Provided!") AS ?pubd)
    }}
}}

GROUP BY ?is_dynamic ?is_static ?is_deterministic ?is_stochastic ?is_dimensionless 
         ?is_dimensional ?is_space_continuous ?is_space_discrete ?is_time_continuous ?is_time_discrete
         ?is_chemical_constant ?is_mathematical_constant ?is_physical_constant ?class 
         ?qudt_quantitykind_id ?qudt_constant_id