SELECT DISTINCT
?is_linear ?is_not_linear
?is_space_continuous ?is_space_discrete
?is_time_continuous ?is_time_discrete
(GROUP_CONCAT(DISTINCT ?alias; SEPARATOR=" <|> ") AS ?aliases)
(GROUP_CONCAT(DISTINCT ?descriptionLong; SEPARATOR=" <|> ") AS ?description_long)
(GROUP_CONCAT(DISTINCT CONCAT(?ass, " | ", ?assl, " | ", ?assd); SEPARATOR=" <|> ") AS ?assumes)
(GROUP_CONCAT(DISTINCT CONCAT(?conf, " | ", ?confl, " | ", ?confd, " | ", ?confq); SEPARATOR=" <|> ") AS ?contains_formulation)
(GROUP_CONCAT(DISTINCT CONCAT(?quan, " | ", ?quanl, " | ", ?quand, " | ", ?quanq); SEPARATOR=" <|> ") AS ?contains_quantity)
(GROUP_CONCAT(DISTINCT CONCAT(?sbt, " | ", ?sbtl, " | ", ?sbtd, " | ", ?sbtq); SEPARATOR=" <|> ") AS ?specialized_by)
(GROUP_CONCAT(DISTINCT CONCAT(?st, " | ", ?stl, " | ", ?std, " | ", ?stq); SEPARATOR=" <|> ") AS ?specializes)
(GROUP_CONCAT(DISTINCT CONCAT(?abt, " | ", ?abtl, " | ", ?abtd); SEPARATOR=" <|> ") AS ?approximated_by)
(GROUP_CONCAT(DISTINCT CONCAT(?at, " | ", ?atl, " | ", ?atd); SEPARATOR=" <|> ") AS ?approximates)
(GROUP_CONCAT(DISTINCT CONCAT(?cont, " | ", ?contl, " | ", ?contd, " | ", " >|< ", ?corder); SEPARATOR=" <|> ") AS ?contains_task)
(GROUP_CONCAT(DISTINCT CONCAT(?conit, " | ", ?conitl, " | ", ?conitd, " | ", " >|< ", ?ciorder); SEPARATOR=" <|> ") AS ?contained_in_task)
(GROUP_CONCAT(DISTINCT CONCAT(?dbt, " | ", ?dbtl, " | ", ?dbtd); SEPARATOR=" <|> ") AS ?discretized_by)
(GROUP_CONCAT(DISTINCT CONCAT(?dt, " | ", ?dtl, " | ", ?dtd); SEPARATOR=" <|> ") AS ?discretizes)
(GROUP_CONCAT(DISTINCT CONCAT(?lbt, " | ", ?lbtl, " | ", ?lbtd); SEPARATOR=" <|> ") AS ?linearized_by)
(GROUP_CONCAT(DISTINCT CONCAT(?lt, " | ", ?ltl, " | ", ?ltd); SEPARATOR=" <|> ") AS ?linearizes)
(GROUP_CONCAT(DISTINCT CONCAT(?stt, " | ", ?sttl, " | ", ?sttd); SEPARATOR=" <|> ") AS ?similar_to)
(GROUP_CONCAT(DISTINCT CONCAT(?pub, " | ", ?publ, " | ", ?pubd); SEPARATOR=" <|> ") AS ?publication)
                        
WHERE {{

    VALUES ?id {{wd:{0}}}

    OPTIONAL {{
        ?id skos:altLabel ?alias .
        FILTER (LANG(?alias) = "en")
    }}

    OPTIONAL {{
        ?id wdt:{description} ?descriptionLong
    }}

    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{linear task} }}, "True", "False" ) AS ?is_linear)
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{nonlinear task} }}, "True", "False" ) AS ?is_not_linear)

    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{continuous-space task} }}, "True", "False" ) AS ?is_space_continuous)
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{discrete-space task} }}, "True", "False" ) AS ?is_space_discrete)

    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{continuous-time task} }}, "True", "False" ) AS ?is_time_continuous)
    BIND(IF(EXISTS {{ ?id wdt:{instance of} wd:{discrete-time task} }}, "True", "False" ) AS ?is_time_discrete)

    OPTIONAL {{
        ?id wdt:{assumes} ?assraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?assraw), STR(wd:))) AS ?ass)
               
        ?assraw wdt:{instance of} wd:{mathematical expression}.

        OPTIONAL {{
            ?assraw rdfs:label ?asslraw.
            FILTER (lang(?asslraw) = 'en')
        }}
        BIND(COALESCE(?asslraw, "No Label Provided!") AS ?assl)

        OPTIONAL {{
            ?assraw schema:description ?assdraw
            FILTER (lang(?assdraw) = 'en')
        }}
        BIND(COALESCE(?assdraw, "No Description Provided!") AS ?assd)
    }}

    OPTIONAL {{
        ?id p:{contains} ?statement.
        ?statement ps:{contains} ?confraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?confraw), STR(wd:))) AS ?conf)

        ?confraw wdt:{instance of} wd:{mathematical expression}.
        
                   
        OPTIONAL {{
            ?confraw rdfs:label ?conflraw.
            FILTER (lang(?conflraw) = 'en')
        }}
        BIND(COALESCE(?conflraw, "No Label Provided!") AS ?confl)
                  
        OPTIONAL {{
            ?confraw schema:description ?confdraw
            FILTER (lang(?confdraw) = 'en')
        }}
        BIND(COALESCE(?confdraw, "No Description Provided!") AS ?confd)

        OPTIONAL {{
            ?statement pq:{object has role} ?quaraw.
            BIND(CONCAT("mardi:", STRAFTER(STR(?quaraw), STR(wd:))) AS ?qua)
        }}
        BIND(COALESCE(?qua, "") AS ?confq)
    }}

    OPTIONAL {{
        ?id p:{contains} ?statement2.
        ?statement2 ps:{contains} ?quanraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?quanraw), STR(wd:))) AS ?quan)

        {{
            ?quanraw wdt:{instance of} wd:{quantity}.
        }}
           UNION
        {{
            ?quanraw wdt:{instance of} wd:{kind of quantity}.
        }}

        OPTIONAL {{
            ?quanraw rdfs:label ?quanlraw.
            FILTER (lang(?quanlraw) = 'en')
        }}
        BIND(COALESCE(?quanlraw, "No Label Provided!") AS ?quanl)
        
        OPTIONAL {{
            ?quanraw schema:description ?quandraw
            FILTER (lang(?quandraw) = 'en')
        }}
        BIND(COALESCE(?quandraw, "No Description Provided!") AS ?quand)

        OPTIONAL {{
            ?statement2 pq:{object has role} ?qua2raw.
            BIND(CONCAT("mardi:", STRAFTER(STR(?qua2raw), STR(wd:))) AS ?qua2)
        }}
        BIND(COALESCE(?qua2, "") AS ?quanq)
    }}

    OPTIONAL {{   
                                                    
        OPTIONAL {{
                                                          
            {{
                SELECT ?statement3 (GROUP_CONCAT(DISTINCT ?sbtq_entry; separator=" <<||>> ") AS ?sbtq)
                WHERE {{
                    ?id p:{specialized by} ?statement3.

                    OPTIONAL {{
                    
                       ?statement3 pq:{assumes} ?qua3raw.
                       BIND(CONCAT("mardi:", STRAFTER(STR(?qua3raw), STR(wd:))) AS ?qua3)

                       OPTIONAL {{
                         ?qua3raw rdfs:label ?sbtqlraw.
                         FILTER (lang(?sbtqlraw) = "en")
                       }}
                       BIND(COALESCE(?sbtqlraw, "No Label Provided!") AS ?sbtql)

                       OPTIONAL {{
                         ?qua3raw schema:description ?sbtqdraw.
                         FILTER (lang(?sbtqdraw) = "en")
                       }}
                       BIND(COALESCE(?sbtqdraw, "No Description Provided!") AS ?sbtqd)

                    }}

                    BIND(COALESCE(?qua3, "") AS ?qua3_final)
                    BIND(COALESCE(?sbtql, "") AS ?sbtql_final)
                    BIND(COALESCE(?sbtqd, "") AS ?sbtqd_final)

                    BIND(IF((?qua3_final = "" && ?sbtql_final = "" && ?sbtqd_final = ""),"",CONCAT(?qua3_final, " | ", ?sbtql_final, " | ", ?sbtqd_final)) AS ?sbtq_entry)
                                                                 
                }}
                GROUP BY ?statement3
            }}
        }}
                                                        
        ?id p:{specialized by} ?statement3.
        ?statement3 ps:{specialized by} ?sbtraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?sbtraw), STR(wd:))) AS ?sbt)
        
        ?sbtraw wdt:{instance of} wd:{computational task}.

        OPTIONAL {{
            ?sbtraw rdfs:label ?sbtlraw
            FILTER (lang(?sbtlraw) = 'en')
        }}
        BIND(COALESCE(?sbtlraw, "No Label Provided!") AS ?sbtl)
    
        OPTIONAL {{
            ?sbtraw schema:description ?sbtdraw
            FILTER (lang(?sbtdraw) = 'en')
        }}
        BIND(COALESCE(?sbtdraw, "No Description Provided!") AS ?sbtd)
                                                  
    }}

    OPTIONAL {{   
                                                    
        OPTIONAL {{
                                                          
            {{
                SELECT ?statement4 (GROUP_CONCAT(DISTINCT ?stq_entry; separator=" <<||>> ") AS ?stq)
                WHERE {{
                                                     
                    ?straw wdt:{specialized by} ?id.
                    ?straw p:{specialized by} ?statement4.
                                                              
                    OPTIONAL {{                       
                        ?statement4 pq:{assumes} ?qua4raw.
                        BIND(CONCAT("mardi:", STRAFTER(STR(?qua4raw), STR(wd:))) AS ?qua4)
                        
                        OPTIONAL {{
                            ?qua4raw rdfs:label ?stqlraw.
                            FILTER (lang(?stqlraw) = "en")
                        }}
                        BIND(COALESCE(?stqlraw, "No Label Provided!") AS ?stql)

                        OPTIONAL {{
                            ?qua4raw schema:description ?stqdraw.
                            FILTER (lang(?stqdraw) = "en")
                        }}
                        BIND(COALESCE(?stqdraw, "No Description Provided!") AS ?stqd)                   
                    }}

                    BIND(COALESCE(?qua4, "") AS ?qua4_final)
                    BIND(COALESCE(?stql, "") AS ?stql_final)
                    BIND(COALESCE(?stqd, "") AS ?stqd_final)
                    
                    BIND(IF((?qua4_final = "" && ?stql_final = "" && ?stqd_final = ""),"",CONCAT(?qua4_final, " | ", ?stql_final, " | ", ?stqd_final)) AS ?stq_entry)
                                                                 
                }}
                GROUP BY ?statement4
            }}
        }}
                                                        
        ?straw p:{specialized by} ?statement4.
        ?statement4 ps:{specialized by} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?straw), STR(wd:))) AS ?st)

        ?straw wdt:{instance of} wd:{computational task}.

        OPTIONAL {{
            ?straw rdfs:label ?stlraw
            FILTER (lang(?stlraw) = 'en')
        }}
        BIND(COALESCE(?stlraw, "No Label Provided!") AS ?stl)

        OPTIONAL {{
            ?straw schema:description ?stdraw
            FILTER (lang(?stdraw) = 'en')
        }}
        BIND(COALESCE(?stdraw, "No Description Provided!") AS ?std)
                                                  
    }}
                                                    
    OPTIONAL {{
        ?id wdt:{approximated by} ?abtraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?abtraw), STR(wd:))) AS ?abt)
         
        ?abtraw wdt:{instance of} wd:{computational task}.

        OPTIONAL {{
            ?abtraw rdfs:label ?abtlraw.
            FILTER (lang(?abtlraw) = 'en')
        }}
        BIND(COALESCE(?abtlraw, "No Label Provided!") AS ?abtl)

        OPTIONAL {{
            ?abtraw schema:description ?abtdraw
            FILTER (lang(?abtdraw) = 'en')
        }}
        BIND(COALESCE(?abtdraw, "No Description Provided!") AS ?abtd)
    }}

    OPTIONAL {{
        ?atraw wdt:{approximated by} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?atraw), STR(wd:))) AS ?at)
         
        ?atraw wdt:{instance of} wd:{computational task}.
        OPTIONAL {{
            ?atraw rdfs:label ?atlraw.
            FILTER (lang(?atlraw) = 'en')
        }}
        BIND(COALESCE(?atlraw, "No Label Provided!") AS ?atl)

        OPTIONAL {{
            ?atraw schema:description ?atdraw
            FILTER (lang(?atdraw) = 'en')
        }}
        BIND(COALESCE(?atdraw, "No Description Provided!") AS ?atd)
    }}

    OPTIONAL {{
        ?id p:{contains} ?statement5.
        ?statement5 ps:{contains} ?contraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?contraw), STR(wd:))) AS ?cont)
                   
        ?contraw wdt:{instance of} wd:{computational task}.

        OPTIONAL {{
            ?contraw rdfs:label ?contlraw.
            FILTER (lang(?contlraw) = 'en')
        }}
        BIND(COALESCE(?contlraw, "No Label Provided!") AS ?contl)

        OPTIONAL {{
            ?contraw schema:description ?contdraw
            FILTER (lang(?contdraw) = 'en')
        }}
        BIND(COALESCE(?contdraw, "No Description Provided!") AS ?contd)

        OPTIONAL {{
            ?statement5 pq:{series ordinal} ?corder_raw.
        }}
        BIND(COALESCE(?corder_raw, "") AS ?corder)
    }}

    OPTIONAL {{
        ?conitraw p:{contains} ?statement6.
        ?statement6 ps:{contains} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?conitraw), STR(wd:))) AS ?conit)
         
        ?conitraw wdt:{instance of} wd:{computational task}.
        
        OPTIONAL {{
            ?conitraw rdfs:label ?conitlraw.
            FILTER (lang(?conitlraw) = 'en')
        }}
        BIND(COALESCE(?conitlraw, "No Label Provided!") AS ?conitl)
        
        OPTIONAL {{
            ?conitraw schema:description ?conitdraw
            FILTER (lang(?conitdraw) = 'en')
        }}
        BIND(COALESCE(?conitdraw, "No Description Provided!") AS ?conitd)
        
        OPTIONAL {{
            ?statement6 pq:{series ordinal} ?ciorder_raw.
        }}
        BIND(COALESCE(?ciorder_raw, "") AS ?ciorder)
    }}

    OPTIONAL {{
        ?id wdt:{discretized by} ?dbtraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?dbtraw), STR(wd:))) AS ?dbt)
                   
        ?dbtraw wdt:{instance of} wd:{computational task}.
        
        OPTIONAL {{
            ?dbtraw rdfs:label ?dbtlraw.
            FILTER (lang(?dbtlraw) = 'en')
        }}
        BIND(COALESCE(?dbtlraw, "No Label Provided!") AS ?dbtl)

        OPTIONAL {{
            ?dbtraw schema:description ?dbtdraw
            FILTER (lang(?dbtdraw) = 'en')
        }}
        BIND(COALESCE(?dbtdraw, "No Description Provided!") AS ?dbtd)
    }}

    OPTIONAL {{
         ?dtraw wdt:{discretized by} ?id.
         BIND(CONCAT("mardi:", STRAFTER(STR(?dtraw), STR(wd:))) AS ?dt)

         ?dtraw wdt:{instance of} wd:{computational task}.

         OPTIONAL {{
            ?dtraw rdfs:label ?dtlraw.
            FILTER (lang(?dtlraw) = 'en')
        }}
        BIND(COALESCE(?dtlraw, "No Label Provided!") AS ?dtl)

        OPTIONAL {{
            ?dtraw schema:description ?dtdraw
            FILTER (lang(?dtdraw) = 'en')
        }}
        BIND(COALESCE(?dtdraw, "No Description Provided!") AS ?dtd)
    }}

    OPTIONAL {{
        ?id wdt:{linearized by} ?lbtraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?lbtraw), STR(wd:))) AS ?lbt)
         
        ?lbtraw wdt:{instance of} wd:{computational task}.

        OPTIONAL {{
            ?lbtraw rdfs:label ?lbtlraw.
            FILTER (lang(?lbtlraw) = 'en')
        }}
        BIND(COALESCE(?lbtlraw, "No Label Provided!") AS ?lbtl)

        OPTIONAL {{
            ?lbtraw schema:description ?lbtdraw
            FILTER (lang(?lbtdraw) = 'en')
        }}
        BIND(COALESCE(?lbtdraw, "No Description Provided!") AS ?lbtd)
    }}

    OPTIONAL {{
        ?ltraw wdt:{linearized by} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?ltraw), STR(wd:))) AS ?lt)
         
        ?ltraw wdt:{instance of} wd:{computational task}.

        OPTIONAL {{
            ?ltraw rdfs:label ?ltlraw.
            FILTER (lang(?ltlraw) = 'en')
        }}
        BIND(COALESCE(?ltlraw, "No Label Provided!") AS ?ltl)
        
        OPTIONAL {{
            ?ltraw schema:description ?ltdraw
            FILTER (lang(?ltdraw) = 'en')
        }}
        BIND(COALESCE(?ltdraw, "No Description Provided!") AS ?ltd)
    }}

    OPTIONAL {{
        ?id wdt:{similar to} ?sttraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?sttraw), STR(wd:))) AS ?stt)
         
        ?sttraw wdt:{instance of} wd:{computational task}.
        OPTIONAL {{
            ?sttraw rdfs:label ?sttlraw.
            FILTER (lang(?sttlraw) = 'en')
        }}
        BIND(COALESCE(?sttlraw, "No Label Provided!") AS ?sttl)
        
        OPTIONAL {{
            ?sttraw schema:description ?sttdraw
            FILTER (lang(?sttdraw) = 'en')
        }}
        BIND(COALESCE(?sttdraw, "No Description Provided!") AS ?sttd)
    }}
                                                      
    OPTIONAL {{
        ?id p:{described by source} ?statement_p .
        ?statement_p ps:{described by source} ?pubraw .
        ?statement_p pq:{object has role} ?role .
        VALUES ?role {{ wd:{documentation} wd:{invention} wd:{review} wd:{study} wd:{use} }}
        BIND(CONCAT("mardi:", STRAFTER(STR(?pubraw), STR(wd:))) AS ?pub)

        OPTIONAL {{
            ?pubraw rdfs:label ?publraw.
            FILTER (lang(?publraw) = 'en')
        }}
        BIND(COALESCE(?publraw, "No Label Provided!") AS ?publ)

        OPTIONAL {{
            ?pubraw schema:description ?pubdraw
            FILTER (lang(?pubdraw) = 'en')
        }}
        BIND(COALESCE(?pubdraw, "No Description Provided!") AS ?pubd)
    }}
}}

GROUP BY ?is_linear ?is_not_linear ?is_space_continuous ?is_space_discrete ?is_time_continuous ?is_time_discrete