site_name: MaRDMO Documentation

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]

nav:
  - Home: index.md
  - Vocabulary: vocabulary.md
  - Concepts:
      - Dynamic Providers: concepts/providers.md
      - Handlers: concepts/handlers.md
      - Publications: concepts/publication.md
      - Export Pipeline: concepts/export.md
  - How to:
      - RDMO:
          - Create a New Attribute: how-to/rdmo/add-attribute.md
          - Create a New Condition: how-to/rdmo/add-condition.md
          - Create a New Option: how-to/rdmo/add-option.md
          - Create a New Optionset: how-to/rdmo/add-optionset.md
          - Create a New Question: how-to/rdmo/add-question.md
      - MaRDMO:
          - Add a Data Property: how-to/mardmo/data-property.md
  - Reference:
      - Core:
          - Entry Points: reference/mardmo.md
          - Checks: reference/checks.md
          - Payload: reference/payload.md
          - Data Access: reference/data.md
          - Utilities: reference/helpers.md
      - Submodules:
          - Model: reference/model.md
          - Algorithm: reference/algorithm.md
          - Workflow: reference/workflow.md
          - Publication: reference/publication.md
          - Search: reference/search.md
