site_name: MaRDMO Documentation

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]

nav:
  - Home: index.md
  - Vocabulary: vocabulary.md
  - Concepts:
      - Dynamic Providers: concepts/providers.md
      - Handlers: concepts/handlers.md
      - Publications: concepts/publication.md
      - Export Pipeline: concepts/export.md
  - How to:
      - How to Create a New Option in RDMO: how-to/add-option-rdmo.md
      - How to Create a New Optionset in RDMO: how-to/add-optionset-rdmo.md
      - How to Add a Data Property in MaRDMO: how-to/data-property.md
  - Reference:
      - Core:
          - Entry Points: reference/mardmo.md
          - Checks: reference/checks.md
          - Payload: reference/payload.md
          - Data Access: reference/data.md
          - Utilities: reference/helpers.md
      - Submodules:
          - Model: reference/model.md
          - Algorithm: reference/algorithm.md
          - Workflow: reference/workflow.md
          - Publication: reference/publication.md
          - Search: reference/search.md
