#Item IDs (QIDs)

scholarly_article='Q1'
english='Q2'
research_workflow='Q3'
mathematical_model='Q4'
method='Q5'
software='Q6'
data_set='Q7'
human='Q8'
researcher='Q9'
scientific_journal='Q10'
publication='Q11'

#Property IDs (PIDs)

wikidata_pid='1'
wikidata_qid='2'
cites_work='3'
instance_of='4'
field_of_work='5'
uses='6'
title='7'
Author='8'
author_name_string='9'
language_of_work_or_name='10'
publication_date='11'
published_in='12'
volume='13'
issue='14'
pages='15'
DOI='16'
main_subject='17'
defining_formula='18'
programmed_in='19'
swMath_work_ID='20'
occupation='21'
ORCID_iD='22'
