PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?ID ?quote ?class     
WHERE {{
        ?idraw rdfs:label {0}.
        BIND(STRAFTER(STR(?idraw), "#") AS ?ID)
        OPTIONAL {{ ?idraw rdfs:comment ?quoteraw}}
        BIND(COALESCE(?quoteraw, "No Description Provided!") AS ?quote)
        ?idraw a ?classraw.
        BIND(STRAFTER(STR(?classraw), "#") AS ?class)
      }}
GROUP BY ?ID ?quote ?class