SELECT DISTINCT
(GROUP_CONCAT(DISTINCT CONCAT(?bench, " | ", ?benchl, " | ", ?benchd); separator=" <|> ") AS ?manifests)
(GROUP_CONCAT(DISTINCT CONCAT(?spec, " | ", ?specl, " | ", ?specd); separator=" <|> ") AS ?specializes)
(GROUP_CONCAT(DISTINCT CONCAT(?specby, " | ", ?specbyl, " | ", ?specbyd); separator=" <|> ") AS ?specialized_by)

WHERE {{

    VALUES ?id {{ wd:{0} }}

    OPTIONAL {{
        ?benchraw wdt:{manifestation of} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?benchraw), STR(wd:))) AS ?bench)

        ?benchraw wdt:{instance of} wd:{benchmark}.

        OPTIONAL {{
            ?benchraw rdfs:label ?benchlraw.
            FILTER (lang(?benchlraw) = 'en')
        }}
        BIND(COALESCE(?benchlraw, "No Label Provided!") AS ?benchl)

        OPTIONAL {{
            ?benchraw schema:description ?benchdraw
            FILTER (lang(?benchdraw) = 'en')
        }}
        BIND(COALESCE(?benchdraw, "No Description Provided!") AS ?benchd)
    }}

    OPTIONAL {{
        ?specraw wdt:{specialized by} ?id.
        BIND(CONCAT("mardi:", STRAFTER(STR(?specraw), STR(wd:))) AS ?spec)

        ?specraw wdt:{instance of} wd:{algorithmic task}

        OPTIONAL {{
            ?specraw rdfs:label ?speclraw.
            FILTER (lang(?speclraw) = 'en')
        }}
        BIND(COALESCE(?speclraw, "No Label Provided!") AS ?specl)

        OPTIONAL {{
            ?specraw schema:description ?specdraw
            FILTER (lang(?specdraw) = 'en')
        }}
        BIND(COALESCE(?specdraw, "No Description Provided!") AS ?specd)
    }}

    OPTIONAL {{
        ?id wdt:{specialized by} ?specbyraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?specbyraw), STR(wd:))) AS ?specby)

        ?specbyraw wdt:{instance of} wd:{algorithmic task}

        OPTIONAL {{
            ?specbyraw rdfs:label ?specbylraw.
            FILTER (lang(?specbylraw) = 'en')
        }}
        BIND(COALESCE(?specbylraw, "No Label Provided!") AS ?specbyl)

        OPTIONAL {{
            ?specbyraw schema:description ?specbydraw
            FILTER (lang(?specbydraw) = 'en')
        }}
        BIND(COALESCE(?specbydraw, "No Description Provided!") AS ?specbyd)
    }}
}}