PROPERTIES = {
    'approximated by':                  'P1655',
    'assumes':                          'P1674',
    'author':                           'P16',
    'author name string':               'P43',
    'cites work':                       'P223',
    'comment':                          'P8',
    'community':                        'P1495',
    'contains':                         'P1560',
    'CPU':                              'P1540',
    'data size':                        'P1542',
    'defining formula':                 'P989',
    'depends on software':              'P342',
    'described by source':              'P286',
    'description':                      'P1459',
    'discretized by':                   'P1656',
    'DOI':                              'P27',
    'edition number':                   'P131',
    'end time':                         'P411',
    'field of work':                    'P437',
    'file extension':                   'P921',
    'has part(s)':                      'P265',
    'implemented by':                   '',
    'input data set':                   'P1605',
    'in defining formula':              'P983',
    'instance of':                      'P31',
    'ISSN':                             'P24',
    'issue':                            'P25',
    'language of work or name':         'P34',
    'linearized by':                    'P1657',
    'location':                         'P365',
    'mandates':                         'P1563',
    'modelled by':                      'P1513',
    'MSC ID':                           'P226',
    'nondimensionalized by':            'P1658',
    'number of processor cores':        'P1565',
    'number of records':                'P139',
    'object has role':                  'P560',
    'ORCID iD':                         'P20',
    'output data set':                  '1606',
    'page(s)':                          'P128',
    'platform':                         'P143',
    'programmed in':                    'P114',
    'publication date':                 'P28',
    'published in':                     'P200',
    'quantity_property':                'P149',
    'QUDT quantity kind ID':            'P1654',
    'serial number':                    'P1570',
    'series ordinal':                   'P146',
    'similar to':                       '',
    'software version identifier':      'P132',
    'source code repository URL':       'P339',
    'specialized by':                   'P1684',
    'swMath work ID':                   'P13',
    'symbol represents':                'P984',
    'title':                            'P159',
    'URL':                              'P188',
    'used by':                          'P147',
    'user manual URL':                  'P340',
    'uses':                             'P557',
    'volume':                           'P26',
    'Wikidata QID':                     'P12',
    'zbMATH author ID':                 'P676'
}

ITEMS = {
    'algorithm':                                        'Q127020',
    'academic discipline':                              'Q60231',
    'binary data':                                      'Q6480276',
    'boundary condition':                               'Q6534259',
    'chemical constant':                                'Q6672074',
    'computational task':                               'Q6534247',
    'compute node':                                     'Q6767935',
    'computer hardware':                                'Q56583',
    'constant':                                         'Q6480317',
    'constraint':                                       'Q6534262',
    'continuous-space equation':                        'Q6672088',
    'continuous-space model':                           'Q6672089',
    'continuous-space quantity':                        'Q6672116',
    'continuous-space quantity kind':                   '', 
    'continuous-space task':                            '',
    'continuous-time equation':                         'Q6672090',
    'continuous-time model':                            'Q6672091',
    'continuous-time quantity':                         '',
    'continuous-time quantity kind':                    '',
    'continuous-time task':                             '',
    'coupling condition':                               'Q6534266',
    'cross-platform reproducible research workflow':    'Q6534214',
    'data publishing':                                  'Q6480291',
    'data set':                                         'Q56885',
    'data type':                                        'Q78802',
    'deterministic equation':                           'Q6672075',
    'deterministic model':                              'Q6672076',
    'deterministic quantity':                           '',
    'deterministic quantity kind':                      '',
    'discrete-space equation':                          'Q6672092',
    'discrete-space model':                             'Q6672093',
    'discrete-space quantity':                          'Q6672117',
    'discrete-space quantity kind':                     '',
    'discrete-space task':                              '',
    'discrete-time equation':                           'Q6672094',
    'discrete-time model':                              'Q6672095',
    'discrete-time quantity':                           '',
    'discrete-time quantity kind':                      '',
    'discrete-time task':                               '',
    'dimensional equation':                             '',
    'dimensional model':                                '',
    'dimensional quantity':                             '',
    'dimensional quantity kind':                        '',
    'dimensionless equation':                           'Q6672079',
    'dimensionless model':                              'Q6672080',
    'dimensionless quantity':                           'Q6482820',
    'dimensionless quantity kind':                      'Q6672113',
    'documentation':                                    'Q6672349',
    'dynamic model':                                    'Q6672082',
    'dynamic equation':                                 'Q6672081',
    'dynamic quantity':                                 'Q6672114',
    'dynamic quantity kind':                            '',
    'final condition':                                  'Q6534267',
    'gigabyte':                                         'Q6534225',
    'initial condition':                                'Q6534264',
    'input':                                            'Q6480299',
    'invention':                                        'Q6672344',
    'kilobyte':                                         'Q6534223',
    'kind of quantity':                                 'Q6534245',
    'linear equation':                                  'Q6672107',
    'linear model':                                     'Q6672112',
    'linear task':                                      'Q6672085',
    'mathematical constant':                            'Q6672097',
    'mathematical expression':                          'Q6481152',
    'mathematical model':                               'Q68663',
    'mathematically reproducible research workflow':    'Q6534210',
    'megabyte':                                         'Q6534224',
    'MathModDB':                                        'Q6534265',
    'method':                                           'Q68669',
    'nonlinear equation':                               'Q6672086',
    'nonlinear task':                                   'Q6672087',
    'nonlinear model':                                  'Q6672110',
    'objective function':                               'Q6534255',
    'open data':                                        'Q6480313',
    'original platform reproducible research workflow': 'Q6534213',
    'output':                                           'Q6480295',
    'parameter':                                        'Q6480341',
    'physical constant':                                'Q6534290',
    'probabilistic equation':                           'Q6672077',
    'probabilistic model':                              'Q6672078',
    'probabilistic quantity':                           '',
    'probabilistic quantity kind':                      '',
    'process step':                                     'Q6486603',
    'proprietary information':                          'Q6480367',
    'publication':                                      'Q56751',
    'quantity':                                         'Q6534237',
    'representation format':                            'Q6534222',
    'research data archiving':                          'Q6480370',
    'research problem':                                 'Q6032837',
    'research tool':                                    'Q77076',
    'research workflow':                                'Q68657',
    'result reproducible research workflow':            'Q6534212',
    'review':                                           'Q6672366',
    'runtime reproducible research workflow':           'Q6534211',
    'scholarly article':                                'Q56887',
    'software':                                         'Q56614',
    'static equation':                                  'Q6672083',
    'static model':                                     'Q6672084',
    'static quantity':                                  'Q6672115',
    'static quantity kind':                             '',
    'study':                                            '',
    'terabyte':                                         'Q6534226',   
    'text data':                                        'Q6534207',
    'transferable research workflow':                   'Q6534215',
    'use':                                              'Q6480405'
}