PROPERTIES = {
    'approximated by':                  'P1065',
    'assumes':                          'P892',
    'author':                           'P20',
    'author name string':               'P21',
    'cites work':                       'P18',
    'comment':                          'P1092',
    'community':                        'P582',
    'contains':                         'P715',
    'CPU':                              'P585',
    'data size':                        'P790',
    'defining formula':                 'P29',
    'depends on software':              'P474',
    'described by source':              'P131',
    'description':                      'P896',
    'discretized by':                   'P1066',
    'DOI':                              'P27',
    'edition number':                   'P568',
    'end time':                         'P791',
    'field of work':                    'P19',
    'file extension':                   'P792',
    'has part(s)':                      'P124',
    'implemented by':                   '1089',
    'in defining formula':              'P597',
    'input data set':                   'P1093',
    'instance of':                      'P3',
    'ISSN':                             'P915',
    'issue':                            'P25',
    'language of work or name':         'P6',
    'linearized by':                    '1067',
    'location':                         'P377',
    'mandates':                         'P794',
    'modelled by':                      'P1046',
    'MSC ID':                           'P349',
    'nondimensionalized by':            'P1068',
    'number of processor cores':        'P588',
    'number of records':                'P328',
    'object has role':                  'P293',
    'ORCID iD':                         'P33',
    'output data set':                  'P1094',
    'page(s)':                          'P26',
    'platform':                         'P402',
    'programmed in':                    'P30',
    'publication date':                 'P22',
    'published in':                     'P23',
    'quantity_property':                'P302',
    'QUDT quantity kind ID':            'P664',
    'serial number':                    'P587',
    'series ordinal':                   'P600',
    'similar to':                       '',
    'software version identifier':      'P472',
    'source code repository URL':       'P69',
    'specialized by':                   'P815',
    'swMath work ID':                   'P31',
    'symbol represents':                'P598',
    'title':                            'P15',
    'URL':                              'P107',
    'used by':                          'P348',
    'user manual URL':                  'P56',
    'uses':                             'P7',
    'volume':                           'P24',
    'Wikidata QID':                     'P2',
    'zbMATH author ID':                 'P369'
}

ITEMS = {
    'algorithm':                                        'Q4629',
    'academic discipline':                              'Q3758',
    'binary data':                                      'Q3742',
    'boundary condition':                               'Q4504',
    'chemical constant':                                '',
    'computational task':                               'Q3863',
    'compute node':                                     'Q13129',
    'computer hardware':                                'Q387',
    'constant':                                         'Q1310',
    'constraint':                                       'Q4507',
    'continuous-space equation':                        '',
    'continuous-space model':                           '',
    'continuous-space quantity':                        '',
    'continuous-space quantity kind':                   '',
    'continuous-space task':                            '',
    'continuous-time equation':                         '',
    'continuous-time model':                            '',
    'continuous-time quantity':                         '',
    'continuous-time quantity kind':                    '',
    'continuous-time task':                             '',
    'coupling condition':                               'Q4540',
    'cross-platform reproducible research workflow':    'Q13165',
    'data publishing':                                  'Q3743',
    'data set':                                         'Q381',
    'data type':                                        'Q1917',
    'deterministic equation':                           '',
    'deterministic model':                              '',
    'deterministic quantity':                           '',
    'deterministic quantity kind':                      '',
    'discrete-space equation':                          '',
    'discrete-space model':                             '',
    'discrete-space quantity':                          '',
    'discrete-space quantity kind':                     '',
    'discrete-space task':                              '',
    'discrete-time equation':                           '',
    'discrete-time model':                              '',
    'discrete-time quantity':                           '',
    'discrete-time quantity kind':                      '',
    'discrete-time task':                               '',
    'dimensional equation':                             '',
    'dimensional model':                                '',
    'dimensional quantity':                             '',
    'dimensional quantity kind':                        '',
    'dimensionless equation':                           '',
    'dimensionless model':                              '',
    'dimensionless quantity':                           '',
    'dimensionless quantity kind':                      '',
    'documentation':                                    '',
    'dynamic model':                                    '',
    'dynamic equation':                                 '',
    'dynamic quantity':                                 '',
    'dynamic quantity kind':                            '',
    'final condition':                                  'Q4541',
    'gigabyte':                                         'Q13147',
    'initial condition':                                'Q3453',
    'input':                                            'Q3744',
    'invention':                                        '',
    'kilobyte':                                         'Q13145',
    'kind of quantity':                                 'Q2829',
    'linear equation':                                  '',
    'linear model':                                     '',
    'linear task':                                      '',
    'mathematical constant':                            'Q2808',
    'mathematical expression':                          'Q1396',
    'mathematical model':                               'Q3204',
    'mathematically reproducible research workflow':    'Q13160',
    'MathModDB':                                        'Q3842',
    'megabyte':                                         'Q13146',
    'method':                                           'Q2822',
    'nonlinear equation':                               '',
    'nonlinear model':                                  '',
    'nonlinear task':                                   '',
    'objective function':                               'Q4501',
    'open data':                                        'Q3745',
    'original platform reproducible research workflow': 'Q13164',
    'output':                                           'Q3746',
    'parameter':                                        'Q1340',
    'physical constant':                                'Q1777',
    'probabilistic equation':                           '',
    'probabilistic model':                              '',
    'probabilistic quantity':                           '',
    'probabilistic quantity kind':                      '',
    'process step':                                     'Q13152',
    'proprietary information':                          'Q3747',
    'publication':                                      'Q428',
    'quantity':                                         'Q4411',
    'representation format':                            'Q13149',
    'research data archiving':                          'Q3748',
    'research problem':                                 'Q3781',
    'research tool':                                    'Q4682',
    'research workflow':                                'Q18',
    'result reproducible research workflow':            'Q13163',
    'review':                                           '',
    'runtime reproducible research workflow':           'Q13162',
    'scholarly article':                                'Q259',
    'software':                                         'Q420',
    'static equation':                                  '',
    'static model':                                     '',
    'static quantity':                                  '',
    'static quantity kind':                             '',
    'study':                                            '',
    'terabyte':                                         'Q13148',
    'text data':                                        '',
    'transferable research workflow':                   'Q13166',
    'use':                                              ''
}