PROPERTIES = {
    'approximated by':                  'P1065',
    'assumes':                          'P892',
    'author':                           'P20',
    'author name string':               'P21',
    'community':                        'P582',
    'contains':                         'P715',
    'defining formula':                 'P29',
    'described by source':              'P131',
    'description':                      'P986',
    'discretized by':                   'P1066',
    'DOI':                              'P27',
    'in defining formula':              'P597',
    'instance of':                      'P3',
    'ISSN':                             'P915',
    'issue':                            'P25',
    'language of work or name':         'P6',
    'linearized by':                    '1067',
    'modelled by':                      'P1046',
    'nondimensionalized by':            'P1068',
    'object has role':                  'P293',
    'ORCID iD':                         'P33',
    'page(s)':                          'P26',
    'publication date':                 'P22',
    'published in':                     'P23',
    'QUDT quantity kind ID':            'P664',
    'similar to':                       '',
    'specialized by':                   'P815',
    'symbol represents':                'P598',
    'title':                            'P15',
    'used by':                          'P348',
    'volume':                           'P24',
    'Wikidata QID':                     'P2',
    'zbMATH author ID':                 'P369'
}

ITEMS = {
    'academic discipline':              'Q3758',
    'boundary condition':               'Q4504',
    'chemical constant':                '',
    'computational task':               'Q3863',
    'constant':                         'Q1310',
    'constraint':                       'Q4507',
    'continuous-space equation':        '',
    'continuous-space model':           '',
    'continuous-space quantity':        '',
    'continuous-space quantity kind':   '',
    'continuous-space task':            '',
    'continuous-time equation':         '',
    'continuous-time model':            '',
    'continuous-time quantity':         '',
    'continuous-time quantity kind':    '',
    'continuous-time task':             '',
    'coupling condition':               'Q4540',
    'deterministic equation':           '',
    'deterministic model':              '',
    'deterministic quantity':           '',
    'deterministic quantity kind':      '',
    'discrete-space equation':          '',
    'discrete-space model':             '',
    'discrete-space quantity':          '',
    'discrete-space quantity kind':     '',
    'discrete-space task':              '',
    'discrete-time equation':           '',
    'discrete-time model':              '',
    'discrete-time quantity':           '',
    'discrete-time quantity kind':      '',
    'discrete-time task':               '',
    'dimensional equation':             '',
    'dimensional model':                '',
    'dimensional quantity':             '',
    'dimensional quantity kind':        '',
    'dimensionless equation':           '',
    'dimensionless model':              '',
    'dimensionless quantity':           '',
    'dimensionless quantity kind':      '',
    'documentation':                    '',
    'dynamic model':                    '',
    'dynamic equation':                 '',
    'dynamic quantity':                 '',
    'dynamic quantity kind':            '',
    'final condition':                  'Q4541',
    'initial condition':                'Q3453',
    'input':                            'Q3744',
    'kind of quantity':                 'Q2829',
    'linear equation':                  '',
    'linear model':                     '',
    'linear task':                      '',
    'mathematical constant':            'Q2808',
    'mathematical expression':          'Q1396',
    'mathematical model':               'Q3204',
    'MathModDB':                        'Q3842',
    'nonlinear equation':               '',
    'nonlinear model':                  '',
    'nonlinear task':                   '',
    'objective function':               'Q4501',
    'output':                           'Q3746',
    'parameter':                        'Q1340',
    'physical constant':                'Q1777',
    'probabilistic equation':           '',
    'probabilistic model':              '',
    'probabilistic quantity':           '',
    'probabilistic quantity kind':      '',
    'publication':                      'Q428',
    'quantity':                         'Q4411',
    'research problem':                 'Q3781',
    'review':                           '',
    'scholarly article':                'Q259',
    'static equation':                  '',
    'static model':                     '',
    'static quantity':                  '',
    'static quantity kind':             '',
    'study':                            '',
    'use':                              ''
}