PROPERTIES = {
    'approximated by':                  'P99024',
    'assumes':                          'P99022',
    'author':                           'P95656',
    'author name string':               'P80807',
    'cites work':                       'P98211',
    'comment':                          'P82004',
    'community':                        'P99018',
    'CPU':                              'P98968',
    'contains':                         'P95822',
    'data size':                        '',
    'defining formula':                 'P99032',
    'depends on software':              'P90491',
    'described by source':              'P85183',
    'description':                      'P96124',
    'discretized by':                   'P99025',
    'DOI':                              'P89784',
    'edition number':                   'P98874',
    'end time':                         'P356',
    'field of work':                    'P128',
    'file extension':                   '',
    'has part(s)':                      'P98076',
    'implemented by':                   '',
    'in defining formula':              'P99033',
    'input data set':                   '',
    'instance of':                      'P82',
    'ISSN':                             'P620',
    'issue':                            'P98860',
    'language of work or name':         'P77090',
    'linearized by':                    'P99026',
    'location':                         'P286',
    'mandates':                         '',
    'modelled by':                      'P99020',
    'MSC ID':                           '',
    'nondimensionalized by':            'P99039',
    'number of processor cores':        'P98966',
    'number of records':                '',
    'object has role':                  'P98849',
    'ORCID iD':                         'P98119',
    'output data set':                  '',
    'page(s)':                          'P98857',
    'platform':                         'P95448',
    'programmed in':                    'P97260',
    'publication date':                 'P761',
    'published in':                     'P98930',
    'QUDT quantity kind ID':            'P99040',
    'quantity_property':                'P84267',
    'serial number':                    '',
    'series ordinal':                   'P551',
    'similar to':                       'P59',
    'software version identifier':      'P97364',
    'source code repository URL':       'P98038',
    'specialized by':                   'P99019',
    'swMath work ID':                   '',
    'symbol represents':                'P99034',
    'title':                            'P77107',
    'URL':                              'P98074',
    'used by':                          'P99023',
    'user manual URL':                  '',
    'uses':                             'P95225',
    'volume':                           'P617',
    'Wikidata QID':                     'P99017',
    'zbMATH author ID':                 'P99041'
}

ITEMS = {
    'algorithm':                                        '',
    'academic discipline':                              'Q68423',
    'binary data':                                      '',
    'boundary condition':                               'Q239462',
    'chemical constant':                                'Q239546',
    'computational task':                               'Q239470',
    'compute node':                                     '',
    'computer hardware':                                '',
    'constant':                                         'Q239478',
    'constraint':                                       'Q239463',
    'continuous-space equation':                        'Q239497',
    'continuous-space model':                           'Q239443',
    'continuous-space quantity':                        'Q239561',
    'continuous-space quantity kind':                   'Q239562',
    'continuous-space task':                            'Q239471',
    'continuous-time equation':                         'Q239499',
    'continuous-time model':                            'Q239444',
    'continuous-time quantity':                         'Q239565',
    'continuous-time quantity kind':                    'Q239566',
    'continuous-time task':                             'Q239472',
    'coupling condition':                               'Q239465',
    'cross-platform reproducible research workflow':    '',
    'data publishing':                                  '',
    'data set':                                         '',
    'data type':                                        '',
    'deterministic equation':                           'Q239489',
    'deterministic model':                              'Q239445',
    'deterministic quantity':                           'Q239549',
    'deterministic quantity kind':                      'Q239550',
    'discrete-space equation':                          'Q239498',
    'discrete-space model':                             'Q239446',
    'discrete-space quantity':                          'Q239563',
    'discrete-space quantity kind':                     'Q239564',
    'discrete-space task':                              'Q239473',
    'discrete-time equation':                           'Q239500',
    'discrete-time model':                              'Q239447',
    'discrete-time quantity':                           'Q239567',
    'discrete-time quantity kind':                      'Q239568',
    'discrete-time task':                               'Q239474',
    'dimensional equation':                             'Q239492',
    'dimensional model':                                'Q239448',
    'dimensional quantity':                             'Q239555',
    'dimensional quantity kind':                        'Q239556',
    'dimensionless equation':                           'Q239491',
    'dimensionless model':                              'Q239449',
    'dimensionless quantity':                           'Q239553',
    'dimensionless quantity kind':                      'Q239554',
    'documentation':                                    'Q239573',
    'dynamic model':                                    'Q239450',
    'dynamic equation':                                 'Q239493',
    'dynamic quantity':                                 'Q239557',
    'dynamic quantity kind':                            'Q239558',
    'final condition':                                  'Q239467',
    'gigabyte':                                         '',
    'initial condition':                                'Q239455',
    'input':                                            'Q239477',
    'invention':                                        'Q239574',
    'kilobyte':                                         '',
    'kind of quantity':                                 'Q239545',
    'linear equation':                                  'Q239495',
    'linear model':                                     'Q239451',
    'linear task':                                      'Q239475',
    'mathematical constant':                            'Q239547',
    'mathematical expression':                          'Q239488',
    'mathematical model':                               'Q239442',
    'mathematically reproducible research workflow':    '',
    'MathModDB':                                        'Q239421',
    'megabyte':                                         '',
    'method':                                           '',
    'nonlinear equation':                               'Q239496',
    'nonlinear model':                                  'Q239452',
    'nonlinear task':                                   'Q239476',
    'objective function':                               'Q239479',
    'open data':                                        '',
    'original platform reproducible research workflow': '',
    'output':                                           'Q239480',
    'parameter':                                        'Q239481',
    'physical constant':                                'Q239548',
    'probabilistic equation':                           'Q239490',
    'probabilistic model':                              'Q239453',
    'probabilistic quantity':                           'Q239551',
    'probabilistic quantity kind':                      'Q239552',
    'process step':                                     '',
    'proprietary information':                          '',
    'publication':                                      'Q224189',
    'quantity':                                         'Q182764',
    'representation format':                            '',
    'research data archiving':                          '',
    'research problem':                                 'Q239427',
    'research tool':                                    '',
    'research workflow':                                '',
    'result reproducible research workflow':            '',
    'review':                                           'Q239576',
    'runtime reproducible research workflow':           '',
    'software':                                         'Q212421',
    'scholarly article':                                'Q212556',
    'static equation':                                  'Q239494',
    'static model':                                     'Q239454',
    'static quantity':                                  'Q239559',
    'static quantity kind':                             'Q239560',
    'study':                                            'Q239575',
    'terabyte':                                         '',
    'text data':                                        '',
    'transferable research workflow':                   '',
    'use':                                              'Q239577'
}