'''Main export entry points and RDMO provider classes for MaRDMO.

Provides:

- :class:`BaseMaRDMOExportProvider` — abstract base carrying the MaRDI Portal
  OAuth2 credentials and callback wiring shared by all providers that need to
  post to the portal.
- :class:`MaRDMOExportProvider` — "Export to MaRDI Portal" button; handles
  preview and authenticated upload for the model, algorithm, and workflow
  documentation catalogs.
- :class:`MaRDMOQueryProvider` — "Query MaRDI Portal" button; handles the
  search-catalog preview and result rendering without requiring OAuth2.
'''

from abc import ABC

from django import forms
from django.conf import settings
from django.http import HttpRequest
from django.shortcuts import redirect, render, reverse
from django.utils.translation import gettext_lazy as _

from rdmo.projects.exports import Export

from .checks import Checks
from .constants import (
    CATALOG_TEMPLATE_MAP,
    CATALOG_MODEL_NAME,
    CATALOG_MODEL_BASICS_NAME,
    CATALOG_ALGORITHM_NAME,
    CATALOG_WORKFLOW_NAME,
)
from .getters import (
    get_answers,
    get_options,
    get_questions,
    get_url
)
from .helpers import (
    is_cyclic,
    process_question_dict,
    topological_order
)
from .oauth2 import OauthProviderMixin
from .views import render_preview

from .model.worker import PrepareModel

from .algorithm.worker import PrepareAlgorithm

from .workflow.worker import PrepareWorkflow
from .search.worker import search
from .publication.worker import PublicationRetriever

_CATALOG_PREPARE_MAP = {
    CATALOG_MODEL_NAME:        ('model',     PrepareModel,     'run_model'),
    CATALOG_MODEL_BASICS_NAME: ('model',     PrepareModel,     'run_model'),
    CATALOG_ALGORITHM_NAME:    ('algorithm', PrepareAlgorithm, 'run_algorithm'),
    CATALOG_WORKFLOW_NAME:     ('workflow',  PrepareWorkflow,  'run_workflow'),
}

class BaseMaRDMOExportProvider(OauthProviderMixin, Export, ABC):
    '''Base export provider wiring MaRDMO to the MaRDI Portal OAuth2 flow.

    Provides the concrete MaRDI Portal URLs and credentials needed by
    :class:`~MaRDMO.oauth2.OauthProviderMixin`.  Subclasses implement
    the catalog-specific :meth:`render` and :meth:`submit_*` methods.
    '''
    @property
    def oauth2_client_id(self):
        '''OAuth2 client ID read from ``settings.MARDMO_PROVIDER["mardi"]``.'''
        return settings.MARDMO_PROVIDER['mardi']['oauth2_client_id']

    @property
    def oauth2_client_secret(self):
        '''OAuth2 client secret read from ``settings.MARDMO_PROVIDER["mardi"]``.'''
        return settings.MARDMO_PROVIDER['mardi']['oauth2_client_secret']

    @property
    def authorize_url(self):
        '''MaRDI Portal OAuth2 authorization endpoint URL.'''
        return f"{get_url('mardi', 'uri')}/w/rest.php/oauth2/authorize"

    @property
    def token_url(self):
        '''MaRDI Portal OAuth2 token exchange endpoint URL.'''
        return f"{get_url('mardi', 'uri')}/w/rest.php/oauth2/access_token"

    @property
    def redirect_path(self):
        '''Callback path registered with the MaRDI Portal OAuth2 application.'''
        return reverse('oauth_callback', args=['wikibase'])

    def get_authorize_params(self, request, state):
        '''Return OAuth2 authorization query parameters for the MaRDI Portal.

        Args:
            request: Django HTTP request (unused — client ID is from settings).
            state:   CSRF state token generated by the OAuth2 flow.

        Returns:
            Dict with ``response_type``, ``client_id``, and ``state`` keys.
        '''
        return {
            'response_type': 'code',
            'client_id': self.oauth2_client_id,
            'state': state
        }

    def get_callback_data(self, request):
        '''Return POST body fields for the MaRDI Portal token exchange request.

        Args:
            request: Django HTTP request supplying the ``code`` GET parameter.

        Returns:
            Dict with ``client_id``, ``client_secret``, ``grant_type``, and
            ``code`` fields.
        '''
        return {
            'client_id': self.oauth2_client_id,
            'client_secret': self.oauth2_client_secret,
            'grant_type': 'authorization_code',
            'code': request.GET.get('code')
        }

class MaRDMOExportProvider(BaseMaRDMOExportProvider):
    '''Export provider for the "Export to MaRDI Portal" button.

    Handles preview and authenticated Wikibase upload for the model, algorithm,
    and workflow documentation catalogs.  Search is handled separately by
    :class:`MaRDMOQueryProvider`.

    Attributes:
        request: The Django HttpRequest associated with the provider.
    '''

    request: HttpRequest

    class ExportForm(forms.Form):
        '''Empty form class required by the RDMO Export provider interface.'''

    def render(self):
        '''Render the catalog-appropriate documentation preview page.

        Dispatches to the correct template based on the active catalog
        (model, algorithm, or workflow).

        Returns:
            HTTP response rendering the preview page, or an error page for
            unsupported catalogs.
        '''

        catalog_slug = str(self.project.catalog).rsplit('/', 1)[-1]
        template = CATALOG_TEMPLATE_MAP.get(catalog_slug)

        if template:
            answers, options = self.get_post_data('preview')
            return render_preview(
                self=self,
                template=template,
                answers=answers,
                option=options,
                submit_label=_('Export to MaRDI Portal'),
        )

        return render(
            self.request,
            'core/error.html',
            {
                'title': _('Catalog Error'),
                'errors': [_('The catalog is not supported by the MaRDMO Plugin.')]
            },
            status=200
        )

    def submit(self):
        '''Dispatch the form submission to the catalog-appropriate export handler.

        Handles the cancel action, checks OAuth2 credentials, then routes to
        :meth:`_submit_catalog` based on the active project catalog.

        Returns:
            HTTP redirect or rendered response from the selected submit method.
        '''
        if 'cancel' in self.request.POST:
            return redirect('project', self.project.id)

        if not (self.oauth2_client_id and self.oauth2_client_secret):
            return render(
                self.request,
                'core/error.html',
                {
                    'title': _('Missing Credentials'),
                    'errors': [_('Credentials for MaRDI Portal are missing!')]
                },
                status=200
            )

        catalog_slug = str(self.project.catalog).rsplit('/', 1)[-1]

        if catalog_slug not in _CATALOG_PREPARE_MAP:
            return render(
                self.request,
                'core/error.html',
                {
                    'title': _('Unknown catalog'),
                    'errors': [_('Cannot handle this catalog type.')]
                },
                status=400
            )

        return self._submit_catalog(catalog_slug)

    def _submit_catalog(self, catalog_slug):
        '''Validate and submit documentation for any supported catalog.

        Runs the catalog-appropriate consistency checks, assembles the Wikibase
        payload, and delegates to :meth:`~.oauth2.OauthProviderMixin.post` for
        the authenticated upload.

        Args:
            catalog_slug: Trailing slug of the active catalog URI.

        Returns:
            HTTP response — either an error page (failed checks) or a redirect
            to the OAuth authorization flow.
        '''
        answers, __ = self.get_post_data()

        __, prepare_class, check_method = _CATALOG_PREPARE_MAP[catalog_slug]

        err = getattr(Checks(), check_method)(
            project = self.project,
            data    = answers,
            catalog = str(self.project.catalog),
        )
        if err:
            return render(
                self.request,
                'core/error.html',
                {
                    'title': _('Incomplete or Inconsistent Documentation'),
                    'errors': err
                },
                status=200
            )

        try:
            payload, dependency = prepare_class().export(
                answers,
                get_url('mardi', 'uri'),
            )
        except (ValueError, KeyError) as err:
            return render(
                self.request,
                'core/error.html',
                {
                    'title': _('Value Error'),
                    'errors': [err]
                },
                status=200
            )

        if is_cyclic(dependency):
            return render(
                self.request,
                'core/error.html',
                {
                    'title': _('Inconsistent Documentation'),
                    'errors': ['Cyclic Dependency Graph']
                },
                status=200
            )

        return self.post(self.request, payload, topological_order(dependency))

    def get_post_data(self, mode = 'submit'):
        '''Collect and pre-process user answers for the documentation catalogs.

        Reads all RDMO project values, applies catalog-specific processing
        (relation resolution, publication retrieval, etc.), and returns the
        structured answers dict alongside the global options dict.

        Supports the model, algorithm, and workflow documentation catalogs.
        The search catalog is handled by :class:`MaRDMOQueryProvider`.

        Args:
            mode: ``'preview'`` additionally fetches publication metadata and
                  runs relation resolution for display; ``'submit'`` (default)
                  skips those steps for a leaner export payload.

        Returns:
            Tuple ``(answers, options)`` where *answers* is a nested dict
            organised by entity type (e.g. ``{"field": {...}, "model": {...}}``)
            and *options* maps RDMO option URIs to their string values.
        '''
        options = get_options()

        catalog_slug = str(self.project.catalog).rsplit('/', 1)[-1]
        entry = _CATALOG_PREPARE_MAP.get(catalog_slug)

        if not entry:
            return render(
                self.request,
                'core/error.html',
                {
                    'title': _('Unknown catalog'),
                    'errors': [_('Cannot handle this catalog type.')]
                },
                status=400
            )

        question_set, PrepareClass, _ = entry
        questions = get_questions(question_set) | get_questions('publication')
        answers = process_question_dict(
            project=self.project,
            questions=questions,
            get_answer=get_answers
        )

        if mode == 'preview':
            publication = PublicationRetriever()
            answers = publication.get_information(
                project=self.project,
                snapshot=self.snapshot,
                answers=answers,
                options=options
            )

        prepare = PrepareClass()
        answers = prepare.preview(answers)

        return answers, options


class MaRDMOQueryProvider(Export):
    '''Export provider for the "Query MaRDI Portal" button.

    Handles the search-catalog preview (showing a form to configure the query)
    and the submit action (executing the search and rendering matching results).
    Does not require OAuth2 — no portal writes are performed.

    Attributes:
        request: The Django HttpRequest associated with the provider.
    '''

    request: HttpRequest

    class ExportForm(forms.Form):
        '''Empty form class required by the RDMO Export provider interface.'''

    def render(self):
        '''Render the search configuration preview page.

        Returns:
            HTTP response rendering ``MaRDMO/serachTemplate.html``, or an error
            page if the active catalog is not the search catalog.
        '''
        if str(self.project.catalog).endswith('mardmo-search-catalog'):
            answers, options = self.get_post_data()
            return render_preview(
                self = self,
                template = 'MaRDMO/searchTemplate.html',
                answers = answers,
                option = options,
                submit_label = _('Query MaRDI Portal'),
            )

        return render(
            self.request,
            'core/error.html',
            {
                'title': _('Catalog Error'),
                'errors': [_('The catalog is not supported by the MaRDMO Query Plugin.')]
            },
            status=200
        )

    def submit(self):
        '''Execute the MaRDI Portal query and render the results page.

        Handles the cancel action (redirects to the project page), then calls
        :meth:`submit_mardmo_search` for the search catalog.

        Returns:
            HTTP redirect or rendered results response.
        '''
        if 'cancel' in self.request.POST:
            return redirect('project', self.project.id)

        if str(self.project.catalog).endswith('mardmo-search-catalog'):
            return self.submit_mardmo_search()

        return render(
            self.request,
            'core/error.html',
            {
                'title': _('Unknown catalog'),
                'errors': [_('Cannot handle this catalog type.')]
            },
            status=400
        )

    def submit_mardmo_search(self):
        '''Execute a MaRDI Portal search and render the matching results.

        Reads the search type from the answers dict to set the result datatype label.

        Returns:
            Rendered ``MaRDMO/searchResults.html`` response with the list of
            matching portal items.
        '''
        answers, options = self.get_post_data()

        if answers['search']['options'] == options['InterdisciplinaryWorkflow']:
            datatype = "Workflow(s)"
        elif answers['search']['options'] == options['MathematicalModel']:
            datatype = "Mathematical Model(s)"
        elif answers['search']['options'] == options['Algorithm']:
            datatype = "Algorithm(s)"
        else:
            datatype = "Unknown"

        return render(
            self.request,
            'MaRDMO/searchResults.html',
            {
                'datatype': datatype,
                'noResults': answers['no_results'],
                'links': answers['links']
            },
            status=200
        )

    def get_post_data(self):
        '''Load and execute the search query for the search catalog.

        Reads the search configuration from RDMO project values and dispatches
        to the :func:`~MaRDMO.search.worker.search` function to retrieve
        matching items from the MaRDI Portal, MathModDB KG, or MathAlgoDB KG.

        Returns:
            Tuple ``(answers, options)`` where *answers* contains the search
            results and *options* maps RDMO option URIs to their string values.
        '''
        options = get_options()

        if str(self.project.catalog).endswith('mardmo-search-catalog'):
            questions = get_questions('search')

            answers = process_question_dict(
                project = self.project,
                questions = questions,
                get_answer = get_answers
            )

            answers = search(answers, options)

            return answers, options

        return render(
            self.request,
            'core/error.html',
            {
                'title': _('Unknown catalog'),
                'errors': [_('Cannot handle this catalog type.')]
            },
            status=400
        )
