
BASE_URI='http://example.com/terms/domain/MaRDI/'

# Language Dictionary

lang_dict={'af':['wikidata:Q14196', 'Afrikaans', 'West Germanic language, spoken in South Africa and Namibia'],
           'ar':['wikidata:Q13955', 'Arabic', 'Semitic language and lingua franca of the Arab world'],
           'bg':['wikidata:Q7918', 'Bulgarian', 'South Slavic language'],
           'bn':['wikidata:Q9610', 'Bangla', 'Indo-Aryan language mostly spoken in Bangladesh and India'],
           'ca':['wikidata:Q7026', 'Catalan', 'Western Romance language'],
           'cs':['wikidata:Q9056', 'Czech', 'West Slavic language'],
           'cy':['wikidata:Q9309', 'Welsh', 'Brythonic language spoken natively in Wales'],
           'da':['wikidata:Q9035', 'Danish', 'North Germanic language spoken in Denmark'],
           'de':['wikidata:Q188', 'German', 'West Germanic language spoken mainly in Central Europe'],
           'el':['wikidata:Q9129', 'Greek', 'Indo-European language'],
           'en':['wikidata:Q1860', 'English', 'West Germanic language'],
           'es':['wikidata:Q1321', 'Spanish', 'Romanic language originating in the Iberian Peninsula'],
           'et':['wikidata:Q9072', 'Estonian', 'Uralic language'],
           'fa':['wikidata:Q9168', 'Persian', 'Southwestern Iranian dialect continuum spoken in the Caucasus, Central Asia, Iran, Kuwait, and Pakistan'],
           'fi':['wikidata:Q1412', 'Finnish', 'Finno-Ugric language mostly spoken in Finland'],
           'fr':['wikidata:Q150', 'French', 'Romance language'],
           'gu':['wikidata:Q5137', 'Gujarati', 'Indo-Aryan language that is spoken on the state of Gujarat'],
           'he':['wikidata:Q9288', 'Hebrew', 'Northwest Semitic language'],
           'hi':['wikidata:Q1568', 'Hindi', 'Indo-Aryan language spoken in India'],
           'hr':['wikidata:Q6654', 'Croatian', 'standardized variety of Serbo-Croatian language, used by Croats'],
           'hu':['wikidata:Q9067', 'Hungarian', 'Urlaic language'],
           'id':['wikidata:Q9240', 'Indonesian', 'official language of Indonesia'],
           'it':['wikidata:Q652', 'Italian', 'Romance language'],
           'ja':['wikidata:Q5287', 'Japanese', 'language spoken in East Asia'],
           'kn':['wikidata:Q33673', 'Kannada', 'Dravidian language'],
           'ko':['wikidata:Q9176', 'Korean', 'language spoken in Korean Peninsula and some part of North-eastern China'],
           'lt':['wikidata:Q9083', 'Lithuanian', 'Baltic language spoken in Lithuania'],
           'lv':['wikidata:Q9078', 'Latvian', 'Baltic language, official in Latvia and the European Union'],
           'mk':['wikidata:Q9296', 'Macedonian', 'South Slavic language mostly spoken in North Macedonia and its neighbouring countries'],
           'ml':['wikidata:Q36236', 'Malayalam', 'Dravidian language of India'],
           'mr':['wikidata:Q1571', 'Marathi', 'Indo-Aryan language'],
           'ne':['wikidata:Q33823', 'Nepali', 'official language of Nepal'],
           'nl':['wikidata:Q7411', 'Dutch', 'West Germanic language'],
           'no':['wikidata:Q9043', 'Norwegian', 'North Germanic language spoken in Norway'],
           'pa':['wikidata:Q58635', 'Punjabi', 'Indo-Aryan language spoken in the Punjab region of Pakistan and India'],
           'pl':['wikidata:Q809', 'Polish', 'West Slavic language'],
           'pt':['wikidata:Q5146', 'Portuguese', 'Western Romance language of the Indo-European language family'],
           'ro':['wikidata:Q7913', 'Romanian', 'Eastern Romance language, official of Romania'],
           'ru':['wikidata:Q7737', 'Russian', 'East Slavic language'],
           'sk':['wikidata:Q9058', 'Slovak', 'West Slavic language spoken in Slovakia'],
           'sl':['wikidata:Q9063', 'Slovene', 'South Slavic language spoken primarily in Slovenia'],
           'so':['wikidata:Q13275', 'Somali', 'Afroasiatic language belonging to the Cushitic branch'],
           'sq':['wikidata:Q8748', 'Albanian', 'Indo-European language, spoken in Albania, Kosovo, North Macedonia and Montenegro as well as Italy, Croatia, Romania and Sebia'],
           'sv':['wikidata:Q9027', 'Swedish', 'North Germanic language spoken in Sweden and Finland'],
           'sw':['wikidata:Q7838', 'Swahili', 'Bantu language spoken mainly in East Africa'],
           'ta':['wikidata:Q5885', 'Tamil', 'Dravidian language native to South India and Sri Lanka'],
           'te':['wikidata:Q8097', 'Telugu', 'Dravidian language native to South India'],
           'th':['wikidata:Q9217', 'Thai', 'Tai language'],
           'tl':['wikidata:Q34057', 'Tagalog', 'Austronesian language and the national language of the Philippines'],
           'tr':['wikidata:Q256', 'Turkish', 'Oghuz Turkic language of the Turkish people'],
           'uk':['wikidata:Q8798', 'Ukrainian', 'East Slavic language'],
           'ur':['wikidata:Q1617', 'Urdu', 'Indo-Aryan language spoken in South Asia'],
           'vi':['wikidata:Q9199', 'Vietnamese', 'Austroasiatic language originating in Vietnam'],
           'zh-cn':['wikidata:Q727694', 'Standard Mandarin', 'standard form of Chinese and the official language of China'],
           'zh-tw':['wikidata:Q262828', 'Standard Taiwanese Mandarin', 'variety of Mandarin serving as the official language of the Republic of China (Taiwan)']}

# Option Dictionary

option = {'YesText': 'https://rdmorganiser.github.io/terms/options/yes_with_text_no/yes',
          'NoText': 'https://rdmorganiser.github.io/terms/options/yes_with_text_no/no',
          'TaskInput': 'http://example.com/terms/options/MaRDI/QuantityAndQuantityKind_kind0',
          'TaskOutput': 'http://example.com/terms/options/MaRDI/QuantityAndQuantityKind_kind1',
          'TaskParameter': 'http://example.com/terms/options/MaRDI/QuantityAndQuantityKind_kind3',
          'Documentation': 'http://example.com/terms/options/MaRDI/operation_modus/modus_0',
          'Search': 'http://example.com/terms/options/MaRDI/operation_modus/modus_1',
          'Local': 'http://example.com/terms/options/MaRDI/publication_type/type_1',
          'Public': 'http://example.com/terms/options/MaRDI/publication_type/type_0',
          'No': 'http://example.com/terms/options/MaRDI/yes_no/no',
          'Yes': 'http://example.com/terms/options/MaRDI/yes_no/yes',
          'Analysis': 'http://example.com/terms/options/MaRDI/workflow_type/type_0',
          'Computation': 'http://example.com/terms/options/MaRDI/workflow_type/type_1',
          'Small': 'http://example.com/terms/options/MaRDI/size/KB',
          'Medium': 'http://example.com/terms/options/MaRDI/size/MB',
          'Large': 'http://example.com/terms/options/MaRDI/size/GB',
          'VeryLarge': 'http://example.com/terms/options/MaRDI/size/TB',
          'Binary': 'http://example.com/terms/options/MaRDI/data_type/type_0',
          'Text': 'http://example.com/terms/options/MaRDI/data_type/type_1',
          'Workflow': 'http://example.com/terms/options/MaRDI/operation_modus_2/workflow',
          'Model': 'http://example.com/terms/options/MaRDI/operation_modus_2/model',
          'Quantity': 'http://example.com/terms/options/MaRDI/QuantityOrQuantityKind0',
          'QuantityKind': 'http://example.com/terms/options/MaRDI/QuantityOrQuantityKind1',
          'GeneralizedByField': 'http://example.com/terms/options/MaRDI/ResearchField_relation0',
          'GeneralizesField': 'http://example.com/terms/options/MaRDI/ResearchField_relation1',
          'SimilarToField': 'http://example.com/terms/options/MaRDI/ResearchField_relation2',
          'GeneralizedByProblem': 'http://example.com/terms/options/MaRDI/ResearchProblem_relation0',
          'GeneralizesProblem': 'http://example.com/terms/options/MaRDI/ResearchProblem_relation1',
          'SimilarToProblem': 'http://example.com/terms/options/MaRDI/ResearchProblem_relation2',
          'IsConvex': 'http://example.com/terms/options/MaRDI/MathModDB/IsConvex',
          'IsNotConvex': 'http://example.com/terms/options/MaRDI/MathModDB/IsNotConvex',
          'IsDeterministic': 'http://example.com/terms/options/MaRDI/MathModDB/IsDeterministic',
          'IsStochastic': 'http://example.com/terms/options/MaRDI/MathModDB/IsStochastic',
          'IsDimensionless': 'http://example.com/terms/options/MaRDI/MathModDB/IsDimensionless',
          'IsDimensional': 'http://example.com/terms/options/MaRDI/MathModDB/IsDimensional',
          'IsDynamic': 'http://example.com/terms/options/MaRDI/MathModDB/IsDynamic',
          'IsStatic': 'http://example.com/terms/options/MaRDI/MathModDB/IsStatic',
          'IsLinear': 'http://example.com/terms/options/MaRDI/MathModDB/IsLinear',
          'IsNotLinear': 'http://example.com/terms/options/MaRDI/MathModDB/IsNotLinear',
          'IsSpaceContinuous': 'http://example.com/terms/options/MaRDI/MathModDB/IsSpaceContinuous',
          'IsSpaceDiscrete': 'http://example.com/terms/options/MaRDI/MathModDB/IsSpaceDiscrete',
          'IsSpaceIndependent': 'http://example.com/terms/options/MaRDI/MathModDB/IsSpaceIndependent',
          'IsTimeContinuous': 'http://example.com/terms/options/MaRDI/MathModDB/IsTimeContinuous',
          'IsTimeDiscrete': 'http://example.com/terms/options/MaRDI/MathModDB/IsTimeDiscrete',
          'IsTimeIndependent': 'http://example.com/terms/options/MaRDI/MathModDB/IsTimeIndependent',
          'GeneralizedByModel': 'http://example.com/terms/options/MaRDI/MathematicalModel_relation0',
          'GeneralizesModel': 'http://example.com/terms/options/MaRDI/MathematicalModel_relation1',
          'DiscretizedByModel': 'http://example.com/terms/options/MaRDI/MathematicalModel_relation2',
          'DiscretizesModel': 'http://example.com/terms/options/MaRDI/MathematicalModel_relation3',
          'ContainedInModel': 'http://example.com/terms/options/MaRDI/MathematicalModel_relation4',
          'ContainsModel': 'http://example.com/terms/options/MaRDI/MathematicalModel_relation5',
          'ApproximatedByModel': 'http://example.com/terms/options/MaRDI/MathematicalModel_relation6',
          'ApproximatesModel': 'http://example.com/terms/options/MaRDI/MathematicalModel_relation7',
          'LinearizedByModel': 'http://example.com/terms/options/MaRDI/MathematicalModel_relation9',
          'LinearizesModel': 'http://example.com/terms/options/MaRDI/MathematicalModel_relation10',
          'SimilarToModel': 'http://example.com/terms/options/MaRDI/MathematicalModel_relation8',
          'ContainedAsAssumptionIn': 'http://example.com/terms/options/MaRDI/MathModDB/ContainedAsAssumptionIn',
          'ContainedAsBoundaryConditionIn': 'http://example.com/terms/options/MaRDI/MathModDB/ContainedAsBoundaryConditionIn',
          'ContainedAsConstraintConditionIn': 'http://example.com/terms/options/MaRDI/MathModDB/ContainedAsConstraintConditionIn',
          'ContainedAsCouplingConditionIn': 'http://example.com/terms/options/MaRDI/MathModDB/ContainedAsCouplingConditionIn',
          'ContainedAsFormulationIn': 'http://example.com/terms/options/MaRDI/MathModDB/ContainedAsFormulationIn',
          'ContainedAsInitialConditionIn': 'http://example.com/terms/options/MaRDI/MathModDB/ContainedAsInitialConditionIn',
          'ContainedAsFinalConditionIn': 'http://example.com/terms/options/MaRDI/MathModDB/ContainedAsFinalConditionIn',
          'ApproximatedByFormulation': 'http://example.com/terms/options/MaRDI/MathematicalFormulation_relation0',
          'ApproximatesFormulation': 'http://example.com/terms/options/MaRDI/MathematicalFormulation_relation1',
          'DiscretizedByFormulation': 'http://example.com/terms/options/MaRDI/MathematicalFormulation_relation2',
          'DiscretizesFormulation': 'http://example.com/terms/options/MaRDI/MathematicalFormulation_relation3',
          'GeneralizedByFormulation': 'http://example.com/terms/options/MaRDI/MathematicalFormulation_relation4',
          'GeneralizesFormulation': 'http://example.com/terms/options/MaRDI/MathematicalFormulation_relation5',
          'NondimensionalizedByFormulation': 'http://example.com/terms/options/MaRDI/MathematicalFormulation_relation6',
          'NondimensionalizesFormulation': 'http://example.com/terms/options/MaRDI/MathematicalFormulation_relation7',
          'LinearizedByFormulation': 'http://example.com/terms/options/MaRDI/MathematicalFormulation_relation9',
          'LinearizesFormulation': 'http://example.com/terms/options/MaRDI/MathematicalFormulation_relation10',
          'SimilarToFormulation': 'http://example.com/terms/options/MaRDI/MathematicalFormulation_relation8',
          'GeneralizedByQuantity': 'http://example.com/terms/options/MaRDI/Quantity_relation0',
          'GeneralizesQuantity': 'http://example.com/terms/options/MaRDI/Quantity_relation1',
          'ApproximatedByQuantity': 'http://example.com/terms/options/MaRDI/Quantity_relation2',
          'ApproximatesQuantity': 'http://example.com/terms/options/MaRDI/Quantity_relation3',
          'LinearizedByQuantity': 'http://example.com/terms/options/MaRDI/Quantity_relation5',
          'LinearizesQuantity': 'http://example.com/terms/options/MaRDI/Quantity_relation6',
          'NondimensionalizedByQuantity': 'http://example.com/terms/options/MaRDI/Quantity_relation7',
          'NondimensionalizesQuantity': 'http://example.com/terms/options/MaRDI/Quantity_relation8',
          'SimilarToQuantity': 'http://example.com/terms/options/MaRDI/Quantity_relation4',
          'GeneralizedByQuantityKind': 'http://example.com/terms/options/MaRDI/QuantityKind_relation0',
          'GeneralizesQuantityKind': 'http://example.com/terms/options/MaRDI/QuantityKind_relation1',
          'NondimensionalizedByQuantityKind': 'http://example.com/terms/options/MaRDI/QuantityKind_relation3',
          'NondimensionalizesQuantityKind': 'http://example.com/terms/options/MaRDI/QuantityKind_relation4',
          'SimilarToQuantityKind': 'http://example.com/terms/options/MaRDI/QuantityKind_relation2',
          'ContainsAssumption': 'http://example.com/terms/options/MaRDI/MathModDB/ContainsAssumption',
          'ContainsBoundaryCondition': 'http://example.com/terms/options/MaRDI/MathModDB/ContainsBoundaryCondition',
          'ContainsConstraintCondition': 'http://example.com/terms/options/MaRDI/MathModDB/ContainsConstraintCondition',
          'ContainsCouplingCondition': 'http://example.com/terms/options/MaRDI/MathModDB/ContainsCouplingCondition',
          'ContainsFormulation': 'http://example.com/terms/options/MaRDI/MathModDB/ContainsFormulation',
          'ContainsInitialCondition': 'http://example.com/terms/options/MaRDI/MathModDB/ContainsInitialCondition',
          'ContainsFinalCondition': 'http://example.com/terms/options/MaRDI/MathModDB/ContainsFinalCondition',
          'ContainsInput': 'http://example.com/terms/options/MaRDI/MathModDB/ContainsInput',
          'ContainsOutput': 'http://example.com/terms/options/MaRDI/MathModDB/ContainsOutput',
          'ContainsObjective': 'http://example.com/terms/options/MaRDI/MathModDB/ContainsObjective',
          'ContainsParameter': 'http://example.com/terms/options/MaRDI/MathModDB/ContainsParameter',
          'GeneralizedByTask': 'http://example.com/terms/options/MaRDI/MathematicalTask_relation0',
          'GeneralizesTask': 'http://example.com/terms/options/MaRDI/MathematicalTask_relation1',
          'DiscretizedByTask': 'http://example.com/terms/options/MaRDI/MathematicalTask_relation2',
          'DiscretizesTask': 'http://example.com/terms/options/MaRDI/MathematicalTask_relation3',
          'ApproximatedByTask': 'http://example.com/terms/options/MaRDI/MathematicalTask_relation4',
          'ApproximatesTask': 'http://example.com/terms/options/MaRDI/MathematicalTask_relation5',
          'LinearizedByTask': 'http://example.com/terms/options/MaRDI/MathematicalTask_relation7',
          'LinearizesTask': 'http://example.com/terms/options/MaRDI/MathematicalTask_relation8',
          'SimilarToTask': 'http://example.com/terms/options/MaRDI/MathematicalTask_relation6',
          'ComputationalTask': 'http://example.com/terms/options/MaRDI/TaskCategory0',
          'ContainedAsInputIn': 'https://mardi4nfdi.de/mathmoddb#containedAsInputIn',
          'ContainedAsOutputIn': 'https://mardi4nfdi.de/mathmoddb#containedAsOutputIn',
          'ContainedAsObjectiveIn': 'https://mardi4nfdi.de/mathmoddb#containedAsObjectiveIn',
          'ContainedAsParameterIn': 'https://mardi4nfdi.de/mathmoddb#containedAsParameterIn',
          'Documents': 'http://example.com/terms/options/MaRDI/Publication_relation0',
          'Invents': 'http://example.com/terms/options/MaRDI/Publication_relation1',
          'Studies': 'http://example.com/terms/options/MaRDI/Publication_relation2',
          'Surveys': 'http://example.com/terms/options/MaRDI/Publication_relation3',
          'Uses': 'http://example.com/terms/options/MaRDI/Publication_relation4'}

# Keys for publication handler

keys = ['publicationQid', 'publicationLabel', 'publicationDescription1', 'authorInfo',
        'entrytypeQid', 'entrytypeLabel', 'entrytypeDescription1',
        'journalQid', 'journalLabel', 'journalDescription1',
        'languageQid', 'languageLabel', 'languageDescription1',
        'title', 'otherAuthor', 'publicationDate', 'volume', 'issue', 'page']

# Answer Dictionary

uNames =['Settings', 'GeneralInformation', 'Creator', 'ProcessStep', 'Publication', 'Models', 'Software', 'Hardware', 'ExperimentalDevice', 'MathematicalArea', 'NonMathematicalDiscipline',
         'DataSet', 'Method', 'Quantity', 'Task', 'ReproducibilityComputational', 'ReproducibilityAnalysis', 'Search', 'ResearchField', 'ResearchProblem', 'AdditionalModel',
         'MathematicalFormulation', 'PublicationModel']

questions = {# Export and Workflow Settings
              uNames[0]+' Documentation': {'uName':uNames[0],'dName':'Documentation','Id': BASE_URI+'Section_0/Set_1/Question_01', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[0]+' DocumentationType': {'uName':uNames[0],'dName':'DocumentationType','Id': BASE_URI+'Section_0/Set_1/Question_02', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[0]+' Public': {'uName':uNames[0],'dName':'Public','Id': BASE_URI+'Section_6/Set_1/Question_01', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[0]+' Preview': {'uName':uNames[0],'dName':'Preview','Id': BASE_URI+'Section_6/Set_1/Question_02', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[0]+' WorkflowType': {'uName':uNames[0],'dName':'WorkflowType','Id': BASE_URI+'Section_2/Set_1/Question_03', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              # General Workflow Information
              uNames[1]+' ProblemStatement': {'uName':uNames[1],'dName':'ProblemStatement','Id': BASE_URI + 'Section_2/Set_1/Question_01', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[1]+' ResearchObjective': {'uName':uNames[1],'dName':'ResearchObjective','Id': BASE_URI + 'Section_2/Set_1/Question_04', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[1]+' Procedure': {'uName':uNames[1],'dName':'Procedure','Id': BASE_URI + 'Section_2/Set_1/Question_05', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[1]+' DataStream': {'uName':uNames[1],'dName':'DataStream','Id': BASE_URI + 'Section_2/Set_3/Question_02', 'set_prefix':False, 'set_index': False, 'collection_index': True},
              # Mathematical Area Information
              uNames[9]+' ID': {'uName':uNames[9],'dName':'ID','Id': BASE_URI+'Section_2/Set_3/Question_00', 'set_prefix':False, 'set_index':True, 'collection_index':True},
              # Non-Mathematical Discipline Information
              uNames[10]+' ID': {'uName':uNames[10],'dName':'ID','Id': BASE_URI+'Section_2/Set_3/Question_01', 'set_prefix':False, 'set_index':True, 'collection_index':True, 'option_text':False, 'external_id':True},
              # Workflow Documentation Creator Information
              uNames[2]+' Name': {'uName':uNames[2],'dName':'Name','Id': BASE_URI + 'Section_0a/Set_1/Question_01', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[2]+' IDs': {'uName':uNames[2],'dName':'IDs','Id': BASE_URI + 'Section_0a/Set_1/Question_02', 'set_prefix':False, 'set_index': False, 'collection_index': True},
              # Related Publication Information
              uNames[4]+' Exists': {'uName':uNames[4],'dName':'Exists','Id': BASE_URI + 'Section_2/Set_1/Question_02', 'set_prefix':False, 'set_index': False, 'collection_index': False, 'option_text': True},
              uNames[4]+' All Authors': {'uName':uNames[4],'dName':'All Authors','Id': BASE_URI + 'Section_2/Set_2/Question_03', 'set_prefix':False, 'set_index': False, 'collection_index': True},
              uNames[4]+' Info': {'uName':uNames[4],'dName':'Info','Id': BASE_URI + 'Section_2/Set_2/Question_00_hidden', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[4]+' Type': {'uName':uNames[4],'dName':'Type','Id': BASE_URI + 'Section_2/Set_2/Question_01_hidden', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[4]+' Title': {'uName':uNames[4],'dName':'Title','Id': BASE_URI + 'Section_2/Set_2/Question_02_hidden', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[4]+' Identified Authors': {'uName':uNames[4],'dName':'Identified Authors','Id':BASE_URI + 'Section_2/Set_2/Question_03_hidden', 'set_prefix':False, 'set_index': False, 'collection_index': True},
              uNames[4]+' Language': {'uName':uNames[4],'dName':'Language','Id': BASE_URI + 'Section_2/Set_2/Question_04_hidden', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[4]+' Journal': {'uName':uNames[4],'dName':'Journal','Id': BASE_URI + 'Section_2/Set_2/Question_05_hidden', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[4]+' Volume': {'uName':uNames[4],'dName':'Volume','Id': BASE_URI + 'Section_2/Set_2/Question_06_hidden', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[4]+' Issue': {'uName':uNames[4],'dName':'Issue','Id': BASE_URI + 'Section_2/Set_2/Question_07_hidden', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[4]+' Pages': {'uName':uNames[4],'dName':'Pages','Id': BASE_URI + 'Section_2/Set_2/Question_08_hidden', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[4]+' Date': {'uName':uNames[4],'dName':'Date','Id': BASE_URI + 'Section_2/Set_2/Question_09_hidden', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              # Model Information
              ## Main Model Info
              uNames[5]+' MathModID': {'uName':uNames[5],'dName':'MathModID','Id': BASE_URI+'Section_3/Set_0/Wiki_01', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[5]+' ID': {'uName':uNames[5],'dName':'ID','Id': BASE_URI+'Section_3/Set_0/Set_0/Question_00', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[5]+' Name': {'uName':uNames[5],'dName':'Name','Id': BASE_URI+'Section_3/Set_0/Set_0/Question_01', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[5]+' Description': {'uName':uNames[5],'dName':'Description','Id': BASE_URI+'Section_3/Set_0/Set_0/Wiki_02', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[5]+' Properties': {'uName':uNames[5],'dName':'Properties','Id': BASE_URI+'Section_3/Set_0/Set_0/Question_02', 'set_prefix':False, 'set_index':True, 'collection_index':True},
              uNames[5]+' Reference': {'uName':uNames[5],'dName':'Reference','Id': BASE_URI+'Section_3/Set_0/Set_0/Question_03', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[5]+' Additional': {'uName':uNames[5],'dName':'Additional','Id': BASE_URI+'Section_3/Set_0/Set_0/Question_06', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              ## Research Field
              uNames[18]+' MathModID': {'uName':uNames[18],'dName':'MathModID','Id': BASE_URI+'Section_3/Set_0/Set_0/Question_04', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[18]+' ID': {'uName':uNames[18],'dName':'ID','Id': BASE_URI+'Section_3a/Set_0/Question_3', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[18]+' Name': {'uName':uNames[18],'dName':'Name','Id': BASE_URI+'Section_3a/Set_0/Question_0', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[18]+' Description': {'uName':uNames[18],'dName':'Description','Id': BASE_URI+'Section_3a/Set_0/Question_1', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[18]+' Reference': {'uName':uNames[18],'dName':'Reference','Id': BASE_URI+'Section_3a/Set_0/Question_2', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[18]+' Relation1': {'uName':uNames[18],'dName':'Relation1','Id': BASE_URI+'Section_3a/Set_0/Set_0/Question_1', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[18]+' Other1': {'uName':uNames[18],'dName':'Other1','Id': BASE_URI+'Section_3a/Set_0/Set_0/Question_0', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              #Research Problem
              uNames[19]+' MathModID': {'uName':uNames[19],'dName':'MathModID','Id': BASE_URI+'Section_3/Set_0/Set_0/Question_05', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[19]+' ID': {'uName':uNames[19],'dName':'ID','Id': BASE_URI+'Section_3a/Set_1/Question_5', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[19]+' Name': {'uName':uNames[19],'dName':'Name','Id': BASE_URI+'Section_3a/Set_1/Question_0', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[19]+' Description': {'uName':uNames[19],'dName':'Description','Id': BASE_URI+'Section_3a/Set_1/Question_1', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[19]+' Reference': {'uName':uNames[19],'dName':'Reference','Id': BASE_URI+'Section_3a/Set_1/Question_2', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[19]+' ResearchField': {'uName':uNames[19],'dName':'ResearchField','Id': BASE_URI+'Section_3a/Set_1/Question_3', 'set_prefix':False, 'set_index':True, 'collection_index':True, 'option_text':False, 'external_id':True},
              uNames[19]+' Models': {'uName':uNames[19],'dName':'Models','Id': BASE_URI+'Section_3a/Set_1/Question_4', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[19]+' Relation1': {'uName':uNames[19],'dName':'Relation1','Id': BASE_URI+'Section_3a/Set_1/Set_0/Question_1', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[19]+' Other1': {'uName':uNames[19],'dName':'Other1','Id': BASE_URI+'Section_3a/Set_1/Set_0/Question_0', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              ## Additional Models
              uNames[20]+' MathModID': {'uName':uNames[20],'dName':'MathModID','Id': BASE_URI+'Section_3a/Set_2/Question_0', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[20]+' ID': {'uName':uNames[20],'dName':'ID','Id': BASE_URI+'Section_3a/Set_2/Set_1/Question_0', 'set_prefix':True, 'set_index':False, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[20]+' Name': {'uName':uNames[20],'dName':'Name','Id': BASE_URI+'Section_3a/Set_2/Set_1/Question_1', 'set_prefix':True, 'set_index':False, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[20]+' Description': {'uName':uNames[20],'dName':'Description','Id': BASE_URI+'Section_3a/Set_2/Set_1/Question_2', 'set_prefix':True, 'set_index':False, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[20]+' Reference': {'uName':uNames[20],'dName':'Reference','Id': BASE_URI+'Section_3a/Set_2/Set_1/Question_3', 'set_prefix':True, 'set_index':False, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[20]+' Properties': {'uName':uNames[20],'dName':'Properties','Id': BASE_URI+'Section_3a/Set_2/Set_1/Question_4', 'set_prefix':True, 'set_index':False, 'collection_index':True, 'option_text':False, 'external_id':False},
              uNames[20]+' ResearchProblem': {'uName':uNames[20],'dName':'ResearchProblem','Id': BASE_URI+'Section_3a/Set_2/Question_4', 'set_prefix':False, 'set_index':True, 'collection_index':True, 'option_text':False, 'external_id':True},
              uNames[20]+' Relation1': {'uName':uNames[20],'dName':'Relation1','Id': BASE_URI+'Section_3a/Set_2/Set_0/Question_1', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[20]+' Other1': {'uName':uNames[20],'dName':'Other1','Id': BASE_URI+'Section_3a/Set_2/Set_0/Question_0', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              ## Mathematical Formulation
              uNames[21]+' MathModID': {'uName':uNames[21],'dName':'MathModID','Id': BASE_URI+'Section_3a/Set_5/Question_0', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[21]+' Definition': {'uName':uNames[21],'dName':'Definition','Id': BASE_URI+'Section_3a/Set_5/Question_1', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[21]+' DefinedQuantity': {'uName':uNames[21],'dName':'DefinedQuantity','Id': BASE_URI+'Section_3a/Set_5/Question_2', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[21]+' ID': {'uName':uNames[21],'dName':'ID','Id': BASE_URI+'Section_3a/Set_5/Set_4/Question_0', 'set_prefix':True, 'set_index':False, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[21]+' Name': {'uName':uNames[21],'dName':'Name','Id': BASE_URI+'Section_3a/Set_5/Set_4/Question_1', 'set_prefix':True, 'set_index':False, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[21]+' Description': {'uName':uNames[21],'dName':'Description','Id': BASE_URI+'Section_3a/Set_5/Set_4/Question_2', 'set_prefix':True, 'set_index':False, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[21]+' Reference': {'uName':uNames[21],'dName':'Reference','Id': BASE_URI+'Section_3a/Set_5/Set_4/Question_3', 'set_prefix':True, 'set_index':False, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[21]+' Properties': {'uName':uNames[21],'dName':'Properties','Id': BASE_URI+'Section_3a/Set_5/Set_4/Question_4', 'set_prefix':True, 'set_index':False, 'collection_index':True, 'option_text':False, 'external_id':False},
              uNames[21]+' Formula': {'uName':uNames[21],'dName':'Formula','Id': BASE_URI+'Section_3a/Set_5/Set_4/Question_5', 'set_prefix':True, 'set_index':False, 'collection_index':True, 'option_text':False, 'external_id':False},
              uNames[21]+' Element Symbol': {'uName':uNames[21],'dName':'Element Symbol','Id': BASE_URI+'Section_3a/Set_5/Set_4/Set_0/Question_0', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[21]+' Element Quantity': {'uName':uNames[21],'dName':'Element Quantity','Id': BASE_URI+'Section_3a/Set_5/Set_4/Set_0/Question_1', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[21]+' Relation1': {'uName':uNames[21],'dName':'Relation1','Id': BASE_URI+'Section_3a/Set_5/Set_2/Question_1', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[21]+' Other1': {'uName':uNames[21],'dName':'Other1','Id': BASE_URI+'Section_3a/Set_5/Set_2/Question_0', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[21]+' Relation2': {'uName':uNames[21],'dName':'Relation2','Id': BASE_URI+'Section_3a/Set_5/Set_1/Question_1', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[21]+' Other2': {'uName':uNames[21],'dName':'Other2','Id': BASE_URI+'Section_3a/Set_5/Set_1/Question_0', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[21]+' Relation3': {'uName':uNames[21],'dName':'Relation3','Id': BASE_URI+'Section_3a/Set_5/Set_3/Question_1', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[21]+' Other3': {'uName':uNames[21],'dName':'Other3','Id': BASE_URI+'Section_3a/Set_5/Set_3/Question_0', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              ## Quantities
              uNames[13]+' MathModID': {'uName':uNames[13],'dName':'MathModID','Id': BASE_URI+'Section_3/Set_0/Set_0/Question_07', 'set_prefix':False, 'set_index':False, 'collection_index':True, 'option_text':False, 'external_id':True},
              uNames[13]+' ID': {'uName':uNames[13],'dName':'ID','Id': BASE_URI+'Section_3a/Set_3/Question_5', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[13]+' Name': {'uName':uNames[13],'dName':'Name','Id': BASE_URI+'Section_3a/Set_3/Question_0', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[13]+' Description': {'uName':uNames[13],'dName':'Description','Id': BASE_URI+'Section_3a/Set_3/Question_1', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[13]+' Reference': {'uName':uNames[13],'dName':'Reference','Id': BASE_URI+'Section_3a/Set_3/Question_2', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[13]+' QorQK': {'uName':uNames[13],'dName':'QorQK','Id': BASE_URI+'Section_3a/Set_3/Question_6', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[13]+' PropertiesQ': {'uName':uNames[13],'dName':'PropertiesQ','Id': BASE_URI+'Section_3a/Set_3/Question_3', 'set_prefix':False, 'set_index':True, 'collection_index':True, 'option_text':False, 'external_id':False},
              uNames[13]+' PropertiesQK': {'uName':uNames[13],'dName':'PropertiesQK','Id': BASE_URI+'Section_3a/Set_3/Question_7', 'set_prefix':False, 'set_index':True, 'collection_index':True, 'option_text':False, 'external_id':False},
              uNames[13]+' RelationQ1': {'uName':uNames[13],'dName':'RelationQ1','Id': BASE_URI+'Section_3a/Set_3/Set_0/Question_1', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[13]+' OtherQ1': {'uName':uNames[13],'dName':'OtherQ1','Id': BASE_URI+'Section_3a/Set_3/Set_0/Question_0', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[13]+' RelationQK1': {'uName':uNames[13],'dName':'RelationQK1','Id': BASE_URI+'Section_3a/Set_4/Set_0/Question_1', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[13]+' OtherQK1': {'uName':uNames[13],'dName':'OtherQK1','Id': BASE_URI+'Section_3a/Set_4/Set_0/Question_0', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[13]+' RelationQ2': {'uName':uNames[13],'dName':'RelationQ2','Id': BASE_URI+'Section_3a/Set_4/Set_1/Question_1', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[13]+' OtherQ2': {'uName':uNames[13],'dName':'OtherQ2','Id': BASE_URI+'Section_3a/Set_4/Set_1/Question_0', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[13]+' RelationQK2': {'uName':uNames[13],'dName':'RelationQK2','Id': BASE_URI+'Section_3a/Set_3/Set_1/Question_0', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[13]+' OtherQK2': {'uName':uNames[13],'dName':'OtherQK2','Id': BASE_URI+'Section_3a/Set_3/Set_1/Question_1', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              ## Task
              uNames[14]+' MathModID': {'uName':uNames[14],'dName':'MathModID','Id': BASE_URI+'Section_3a/Set_6/Question_0', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[14]+' ID': {'uName':uNames[14],'dName':'ID','Id': BASE_URI+'Section_3a/Set_6/Set_0/Question_0', 'set_prefix':True, 'set_index':False, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[14]+' Name': {'uName':uNames[14],'dName':'Name','Id': BASE_URI+'Section_3a/Set_6/Set_0/Question_1', 'set_prefix':True, 'set_index':False, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[14]+' Description': {'uName':uNames[14],'dName':'Description','Id': BASE_URI+'Section_3a/Set_6/Set_0/Question_2', 'set_prefix':True, 'set_index':False, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[14]+' Reference': {'uName':uNames[14],'dName':'Reference','Id': BASE_URI+'Section_3a/Set_6/Set_0/Question_3', 'set_prefix':True, 'set_index':False, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[14]+' Properties': {'uName':uNames[14],'dName':'Properties','Id': BASE_URI+'Section_3a/Set_6/Set_0/Question_4', 'set_prefix':True, 'set_index':False, 'collection_index':True, 'option_text':False, 'external_id':False},
              uNames[14]+' TaskClass': {'uName':uNames[14],'dName':'TaskClass','Id': BASE_URI+'Section_3a/Set_6/Set_0/Question_5', 'set_prefix':True, 'set_index':False, 'collection_index':True, 'option_text':False, 'external_id':False},
              uNames[14]+' Relation1': {'uName':uNames[14],'dName':'Relation1','Id': BASE_URI+'Section_3a/Set_6/Set_0/Set_0/Question_0', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[14]+' Other1': {'uName':uNames[14],'dName':'Other1','Id': BASE_URI+'Section_3a/Set_6/Set_0/Set_0/Question_1', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[14]+' Relation2': {'uName':uNames[14],'dName':'Relation2','Id': BASE_URI+'Section_3a/Set_6/Set_0/Set_1/Question_0', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[14]+' Other2': {'uName':uNames[14],'dName':'Other2','Id': BASE_URI+'Section_3a/Set_6/Set_0/Set_1/Question_1', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[14]+' Model': {'uName':uNames[14],'dName':'Model','Id': BASE_URI+'Section_3a/Set_6/Question_1', 'set_prefix':False, 'set_index':True, 'collection_index':True, 'option_text':False, 'external_id':True},
              uNames[14]+' ResearchProblem': {'uName':uNames[14],'dName':'ResearchProblem','Id': BASE_URI+'Section_3a/Set_6/Question_2', 'set_prefix':False, 'set_index':True, 'collection_index':True, 'option_text':False, 'external_id':True},
              uNames[14]+' Relation3': {'uName':uNames[14],'dName':'Relation3','Id': BASE_URI+'Section_3a/Set_6/Set_1/Question_0', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[14]+' Other3': {'uName':uNames[14],'dName':'Other3','Id': BASE_URI+'Section_3a/Set_6/Set_1/Question_1', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              ## Publication Model
              uNames[22]+' MathModID': {'uName':uNames[22],'dName':'MathModID','Id': BASE_URI+'Section_3a/Set_7/Question_0', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[22]+' Name': {'uName':uNames[22],'dName':'Name','Id': BASE_URI+'Section_3a/Set_7/Set_1/Question_1', 'set_prefix':True, 'set_index':False, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[22]+' Reference': {'uName':uNames[22],'dName':'Reference','Id': BASE_URI+'Section_3a/Set_7/Set_1/Question_0', 'set_prefix':True, 'set_index':False, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[22]+' Relation1': {'uName':uNames[22],'dName':'Relation1','Id': BASE_URI+'Section_3a/Set_7/Set_0/Question_1', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':False},
              uNames[22]+' Other1': {'uName':uNames[22],'dName':'Other1','Id': BASE_URI+'Section_3a/Set_7/Set_0/Question_0', 'set_prefix':True, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              # Software Information
              uNames[6]+' ID': {'uName':uNames[6],'dName':'ID','Id': BASE_URI+'Section_4/Set_3/Question_01', 'set_prefix':False, 'set_index': True, 'collection_index': False, 'option_text':False, 'external_id':True},
              uNames[6]+' Name': {'uName':uNames[6],'dName':'Name','Id': BASE_URI+'Section_4/Set_3/Question_02', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[6]+' Description': {'uName':uNames[6],'dName':'Description','Id': BASE_URI+'Section_4/Set_3/Question_03', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[6]+' SubProperty': {'uName':uNames[6],'dName':'SubProperty','Id': BASE_URI+'Section_4/Set_3/Question_05', 'set_prefix':False, 'set_index': True, 'collection_index': True, 'option_text': False, 'external_id': True},
              uNames[6]+' Reference': {'uName':uNames[6],'dName':'Reference','Id': BASE_URI+'Section_4/Set_3/Question_00', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[6]+' Version': {'uName':uNames[6],'dName':'Version','Id': BASE_URI+'Section_4/Set_3/Question_04', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[6]+' Dependency': {'uName':uNames[6],'dName':'Dependency','Id': BASE_URI+'Section_4/Set_3/Question_06', 'set_prefix':False, 'set_index': True, 'collection_index': True},
              uNames[6]+' Versioned': {'uName':uNames[6],'dName':'Versioned','Id': BASE_URI+'Section_4/Set_3/Question_07', 'set_prefix':False, 'set_index': True, 'collection_index': False, 'option_text': True},
              uNames[6]+' Published': {'uName':uNames[6],'dName':'Published','Id': BASE_URI+'Section_4/Set_3/Question_08',  'set_prefix':False, 'set_index': True, 'collection_index': False, 'option_text': True},
              uNames[6]+' Documented': {'uName':uNames[6],'dName':'Documented','Id': BASE_URI+'Section_4/Set_3/Question_09', 'set_prefix':False, 'set_index': True, 'collection_index': False, 'option_text': True},
              # Hardware Information
              uNames[7]+' ID': {'uName':uNames[7],'dName':'ID','Id': BASE_URI+'Section_4/Set_4/Question_01', 'set_prefix':False, 'set_index': True, 'collection_index': False, 'option_text':False, 'external_id':True},
              uNames[7]+' Name': {'uName':uNames[7],'dName':'Name','Id': BASE_URI+'Section_4/Set_4/Question_02', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[7]+' Description': {'uName':uNames[7],'dName':'Description','Id': BASE_URI+'Section_4/Set_4/Question_07', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[7]+' SubProperty': {'uName':uNames[7],'dName':'SubProperty','Id': BASE_URI+'Section_4/Set_4/Question_03', 'set_prefix':False, 'set_index': True, 'collection_index': True, 'option_text':False, 'external_id':True},
              uNames[7]+' SubProperty2': {'uName':uNames[7],'dName':'SubProperty2','Id': BASE_URI+'Section_4/Set_4/Question_04', 'set_prefix':False, 'set_index': True, 'collection_index': True, 'option_text':False, 'external_id':True},
              uNames[7]+' Node': {'uName':uNames[7],'dName':'Node','Id': BASE_URI+'Section_4/Set_4/Question_05', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[7]+' Core': {'uName':uNames[7],'dName':'Core','Id': BASE_URI+'Section_4/Set_4/Question_06', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              # Experimental Device Information
              uNames[8]+' ID': {'uName':uNames[8],'dName':'ID','Id': BASE_URI+'Section_4/Set_5/Question_01', 'set_prefix':False, 'set_index': True, 'collection_index': False, 'option_text': False, 'external_id': True},
              uNames[8]+' Name': {'uName':uNames[8],'dName':'Name','Id': BASE_URI+'Section_4/Set_5/Question_02', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[8]+' Description': {'uName':uNames[8],'dName':'Description','Id': BASE_URI+'Section_4/Set_5/Question_03', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[8]+' Version': {'uName':uNames[8],'dName':'Version','Id': BASE_URI+'Section_4/Set_5/Question_04', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[8]+' PartNumber': {'uName':uNames[8],'dName':'PartNumber','Id': BASE_URI+'Section_4/Set_5/Question_05', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[8]+' SerialNumber': {'uName':uNames[8],'dName':'SerialNumber','Id': BASE_URI+'Section_4/Set_5/Question_06', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[8]+' SubProperty': {'uName':uNames[8],'dName':'SubProperty','Id': BASE_URI+'Section_4/Set_5/Question_07', 'set_prefix':False, 'set_index': True, 'collection_index': True, 'option_text':False, 'external_id':True},
              uNames[8]+' SubProperty2': {'uName':uNames[8],'dName':'SubProperty2','Id': BASE_URI+'Section_4/Set_5/Question_08', 'set_prefix':False, 'set_index': True, 'collection_index': True, 'option_text':False, 'external_id':True},
              # Data Set Information
              uNames[11]+' ID': {'uName':uNames[11],'dName':'ID','Id': BASE_URI+'Section_4/Set_6/Question_00', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[11]+' Name': {'uName':uNames[11],'dName':'Name','Id':  BASE_URI+'Section_4/Set_6/Question_01', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[11]+' Description': {'uName':uNames[11],'dName':'Description','Id':  BASE_URI+'Section_4/Set_6/Question_11', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[11]+' Reference': {'uName':uNames[11],'dName':'Reference','Id': BASE_URI+'Section_4/Set_6/Question_10', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[11]+' Size': {'uName':uNames[11],'dName':'Size','Id':  BASE_URI+'Section_4/Set_6/Question_02', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[11]+' DataStructure': {'uName':uNames[11],'dName':'DataStructure','Id':  BASE_URI+'Section_4/Set_6/Question_03', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[11]+' RepresentationFormat': {'uName':uNames[11],'dName':'RepresentationFormat','Id':  BASE_URI+'Section_4/Set_6/Question_04', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[11]+' ExchangeFormat': {'uName':uNames[11],'dName':'ExchangeFormat','Id':  BASE_URI+'Section_4/Set_6/Question_05', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[11]+' BinaryText': {'uName':uNames[11],'dName':'BinaryText','Id':  BASE_URI+'Section_4/Set_6/Question_06', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[11]+' Proprietary': {'uName':uNames[11],'dName':'Proprietary','Id':  BASE_URI+'Section_4/Set_6/Question_07', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[11]+' Publication': {'uName':uNames[11],'dName':'Publication','Id':  BASE_URI+'Section_4/Set_6/Question_08', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[11]+' Archiving': {'uName':uNames[11],'dName':'Archiving','Id':  BASE_URI+'Section_4/Set_6/Question_09', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':True},
              # Method Information
              uNames[12]+' ID': {'uName':uNames[12],'dName':'ID','Id': BASE_URI+'Section_4/Set_2/Question_01', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[12]+' Name': {'uName':uNames[12],'dName':'Name','Id': BASE_URI+'Section_4/Set_2/Question_02', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[12]+' Description': {'uName':uNames[12],'dName':'Description','Id':  BASE_URI+'Section_4/Set_2/Wiki_02', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[12]+' SubProperty': {'uName':uNames[12],'dName':'SubProperty','Id': BASE_URI+'Section_4/Set_2/Wiki_03', 'set_prefix':False, 'set_index':True, 'collection_index':True, 'option_text':False,'external_id':True},
              uNames[12]+' Formular': {'uName':uNames[12],'dName':'Formular','Id': BASE_URI+'Section_4/Set_2/Wiki_04', 'set_prefix':False, 'set_index':True, 'collection_index':True},
              uNames[12]+' Reference': {'uName':uNames[12],'dName':'Reference','Id': BASE_URI+'Section_4/Set_2/Question_00', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[12]+' Parameter': {'uName':uNames[12],'dName':'Parameter','Id': BASE_URI+'Section_4/Set_2/Question_04', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[12]+' Software': {'uName':uNames[12],'dName':'Software','Id': BASE_URI+'Section_4/Set_2/Question_05', 'set_prefix':False, 'set_index':True, 'collection_index':True},
              # Process Step Information
              uNames[3]+' Name': {'uName':uNames[3],'dName':'Name','Id': BASE_URI+'Section_4/Set_1/Question_01', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[3]+' Description': {'uName':uNames[3],'dName':'Description','Id': BASE_URI+'Section_4/Set_1/Question_02', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[3]+' Input': {'uName':uNames[3],'dName':'Input','Id': BASE_URI+'Section_4/Set_1/Question_03', 'set_prefix':False, 'set_index':True, 'collection_index':True},
              uNames[3]+' Output': {'uName':uNames[3],'dName':'Output','Id': BASE_URI+'Section_4/Set_1/Question_04', 'set_prefix':False, 'set_index':True, 'collection_index':True},
              uNames[3]+' Method': {'uName':uNames[3],'dName':'Method','Id': BASE_URI+'Section_4/Set_1/Question_05', 'set_prefix':False, 'set_index':True, 'collection_index':True},
              uNames[3]+' Parameter': {'uName':uNames[3],'dName':'Parameter','Id': BASE_URI+'Section_4/Set_1/Question_06', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[3]+' Environment': {'uName':uNames[3],'dName':'Environment','Id': BASE_URI+'Section_4/Set_1/Question_07', 'set_prefix':False, 'set_index':True, 'collection_index':True},
              uNames[3]+' MathArea': {'uName':uNames[3],'dName':'MathArea','Id': BASE_URI+'Section_4/Set_1/Question_08', 'set_prefix':False, 'set_index':True, 'collection_index':True},
              # Reproducibility
              uNames[15]+ ' Mathematically': {'uName':uNames[15], 'dName':'Mathematically', 'Id':BASE_URI+'Section_5/Set_1/Question_01', 'set_prefix':False,'set_index':False,'collection_index':False,'option_text':False},
              uNames[15]+ ' MathematicallyInfo': {'uName':uNames[15], 'dName':'MathematicallyInfo', 'Id':BASE_URI+'Section_5/Set_1/Question_01a', 'set_prefix':False,'set_index':False,'collection_index':False,'option_text':False},
              uNames[15]+ ' Runtime': {'uName':uNames[15], 'dName':'Runtime', 'Id':BASE_URI+'Section_5/Set_1/Question_02', 'set_prefix':False,'set_index':False,'collection_index':False,'option_text':False},
              uNames[15]+ ' RuntimeInfo': {'uName':uNames[15], 'dName':'RuntimeInfo', 'Id':BASE_URI+'Section_5/Set_1/Question_02a', 'set_prefix':False,'set_index':False,'collection_index':False,'option_text':False},
              uNames[15]+ ' Result': {'uName':uNames[15], 'dName':'Result', 'Id':BASE_URI+'Section_5/Set_1/Question_03', 'set_prefix':False,'set_index':False,'collection_index':False,'option_text':False},
              uNames[15]+ ' ResultInfo': {'uName':uNames[15], 'dName':'ResultInfo', 'Id':BASE_URI+'Section_5/Set_1/Question_03a', 'set_prefix':False,'set_index':False,'collection_index':False,'option_text':False},
              uNames[15]+ ' OriginalHardware': {'uName':uNames[15], 'dName':'OriginalHardware', 'Id':BASE_URI+'Section_5/Set_1/Question_04', 'set_prefix':False,'set_index':False,'collection_index':False,'option_text':False},
              uNames[15]+ ' OriginalHardwareInfo': {'uName':uNames[15], 'dName':'OriginalHardwareInfo', 'Id':BASE_URI+'Section_5/Set_1/Question_04a', 'set_prefix':False,'set_index':False,'collection_index':False,'option_text':False},
              uNames[15]+ ' OtherHardware': {'uName':uNames[15], 'dName':'OtherHardware', 'Id':BASE_URI+'Section_5/Set_1/Question_05', 'set_prefix':False,'set_index':False,'collection_index':False,'option_text':False},
              uNames[15]+ ' OtherHardwareInfo': {'uName':uNames[15], 'dName':'OtherHardwareInfo', 'Id':BASE_URI+'Section_5/Set_1/Question_05a', 'set_prefix':False,'set_index':False,'collection_index':False,'option_text':False},
              uNames[15]+ ' Transferability': {'uName':uNames[15], 'dName':'Transferability', 'Id':BASE_URI+'Section_5/Set_1/Question_06', 'set_prefix':False,'set_index':False,'collection_index':True},
              # Workflow Search 
              uNames[17]+' Search Objective': {'uName':uNames[17], 'dName':'Search Objective', 'Id':BASE_URI+'Section_1/Set_1/Question_00', 'set_prefix':False, 'set_index':False, 'collection_index':False},
              uNames[17]+' Objective Keywords': {'uName':uNames[17], 'dName':'Objective Keywords', 'Id':BASE_URI+'Section_1/Set_1/Question_01', 'set_prefix':False, 'set_index':False, 'collection_index':True},
              uNames[17]+' Search Discipline': {'uName':uNames[17], 'dName':'Search Discipline', 'Id':BASE_URI+'Section_1/Set_1/Question_02', 'set_prefix':False, 'set_index':False, 'collection_index':False},
              uNames[17]+' Discipline Keywords': {'uName':uNames[17], 'dName':'Discipline Keywords', 'Id':BASE_URI+'Section_1/Set_1/Question_03', 'set_prefix':False, 'set_index':False, 'collection_index':True, 'option_text':False, 'external_id':True},
              uNames[17]+' Search Entities': {'uName':uNames[17], 'dName':'Search Entities', 'Id':BASE_URI+'Section_1/Set_1/Question_04', 'set_prefix':False, 'set_index':False, 'collection_index':False},
              uNames[17]+' Entities Keywords': {'uName':uNames[17], 'dName':'Entities Keywords', 'Id':BASE_URI+'Section_1/Set_1/Question_05', 'set_prefix':False, 'set_index':False, 'collection_index':True, 'option_text':False, 'external_id':True}}
              

