
BASE_URI='http://example.com/terms/domain/MaRDI/'

# Language Dictionary

lang_dict={'af':['wikidata:Q14196', 'Afrikaans', 'West Germanic language, spoken in South Africa and Namibia'],
           'ar':['wikidata:Q13955', 'Arabic', 'Semitic language and lingua franca of the Arab world'],
           'bg':['wikidata:Q7918', 'Bulgarian', 'South Slavic language'],
           'bn':['wikidata:Q9610', 'Bangla', 'Indo-Aryan language mostly spoken in Bangladesh and India'],
           'ca':['wikidata:Q7026', 'Catalan', 'Western Romance language'],
           'cs':['wikidata:Q9056', 'Czech', 'West Slavic language'],
           'cy':['wikidata:Q9309', 'Welsh', 'Brythonic language spoken natively in Wales'],
           'da':['wikidata:Q9035', 'Danish', 'North Germanic language spoken in Denmark'],
           'de':['wikidata:Q188', 'German', 'West Germanic language spoken mainly in Central Europe'],
           'el':['wikidata:Q9129', 'Greek', 'Indo-European language'],
           'en':['wikidata:Q1860', 'English', 'West Germanic language'],
           'es':['wikidata:Q1321', 'Spanish', 'Romanic language originating in the Iberian Peninsula'],
           'et':['wikidata:Q9072', 'Estonian', 'Uralic language'],
           'fa':['wikidata:Q9168', 'Persian', 'Southwestern Iranian dialect continuum spoken in the Caucasus, Central Asia, Iran, Kuwait, and Pakistan'],
           'fi':['wikidata:Q1412', 'Finnish', 'Finno-Ugric language mostly spoken in Finland'],
           'fr':['wikidata:Q150', 'French', 'Romance language'],
           'gu':['wikidata:Q5137', 'Gujarati', 'Indo-Aryan language that is spoken on the state of Gujarat'],
           'he':['wikidata:Q9288', 'Hebrew', 'Northwest Semitic language'],
           'hi':['wikidata:Q1568', 'Hindi', 'Indo-Aryan language spoken in India'],
           'hr':['wikidata:Q6654', 'Croatian', 'standardized variety of Serbo-Croatian language, used by Croats'],
           'hu':['wikidata:Q9067', 'Hungarian', 'Urlaic language'],
           'id':['wikidata:Q9240', 'Indonesian', 'official language of Indonesia'],
           'it':['wikidata:Q652', 'Italian', 'Romance language'],
           'ja':['wikidata:Q5287', 'Japanese', 'language spoken in East Asia'],
           'kn':['wikidata:Q33673', 'Kannada', 'Dravidian language'],
           'ko':['wikidata:Q9176', 'Korean', 'language spoken in Korean Peninsula and some part of North-eastern China'],
           'lt':['wikidata:Q9083', 'Lithuanian', 'Baltic language spoken in Lithuania'],
           'lv':['wikidata:Q9078', 'Latvian', 'Baltic language, official in Latvia and the European Union'],
           'mk':['wikidata:Q9296', 'Macedonian', 'South Slavic language mostly spoken in North Macedonia and its neighbouring countries'],
           'ml':['wikidata:Q36236', 'Malayalam', 'Dravidian language of India'],
           'mr':['wikidata:Q1571', 'Marathi', 'Indo-Aryan language'],
           'ne':['wikidata:Q33823', 'Nepali', 'official language of Nepal'],
           'nl':['wikidata:Q7411', 'Dutch', 'West Germanic language'],
           'no':['wikidata:Q9043', 'Norwegian', 'North Germanic language spoken in Norway'],
           'pa':['wikidata:Q58635', 'Punjabi', 'Indo-Aryan language spoken in the Punjab region of Pakistan and India'],
           'pl':['wikidata:Q809', 'Polish', 'West Slavic language'],
           'pt':['wikidata:Q5146', 'Portuguese', 'Western Romance language of the Indo-European language family'],
           'ro':['wikidata:Q7913', 'Romanian', 'Eastern Romance language, official of Romania'],
           'ru':['wikidata:Q7737', 'Russian', 'East Slavic language'],
           'sk':['wikidata:Q9058', 'Slovak', 'West Slavic language spoken in Slovakia'],
           'sl':['wikidata:Q9063', 'Slovene', 'South Slavic language spoken primarily in Slovenia'],
           'so':['wikidata:Q13275', 'Somali', 'Afroasiatic language belonging to the Cushitic branch'],
           'sq':['wikidata:Q8748', 'Albanian', 'Indo-European language, spoken in Albania, Kosovo, North Macedonia and Montenegro as well as Italy, Croatia, Romania and Sebia'],
           'sv':['wikidata:Q9027', 'Swedish', 'North Germanic language spoken in Sweden and Finland'],
           'sw':['wikidata:Q7838', 'Swahili', 'Bantu language spoken mainly in East Africa'],
           'ta':['wikidata:Q5885', 'Tamil', 'Dravidian language native to South India and Sri Lanka'],
           'te':['wikidata:Q8097', 'Telugu', 'Dravidian language native to South India'],
           'th':['wikidata:Q9217', 'Thai', 'Tai language'],
           'tl':['wikidata:Q34057', 'Tagalog', 'Austronesian language and the national language of the Philippines'],
           'tr':['wikidata:Q256', 'Turkish', 'Oghuz Turkic language of the Turkish people'],
           'uk':['wikidata:Q8798', 'Ukrainian', 'East Slavic language'],
           'ur':['wikidata:Q1617', 'Urdu', 'Indo-Aryan language spoken in South Asia'],
           'vi':['wikidata:Q9199', 'Vietnamese', 'Austroasiatic language originating in Vietnam'],
           'zh-cn':['wikidata:Q727694', 'Standard Mandarin', 'standard form of Chinese and the official language of China'],
           'zh-tw':['wikidata:Q262828', 'Standard Taiwanese Mandarin', 'variety of Mandarin serving as the official language of the Republic of China (Taiwan)']}

# Option Dictionary

option = {'YesText': 'https://rdmorganiser.github.io/terms/options/yes_with_text_no/yes',
          'NoText': 'https://rdmorganiser.github.io/terms/options/yes_with_text_no/no',
          'TaskInput': 'http://example.com/terms/options/QuantityAndQuantityKind_kind0',
          'TaskOutput': 'http://example.com/terms/options/QuantityAndQuantityKind_kind1',
          'TaskParameter': 'http://example.com/terms/options/QuantityAndQuantityKind_kind3',
          'TimeDiscrete': 'http://example.com/terms/options/MathematicalModel_property6',
          'SpaceDiscrete': 'http://example.com/terms/options/MathematicalModel_property5',
          'Documentation': 'http://example.com/terms/options/operation_modus/modus_0',
          'Search': 'http://example.com/terms/options/operation_modus/modus_1',
          'Local': 'http://example.com/terms/options/publication_type/type_1',
          'Public': 'http://example.com/terms/options/publication_type/type_0',
          'No': 'http://example.com/terms/options/yes_no/no',
          'Yes': 'http://example.com/terms/options/yes_no/yes',
          'Analysis': 'http://example.com/terms/options/workflow_type/type_0',
          'Computation': 'http://example.com/terms/options/workflow_type/type_1',
          'Small': 'http://example.com/terms/options/size/KB',
          'Medium': 'http://example.com/terms/options/size/MB',
          'Large': 'http://example.com/terms/options/size/GB',
          'VeryLarge': 'http://example.com/terms/options/size/TB',
          'Binary': 'http://example.com/terms/options/data_type/type_0',
          'Text': 'http://example.com/terms/options/data_type/type_1'}

# Keys for publication handler

keys = ['publicationQid', 'publicationLabel', 'publicationDescription1', 'authorInfo',
        'entrytypeQid', 'entrytypeLabel', 'entrytypeDescription1',
        'journalQid', 'journalLabel', 'journalDescription1',
        'languageQid', 'languageLabel', 'languageDescription1',
        'title', 'otherAuthor', 'publicationDate', 'volume', 'issue', 'page']

# Answer Dictionary

uNames =['Settings', 'GeneralInformation', 'Creator', 'ProcessStep', 'Publication', 'Model', 'Software', 'Hardware', 'ExperimentalDevice', 'MathematicalArea', 'NonMathematicalDiscipline',
         'DataSet', 'Method', 'Quantity', 'Task', 'ReproducibilityComputational', 'ReproducibilityAnalysis', 'Search']

questions = {# Export and Workflow Settings
              uNames[0]+' Documentation': {'uName':uNames[0],'dName':'Documentation','Id': BASE_URI+'Section_0/Set_1/Question_01', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[0]+' Public': {'uName':uNames[0],'dName':'Public','Id': BASE_URI+'Section_6/Set_1/Question_01', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[0]+' Preview': {'uName':uNames[0],'dName':'Preview','Id': BASE_URI+'Section_6/Set_1/Question_02', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[0]+' WorkflowType': {'uName':uNames[0],'dName':'WorkflowType','Id': BASE_URI+'Section_2/Set_1/Question_03', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              # General Workflow Information
              uNames[1]+' ProblemStatement': {'uName':uNames[1],'dName':'ProblemStatement','Id': BASE_URI + 'Section_2/Set_1/Question_01', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[1]+' ResearchObjective': {'uName':uNames[1],'dName':'ResearchObjective','Id': BASE_URI + 'Section_2/Set_1/Question_04', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[1]+' Procedure': {'uName':uNames[1],'dName':'Procedure','Id': BASE_URI + 'Section_2/Set_1/Question_05', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[1]+' DataStream': {'uName':uNames[1],'dName':'DataStream','Id': BASE_URI + 'Section_2/Set_3/Question_02', 'set_prefix':False, 'set_index': False, 'collection_index': True},
              # Mathematical Area Information
              uNames[9]+' ID': {'uName':uNames[9],'dName':'ID','Id': BASE_URI+'Section_2/Set_3/Question_00', 'set_prefix':False, 'set_index':True, 'collection_index':True, 'option_text':False, 'external_id':True},
              # Non-Mathematical Discipline Information
              uNames[10]+' ID': {'uName':uNames[10],'dName':'ID','Id': BASE_URI+'Section_2/Set_3/Question_01', 'set_prefix':False, 'set_index':True, 'collection_index':True, 'option_text':False, 'external_id':True},
              # Workflow Documentation Creator Information
              uNames[2]+' Name': {'uName':uNames[2],'dName':'Name','Id': BASE_URI + 'Section_0/Set_1/Question_02', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[2]+' IDs': {'uName':uNames[2],'dName':'IDs','Id': BASE_URI + 'Section_0/Set_1/Question_03', 'set_prefix':False, 'set_index': False, 'collection_index': True},
              # Related Publication Information
              uNames[4]+' Exists': {'uName':uNames[4],'dName':'Exists','Id': BASE_URI + 'Section_2/Set_1/Question_02', 'set_prefix':False, 'set_index': False, 'collection_index': False, 'option_text': True},
              uNames[4]+' All Authors': {'uName':uNames[4],'dName':'All Authors','Id': BASE_URI + 'Section_2/Set_2/Question_03', 'set_prefix':False, 'set_index': False, 'collection_index': True},
              uNames[4]+' Info': {'uName':uNames[4],'dName':'Info','Id': BASE_URI + 'Section_2/Set_2/Question_00_hidden', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[4]+' Type': {'uName':uNames[4],'dName':'Type','Id': BASE_URI + 'Section_2/Set_2/Question_01_hidden', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[4]+' Title': {'uName':uNames[4],'dName':'Title','Id': BASE_URI + 'Section_2/Set_2/Question_02_hidden', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[4]+' Identified Authors': {'uName':uNames[4],'dName':'Identified Authors','Id':BASE_URI + 'Section_2/Set_2/Question_03_hidden', 'set_prefix':False, 'set_index': False, 'collection_index': True},
              uNames[4]+' Language': {'uName':uNames[4],'dName':'Language','Id': BASE_URI + 'Section_2/Set_2/Question_04_hidden', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[4]+' Journal': {'uName':uNames[4],'dName':'Journal','Id': BASE_URI + 'Section_2/Set_2/Question_05_hidden', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[4]+' Volume': {'uName':uNames[4],'dName':'Volume','Id': BASE_URI + 'Section_2/Set_2/Question_06_hidden', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[4]+' Issue': {'uName':uNames[4],'dName':'Issue','Id': BASE_URI + 'Section_2/Set_2/Question_07_hidden', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[4]+' Pages': {'uName':uNames[4],'dName':'Pages','Id': BASE_URI + 'Section_2/Set_2/Question_08_hidden', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              uNames[4]+' Date': {'uName':uNames[4],'dName':'Date','Id': BASE_URI + 'Section_2/Set_2/Question_09_hidden', 'set_prefix':False, 'set_index': False, 'collection_index': False},
              # Model Information
              uNames[5]+' ID': {'uName':uNames[5],'dName':'ID','Id': BASE_URI+'Section_3/Set_0/Wiki_01', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[5]+' Name': {'uName':uNames[5],'dName':'Name','Id': BASE_URI+'Section_3/Set_0/Set_0/Question_01', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[5]+' Description': {'uName':uNames[5],'dName':'Description','Id': BASE_URI+'Section_3/Set_0/Set_0/Wiki_02', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[5]+' Properties': {'uName':uNames[5],'dName':'Properties','Id': BASE_URI+'Section_3/Set_0/Set_0/Question_02', 'set_prefix':False, 'set_index':True, 'collection_index':True},
              uNames[5]+' Reference': {'uName':uNames[5],'dName':'Reference','Id': BASE_URI+'Section_3/Set_0/Set_0/Question_03', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[13]+' Name': {'uName':uNames[13],'dName':'Name','Id': BASE_URI+'Section_3a/Set_5/Set_0/Question_1', 'set_prefix':True, 'set_index':True, 'collection_index':False},
              uNames[13]+' Symbol': {'uName':uNames[13],'dName':'Symbol','Id': BASE_URI+'Section_3a/Set_5/Set_0/Question_0', 'set_prefix':True, 'set_index':True, 'collection_index':False},
              uNames[14]+' Property': {'uName':uNames[14],'dName':'Property','Id': BASE_URI+'Section_3a/Set_6/Set_1/Question_1', 'set_prefix':True, 'set_index':True, 'collection_index':False},
              uNames[14]+' Quantity': {'uName':uNames[14],'dName':'Quantity','Id': BASE_URI+'Section_3a/Set_6/Set_1/Question_0', 'set_prefix':True, 'set_index':True, 'collection_index':False},
              # more to come...
              # Software Information
              uNames[6]+' ID': {'uName':uNames[6],'dName':'ID','Id': BASE_URI+'Section_4/Set_3/Question_01', 'set_prefix':False, 'set_index': True, 'collection_index': False, 'option_text':False, 'external_id':True},
              uNames[6]+' Name': {'uName':uNames[6],'dName':'Name','Id': BASE_URI+'Section_4/Set_3/Question_02', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[6]+' Description': {'uName':uNames[6],'dName':'Description','Id': BASE_URI+'Section_4/Set_3/Question_03', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[6]+' SubProperty': {'uName':uNames[6],'dName':'SubProperty','Id': BASE_URI+'Section_4/Set_3/Question_05', 'set_prefix':False, 'set_index': True, 'collection_index': True},
              uNames[6]+' Reference': {'uName':uNames[6],'dName':'Reference','Id': BASE_URI+'Section_4/Set_3/Question_00', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[6]+' Version': {'uName':uNames[6],'dName':'Version','Id': BASE_URI+'Section_4/Set_3/Question_04', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[6]+' Dependency': {'uName':uNames[6],'dName':'Dependency','Id': BASE_URI+'Section_4/Set_3/Question_06', 'set_prefix':False, 'set_index': True, 'collection_index': True},
              uNames[6]+' Versioned': {'uName':uNames[6],'dName':'Versioned','Id': BASE_URI+'Section_4/Set_3/Question_07', 'set_prefix':False, 'set_index': True, 'collection_index': False, 'option_text': True},
              uNames[6]+' Published': {'uName':uNames[6],'dName':'Published','Id': BASE_URI+'Section_4/Set_3/Question_08',  'set_prefix':False, 'set_index': True, 'collection_index': False, 'option_text': True},
              uNames[6]+' Documented': {'uName':uNames[6],'dName':'Documented','Id': BASE_URI+'Section_4/Set_3/Question_09', 'set_prefix':False, 'set_index': True, 'collection_index': False, 'option_text': True},
              # Hardware Information
              uNames[7]+' ID': {'uName':uNames[7],'dName':'ID','Id': BASE_URI+'Section_4/Set_4/Question_01', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[7]+' Name': {'uName':uNames[7],'dName':'Name','Id': BASE_URI+'Section_4/Set_4/Question_02', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[7]+' Processor': {'uName':uNames[7],'dName':'Processor','Id': BASE_URI+'Section_4/Set_4/Question_03', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[7]+' Compiler': {'uName':uNames[7],'dName':'Compiler','Id': BASE_URI+'Section_4/Set_4/Question_04', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[7]+' Node': {'uName':uNames[7],'dName':'Node','Id': BASE_URI+'Section_4/Set_4/Question_05', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[7]+' Core': {'uName':uNames[7],'dName':'Core','Id': BASE_URI+'Section_4/Set_4/Question_06', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              # Experimental Device Information
              uNames[8]+' ID': {'uName':uNames[8],'dName':'ID','Id': BASE_URI+'Section_4/Set_5/Question_01', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[8]+' Name': {'uName':uNames[8],'dName':'Name','Id': BASE_URI+'Section_4/Set_5/Question_02', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[8]+' Description': {'uName':uNames[8],'dName':'Description','Id': BASE_URI+'Section_4/Set_5/Question_03', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[8]+' Version': {'uName':uNames[8],'dName':'Version','Id': BASE_URI+'Section_4/Set_5/Question_04', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[8]+' PartNumber': {'uName':uNames[8],'dName':'PartNumber','Id': BASE_URI+'Section_4/Set_5/Question_05', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[8]+' SerialNumber': {'uName':uNames[8],'dName':'SerialNumber','Id': BASE_URI+'Section_4/Set_5/Question_06', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[8]+' Location': {'uName':uNames[8],'dName':'Location','Id': BASE_URI+'Section_4/Set_5/Question_07', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              uNames[8]+' Software': {'uName':uNames[8],'dName':'Software','Id': BASE_URI+'Section_4/Set_5/Question_08', 'set_prefix':False, 'set_index': True, 'collection_index': False},
              # Data Set Information
              uNames[11]+' ID': {'uName':uNames[11],'dName':'ID','Id': BASE_URI+'Section_4/Set_6/Question_00', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[11]+' Name': {'uName':uNames[11],'dName':'Name','Id':  BASE_URI+'Section_4/Set_6/Question_01', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[11]+' Description': {'uName':uNames[11],'dName':'Description','Id':  BASE_URI+'Section_4/Set_6/Question_11', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[11]+' Reference': {'uName':uNames[11],'dName':'Reference','Id': BASE_URI+'Section_4/Set_6/Question_10', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[11]+' Size': {'uName':uNames[11],'dName':'Size','Id':  BASE_URI+'Section_4/Set_6/Question_02', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[11]+' DataStructure': {'uName':uNames[11],'dName':'DataStructure','Id':  BASE_URI+'Section_4/Set_6/Question_03', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[11]+' RepresentationFormat': {'uName':uNames[11],'dName':'RepresentationFormat','Id':  BASE_URI+'Section_4/Set_6/Question_04', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[11]+' ExchangeFormat': {'uName':uNames[11],'dName':'ExchangeFormat','Id':  BASE_URI+'Section_4/Set_6/Question_05', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[11]+' BinaryText': {'uName':uNames[11],'dName':'BinaryText','Id':  BASE_URI+'Section_4/Set_6/Question_06', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[11]+' Proprietary': {'uName':uNames[11],'dName':'Proprietary','Id':  BASE_URI+'Section_4/Set_6/Question_07', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[11]+' Publication': {'uName':uNames[11],'dName':'Publication','Id':  BASE_URI+'Section_4/Set_6/Question_08', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[11]+' Archiving': {'uName':uNames[11],'dName':'Archiving','Id':  BASE_URI+'Section_4/Set_6/Question_09', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':True},
              # Method Information
              uNames[12]+' ID': {'uName':uNames[12],'dName':'ID','Id': BASE_URI+'Section_4/Set_2/Question_01', 'set_prefix':False, 'set_index':True, 'collection_index':False, 'option_text':False, 'external_id':True},
              uNames[12]+' Name': {'uName':uNames[12],'dName':'Name','Id': BASE_URI+'Section_4/Set_2/Question_02', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[12]+' Description': {'uName':uNames[12],'dName':'Description','Id':  BASE_URI+'Section_4/Set_2/Wiki_02', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[12]+' Sub Property': {'uName':uNames[12],'dName':'Sub Property','Id': BASE_URI+'Section_4/Set_2/Wiki_03', 'set_prefix':False, 'set_index':True, 'collection_index':True},
              uNames[12]+' Formular': {'uName':uNames[12],'dName':'Formular','Id': BASE_URI+'Section_4/Set_2/Wiki_04', 'set_prefix':False, 'set_index':True, 'collection_index':True},
              uNames[12]+' Reference': {'uName':uNames[12],'dName':'Reference','Id': BASE_URI+'Section_4/Set_2/Question_00', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[12]+' Parameter': {'uName':uNames[12],'dName':'Parameter','Id': BASE_URI+'Section_4/Set_2/Question_04', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[12]+' Software': {'uName':uNames[12],'dName':'Software','Id': BASE_URI+'Section_4/Set_2/Question_05', 'set_prefix':False, 'set_index':True, 'collection_index':True},
              # Process Step Information
              uNames[3]+' Name': {'uName':uNames[3],'dName':'Name','Id': BASE_URI+'Section_4/Set_1/Question_01', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[3]+' Description': {'uName':uNames[3],'dName':'Description','Id': BASE_URI+'Section_4/Set_1/Question_02', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[3]+' Input': {'uName':uNames[3],'dName':'Input','Id': BASE_URI+'Section_4/Set_1/Question_03', 'set_prefix':False, 'set_index':True, 'collection_index':True},
              uNames[3]+' Output': {'uName':uNames[3],'dName':'Output','Id': BASE_URI+'Section_4/Set_1/Question_04', 'set_prefix':False, 'set_index':True, 'collection_index':True},
              uNames[3]+' Method': {'uName':uNames[3],'dName':'Method','Id': BASE_URI+'Section_4/Set_1/Question_05', 'set_prefix':False, 'set_index':True, 'collection_index':True},
              uNames[3]+' Parameter': {'uName':uNames[3],'dName':'Parameter','Id': BASE_URI+'Section_4/Set_1/Question_06', 'set_prefix':False, 'set_index':True, 'collection_index':False},
              uNames[3]+' Environment': {'uName':uNames[3],'dName':'Environment','Id': BASE_URI+'Section_4/Set_1/Question_07', 'set_prefix':False, 'set_index':True, 'collection_index':True},
              uNames[3]+' MathArea': {'uName':uNames[3],'dName':'MathArea','Id': BASE_URI+'Section_4/Set_1/Question_08', 'set_prefix':False, 'set_index':True, 'collection_index':True},
              # Reproducibility Computational
              uNames[15]+ ' Mathematically': {'uName':uNames[15], 'dName':'Mathematically', 'Id':BASE_URI+'Section_5/Set_1/Question_01', 'set_prefix':False,'set_index':False,'collection_index':False,'option_text':True},
              uNames[15]+ ' Runtime': {'uName':uNames[15], 'dName':'Runtime', 'Id':BASE_URI+'Section_5/Set_1/Question_02', 'set_prefix':False,'set_index':False,'collection_index':False,'option_text':True},
              uNames[15]+ ' Result': {'uName':uNames[15], 'dName':'Result', 'Id':BASE_URI+'Section_5/Set_1/Question_03', 'set_prefix':False,'set_index':False,'collection_index':False,'option_text':True},
              uNames[15]+ ' OriginalHardware': {'uName':uNames[15], 'dName':'OriginalHardware', 'Id':BASE_URI+'Section_5/Set_1/Question_04', 'set_prefix':False,'set_index':False,'collection_index':False,'option_text':True},
              uNames[15]+ ' OtherHardware': {'uName':uNames[15], 'dName':'OtherHardware', 'Id':BASE_URI+'Section_5/Set_1/Question_05', 'set_prefix':False,'set_index':False,'collection_index':False,'option_text':True},
              uNames[15]+ ' Transferability': {'uName':uNames[15], 'dName':'Transferability', 'Id':BASE_URI+'Section_5/Set_1/Question_06', 'set_prefix':False,'set_index':False,'collection_index':True},
              # Reproducibility Analysis
              uNames[16]+' OriginalDevice': {'uName':uNames[16], 'dName':'OriginalDevice', 'Id':BASE_URI+'Section_5/Set_2/Question_01', 'set_prefix':False,'set_index':False,'collection_index':False,'option_text':True},
              uNames[16]+' OtherDevice': {'uName':uNames[16], 'dName':'OtherDevice', 'Id':BASE_URI+'Section_5/Set_2/Question_02','set_prefix':False,'set_index':False,'collection_index':False,'option_text':True},
              uNames[16]+' Transferability': {'uName':uNames[16], 'dName':'Transferability', 'Id':BASE_URI+'Section_5/Set_2/Question_03', 'set_prefix':False,'set_index':False,'collection_index':True},
              # Workflow Search 
              uNames[17]+' Search Objective': {'uName':uNames[17], 'dName':'Search Objective', 'Id':BASE_URI+'Section_1/Set_1/Question_00', 'set_prefix':False, 'set_index':False, 'collection_index':False},
              uNames[17]+' Objective Keywords': {'uName':uNames[17], 'dName':'Objective Keywords', 'Id':BASE_URI+'Section_1/Set_1/Question_01', 'set_prefix':False, 'set_index':False, 'collection_index':True},
              uNames[17]+' Search Discipline': {'uName':uNames[17], 'dName':'Search Discipline', 'Id':BASE_URI+'Section_1/Set_1/Question_02', 'set_prefix':False, 'set_index':False, 'collection_index':False},
              uNames[17]+' Discipline Keywords': {'uName':uNames[17], 'dName':'Discipline Keywords', 'Id':BASE_URI+'Section_1/Set_1/Question_03', 'set_prefix':False, 'set_index':False, 'collection_index':True, 'option_text':False, 'external_id':True},
              uNames[17]+' Search Entities': {'uName':uNames[17], 'dName':'Search Entities', 'Id':BASE_URI+'Section_1/Set_1/Question_04', 'set_prefix':False, 'set_index':False, 'collection_index':False},
              uNames[17]+' Entities Keywords': {'uName':uNames[17], 'dName':'Entities Keywords', 'Id':BASE_URI+'Section_1/Set_1/Question_05', 'set_prefix':False, 'set_index':False, 'collection_index':True, 'option_text':False, 'external_id':True}}
              

