PREFIX wd:  <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?doi ?label ?description

WHERE {{
  SERVICE wdsubgraph:scholarly_articles {{
    
    BIND(wd:{0} AS ?idraw) .
    
    OPTIONAL {{ 
      ?idraw wdt:P356 ?doi.
    }}
    
    OPTIONAL {{
      ?idraw rdfs:label ?labelraw_en.
      FILTER (lang(?labelraw_en) = 'en')
    }}
    OPTIONAL {{
      ?idraw rdfs:label ?labelraw_mul.
      FILTER (lang(?labelraw_mul) = 'mul')
    }}
    BIND(COALESCE(COALESCE(?labelraw_en, ?labelraw_mul), "No Label Provided!") As ?label)
   
    OPTIONAL {{
      ?idraw schema:description ?descriptionraw_en.
      FILTER (lang(?descriptionraw_en) = 'en')
    }}
    OPTIONAL {{
      ?idraw schema:description ?descriptionraw_mul.
      FILTER (lang(?descriptionraw_mul) = 'mul')
    }}
    BIND(COALESCE(COALESCE(?descriptionraw_en, ?descriptionraw_mul), "No Label Provided!") As ?description)
  }}
}}
GROUP BY ?doi ?label ?description