SELECT ?doi ?label ?description
       (GROUP_CONCAT(DISTINCT CONCAT(?inv, " | ", ?invl, " | ", ?invd); SEPARATOR=" <|> ") AS ?invents)    
       (GROUP_CONCAT(DISTINCT CONCAT(?doc, " | ", ?docl, " | ", ?docd); SEPARATOR=" <|> ") AS ?documents)
       (GROUP_CONCAT(DISTINCT CONCAT(?stu, " | ", ?stul, " | ", ?stud); SEPARATOR=" <|> ") AS ?studies)
       (GROUP_CONCAT(DISTINCT CONCAT(?rev, " | ", ?revl, " | ", ?revd); SEPARATOR=" <|> ") AS ?surveys)
       (GROUP_CONCAT(DISTINCT CONCAT(?use, " | ", ?usel, " | ", ?used); SEPARATOR=" <|> ") AS ?uses)    

WHERE {{ VALUES ?publication {{ wd:{0} }}

  OPTIONAL {{
    ?invraw p:{described by source} ?statement1.
    ?statement1 ps:{described by source} ?publication.
    BIND(CONCAT("mardi:", STRAFTER(STR(?invraw), STR(wd:))) AS ?inv)
                 
    OPTIONAL {{
      ?invraw rdfs:label ?invlraw.
      FILTER (lang(?invlraw) = 'en')
    }}
    BIND(COALESCE(?invlraw, "No Label Provided!") AS ?invl)
                
    OPTIONAL {{
      ?invraw schema:description ?invdraw
      FILTER (lang(?invdraw) = 'en')
    }}
    BIND(COALESCE(?invdraw, "No Description Provided!") AS ?invd)
                
    ?statement1 pq:{object has role} wd:{invention}.
  }}

  OPTIONAL {{
    ?docraw p:{described by source} ?statement2.
    ?statement2 ps:{described by source} ?publication.
    BIND(CONCAT("mardi:", STRAFTER(STR(?docraw), STR(wd:))) AS ?doc)
                 
    OPTIONAL {{
      ?docraw rdfs:label ?doclraw.
      FILTER (lang(?doclraw) = 'en')
    }}
    BIND(COALESCE(?doclraw, "No Label Provided!") AS ?docl)
                
    OPTIONAL {{
      ?docraw schema:description ?docdraw
      FILTER (lang(?docdraw) = 'en')
    }}
    BIND(COALESCE(?docdraw, "No Description Provided!") AS ?docd)
                
    ?statement2 pq:{object has role} wd:{documentation}.
  }}

  OPTIONAL {{
    ?sturaw p:{described by source} ?statement3.
    ?statement3 ps:{described by source} ?publication.
    BIND(CONCAT("mardi:", STRAFTER(STR(?sturaw), STR(wd:))) AS ?stu)
                 
    OPTIONAL {{
      ?sturaw rdfs:label ?stulraw.
      FILTER (lang(?stulraw) = 'en')
    }}
    BIND(COALESCE(?stulraw, "No Label Provided!") AS ?stul)
    
    OPTIONAL {{
      ?sturaw schema:description ?studraw
      FILTER (lang(?studraw) = 'en')
    }}
    BIND(COALESCE(?studraw, "No Description Provided!") AS ?stud)
    
    ?statement3 pq:{object has role} wd:{study}.
  }}

  OPTIONAL {{
    ?revraw p:{described by source} ?statement4.
    ?statement4 ps:{described by source} ?publication.
    BIND(CONCAT("mardi:", STRAFTER(STR(?revraw), STR(wd:))) AS ?rev)
                 
    OPTIONAL {{
      ?revraw rdfs:label ?revlraw.
      FILTER (lang(?revlraw) = 'en')
    }}
    BIND(COALESCE(?revlraw, "No Label Provided!") AS ?revl)
    
    OPTIONAL {{
      ?revraw schema:description ?revdraw
      FILTER (lang(?revdraw) = 'en')
    }}
    BIND(COALESCE(?revdraw, "No Description Provided!") AS ?revd)
    
    ?statement4 pq:{object has role} wd:{review}.
  }}

  OPTIONAL {{
    ?useraw p:{described by source} ?statement5.
    ?statement5 ps:{described by source} ?publication.
    BIND(CONCAT("mardi:", STRAFTER(STR(?useraw), STR(wd:))) AS ?use)
                 
    OPTIONAL {{
      ?useraw rdfs:label ?uselraw.
      FILTER (lang(?uselraw) = 'en')
    }}
    BIND(COALESCE(?uselraw, "No Label Provided!") AS ?usel)
    
    OPTIONAL {{
      ?useraw schema:description ?usedraw
      FILTER (lang(?usedraw) = 'en')
    }}
    BIND(COALESCE(?usedraw, "No Description Provided!") AS ?used)
    
    ?statement5 pq:{object has role} wd:{use}.
  }} 

  OPTIONAL {{ 
    ?publication wdt:{DOI} ?doi.
  }}

  SERVICE wikibase:label {{ 
    bd:serviceParam wikibase:language "en,mul". 
    ?publication rdfs:label ?labelraw.
    ?publication schema:description ?descriptionraw.
  }}

  BIND(COALESCE(?labelraw, "No Label Provided!") AS ?label)
  BIND(COALESCE(?descriptionraw, "No DescriptionProvided!") AS ?description)
  
}}
GROUP BY ?doi ?label ?description