SELECT DISTINCT
?id
(CONCAT("mardi:", STRAFTER(STR(?id), STR(wd:))) AS ?qid)
?nodes ?cores
(GROUP_CONCAT(DISTINCT CONCAT(?cpu_id, " || ", ?cpul, " || ", ?cpud); separator=" <|> ") AS ?cpu)

WHERE {{

    VALUES ?id {{{0}}}

    OPTIONAL {{
        ?id p:{CPU} ?statement.
        ?statement ps:{CPU} ?cpuraw.
        BIND(CONCAT("mardi:", STRAFTER(STR(?cpuraw), STR(wd:))) AS ?cpu_id)

        OPTIONAL {{
            ?cpuraw rdfs:label ?cpulraw
            FILTER (lang(?cpulraw) = 'en')
        }}

        BIND(COALESCE(?cpulraw, "No Label Provided!") AS ?cpul)

        OPTIONAL {{
            ?cpuraw schema:description ?cpudraw
            FILTER (lang(?cpudraw) = 'en')
        }}

        BIND(COALESCE(?cpudraw, "No Description Provided!") AS ?cpud)

        OPTIONAL {{
            ?cpuraw wdt:{number of processor cores} ?cores.
        }}

        OPTIONAL {{
            ?statement pq:{quantity_property} ?nodes.
        }}
    }}
}}

GROUP BY ?id ?nodes ?cores
