SELECT DISTINCT
(GROUP_CONCAT(DISTINCT(?msc); SEPARATOR=" / ") AS ?mscID)
(GROUP_CONCAT(DISTINCT CONCAT(?input, " | ", ?inputl, " | ", ?inputd); separator=" / ") AS ?inputDataSet)
(GROUP_CONCAT(DISTINCT CONCAT(?output, " | ", ?outputl, " | ", ?outputd); separator=" / ") AS ?outputDataSet)
(GROUP_CONCAT(DISTINCT CONCAT(?method, " | ", ?methodl, " | ", ?methodd, " | ", STR(?methodurl)); separator=" / ") AS ?uses)
(GROUP_CONCAT(DISTINCT CONCAT(?platformsoftware, " | ", ?platformsoftwarel, " | ", ?platformsoftwared); separator=" / ") AS ?platformSoftware)
(GROUP_CONCAT(DISTINCT CONCAT(?platforminstrument, " | ", ?platforminstrumentl, " | ", ?platforminstrumentd); separator=" / ") AS ?platformInstrument)
(GROUP_CONCAT(DISTINCT CONCAT(?field, " | ", ?fieldl, " | ", ?fieldd); separator=" / ") AS ?fieldOfWork)
                                  
WHERE {{
    
    VALUES ?step {{ wd:{0} }}
                                          
    OPTIONAL {{
        ?step wdt:{input data set} ?inputraw
        BIND(CONCAT("mardi:", STRAFTER(STR(?inputraw), STR(wd:))) AS ?input)
        
        OPTIONAL {{
            ?inputraw rdfs:label ?inputlraw
            FILTER (lang(?inputlraw) = 'en')
        }}
        
        BIND(COALESCE(?inputlraw, "No Label Provided!") AS ?inputl)
        
        OPTIONAL {{
            ?inputraw schema:description ?inputdraw
            FILTER (lang(?inputdraw) = 'en')
        }}
        
        BIND(COALESCE(?inputdraw, "No Description Provided!") AS ?inputd)
    }}
                                          
    OPTIONAL {{
        ?step wdt:{output data set} ?outputraw
        BIND(CONCAT("mardi:", STRAFTER(STR(?outputraw), STR(wd:))) AS ?output)
        
        OPTIONAL {{
            ?outputraw rdfs:label ?outputlraw
            FILTER (lang(?outputlraw) = 'en')
        }}
        
        BIND(COALESCE(?outputlraw, "No Label Provided!") AS ?outputl)
        
        OPTIONAL {{
            ?outputraw schema:description ?outputdraw
            FILTER (lang(?outputdraw) = 'en')
        }}
        
        BIND(COALESCE(?outputdraw, "No Description Provided!") AS ?outputd)
    }}

    OPTIONAL {{
        ?step wdt:{uses} ?methodraw
        BIND(CONCAT("mardi:", STRAFTER(STR(?methodraw), STR(wd:))) AS ?method)
        
        OPTIONAL {{
            ?methodraw rdfs:label ?methodlraw
            FILTER (lang(?methodlraw) = 'en')
        }}
        
        BIND(COALESCE(?methodlraw, "No Label Provided!") AS ?methodl)
        
        OPTIONAL {{
            ?methodraw schema:description ?methoddraw
            FILTER (lang(?methoddraw) = 'en')
        }}
        
        BIND(COALESCE(?methoddraw, "No Description Provided!") AS ?methodd)
        
        OPTIONAL {{
            ?methodraw wdt:{URL} ?methodurl
        }}
        
        BIND(COALESCE(?methodurl, "") AS ?methodurl)
    }}
                                          
    OPTIONAL {{
        ?step p:{platform} ?statement0.
        ?statement0 ps:{platform} ?platformsoftwareraw.
        
        ?statement pq:{object has role} ?platformsoftwaretyperaw.
        BIND(CONCAT("", STRAFTER(STR(?platformsoftwaretyperaw), STR(wd:))) AS ?platformsoftwaretype)
        FILTER (?platformsoftwaretype = "{software}")
        
        BIND(CONCAT("mardi:", STRAFTER(STR(?platformsoftwareraw), STR(wd:))) AS ?platformsoftware)
        
        OPTIONAL {{
            ?platformsoftwareraw rdfs:label ?platformsoftwarelraw
            FILTER (lang(?platformsoftwarelraw) = 'en')
        }}
        
        BIND(COALESCE(?platformsoftwarelraw, "No Label Provided!") AS ?platformsoftwarel)
        
        OPTIONAL {{
            ?platformsoftwareraw schema:description ?platformsoftwaredraw
            FILTER (lang(?platformsoftwaredraw) = 'en')
        }}
        
        BIND(COALESCE(?platformsoftwaredraw, "No Description Provided!") AS ?platformsoftwared)
    }}
    
    OPTIONAL {{
        ?step p:{platform} ?statement1.
        ?statement1 ps:{platform} ?platforminstrumentraw.
        
        ?statement pq:{object has role} ?platforminstrumenttyperaw.
        BIND(CONCAT("", STRAFTER(STR(?platforminstrumenttyperaw), STR(wd:))) AS ?platforminstrumenttype)
        FILTER (?platforminstrumenttype = "{research tool}")
        
        BIND(CONCAT("mardi:", STRAFTER(STR(?platforminstrumentraw), STR(wd:))) AS ?platforminstrument)
        
        OPTIONAL {{
            ?platforminstrumentraw rdfs:label ?platforminstrumentlraw
            FILTER (lang(?platforminstrumentlraw) = 'en')
        }}
        
        BIND(COALESCE(?platforminstrumentlraw, "No Label Provided!") AS ?platforminstrumentl)
        
        OPTIONAL {{
            ?platforminstrumentraw schema:description ?platforminstrumentdraw
            FILTER (lang(?platforminstrumentdraw) = 'en')
        }}
        
        BIND(COALESCE(?platforminstrumentdraw, "No Description Provided!") AS ?platforminstrumentd)
    }}
                                          
    OPTIONAL {{
        ?step wdt:{field of work} ?fieldraw.
        
        BIND(CONCAT("mardi:", STRAFTER(STR(?fieldraw), STR(wd:))) AS ?field)
        OPTIONAL {{
            ?fieldraw rdfs:label ?fieldlraw
            FILTER (lang(?fieldlraw) = 'en')
        }}
        
        BIND(COALESCE(?fieldlraw, "No Label Provided!") AS ?fieldl)
        
        OPTIONAL {{
            ?fieldraw schema:description ?fielddraw
            FILTER (lang(?fielddraw) = 'en')
        }}
        
        BIND(COALESCE(?fielddraw, "No Description Provided!") AS ?fieldd)
    }}

    OPTIONAL {{
        ?step wdt:{MSC ID} ?msc.
    }}
}}