SELECT DISTINCT
?id
(REPLACE(STR(?id), "http://www.wikidata.org/entity/", "wikidata:") AS ?qid)
?DOI ?SWMATH ?SOURCECODE_URL ?DESCRIPTION_URL
(GROUP_CONCAT(DISTINCT CONCAT(?pl, " || ", ?pll, " || ", ?pld); separator=" <|> ") AS ?programmed_in)
(GROUP_CONCAT(DISTINCT CONCAT(?dp, " || ", ?dpl, " || ", ?dpd); separator=" <|> ") AS ?depends_on_software)

WHERE {{

    VALUES ?id {{{0}}}

    OPTIONAL {{
        ?id wdt:P277 ?plraw.
        BIND(replace( xsd:string(?plraw),'http://www.wikidata.org/entity/','wikidata:') as ?pl)

        SERVICE wikibase:label {{
            bd:serviceParam wikibase:language "en,[AUTO_LANGUAGE],mul" .
            ?plraw rdfs:label ?pllraw .
            ?plraw schema:description ?pldraw .
        }}

        BIND(COALESCE(?pllraw, "No Label Provided!") AS ?pll)
        BIND(COALESCE(?pldraw, "No Description Provided!") AS ?pld)
    }}

    OPTIONAL {{
        ?id wdt:P1547 ?dpraw.
        BIND(replace( xsd:string(?dpraw),'http://www.wikidata.org/entity/','wikidata:') as ?dp)

        SERVICE wikibase:label {{
            bd:serviceParam wikibase:language "en,[AUTO_LANGUAGE],mul" .
            ?dpraw rdfs:label ?dplraw .
            ?dpraw schema:description ?dpdraw .
        }}

        BIND(COALESCE(?dplraw, "No Label Provided!") AS ?dpl)
        BIND(COALESCE(?dpdraw, "No Description Provided!") AS ?dpd)
    }}

    OPTIONAL {{
        ?id wdt:{DOI} ?DOI.
    }}

    OPTIONAL {{
        ?id wdt:{swMath work ID} ?SWMATH.
    }}

    OPTIONAL {{
        ?id wdt:{source code repository URL} ?SOURCECODE_URL.
    }}

    OPTIONAL {{
        ?id wdt:{described at URL} ?DESCRIPTION_URL.
    }}

}}

GROUP BY ?id ?DOI ?SWMATH ?SOURCECODE_URL ?DESCRIPTION_URL
